// English (US) texts. Same keys in all three languages.
(function (EP) {
  EP.texts['en-US'] = {
    'lang.name': 'English',
    'app.tagline': 'How far can you run?',
    'boot.loading': 'Warming up…',
    'boot.noWebgl': 'This browser could not open the 3D view. Update your browser or try another one.',
    'boot.noSave': 'Your browser blocked storage: you can run, but progress will not be saved.',

    'create.title': 'CREATE YOUR RUNNER',
    'create.step': 'Step {n} of 4',
    'create.who': 'Who is running?',
    'gender.m': 'Male runner',
    'gender.f': 'Female runner',
    'create.nameTitle': 'What is the name?',
    'create.namePh': 'Runner name',
    'create.nameHint': 'Up to 15 letters. It shows on your profile.',
    'create.looks': 'Look',
    'create.skin': 'Skin tone',
    'create.hairStyle': 'Hair',
    'create.hairColor': 'Hair color',
    'hair.curto': 'Short',
    'hair.cacheado': 'Curly',
    'hair.rabo': 'Ponytail',
    'hair.coque': 'Bun',
    'hair.longo': 'Long',
    'hair.raspado': 'Buzz cut',
    'create.outfit': 'Starting outfit',
    'create.outfitHint': 'T-shirt, shorts and sneakers. Pick the colors.',
    'create.shirt': 'T-shirt',
    'create.shorts': 'Shorts',
    'create.shoes': 'Sneakers',
    'create.rotate': 'Drag to turn',
    'ui.next': 'Next',
    'ui.back': 'Back',
    'ui.start': 'Start running',
    'ui.save': 'Save',
    'ui.continue': 'Continue',
    'ui.close': 'Close',
    'ui.cancel': 'Cancel',
    'ui.confirm': 'Erase',

    'home.run': 'RUN',
    'home.total': 'covered',
    'home.coins': 'Coins',
    'home.runner': 'Runner',
    'home.records': 'Records',
    'home.options': 'Options',
    'home.firstRun': 'Your journey starts now',
    'home.best': 'Longest run: {d}',

    'hud.distance': 'DISTANCE',
    'hud.speed': 'KM/H',
    'hud.energy': 'ENERGY',
    'hud.overtakes': 'OVERTAKES',
    'hud.pause': 'Pause',
    'hud.flow': 'FLOW ×{n}',
    'hud.combo': 'COMBO ×{n}',
    'hud.lowEnergy': 'Low energy: ease off and recover',
    'hud.spam': 'Easy! Rhythm beats force',
    'rating.perfect': 'PERFECT',
    'rating.great': 'GREAT',
    'rating.good': 'GOOD',
    'rating.off': 'OFF BEAT',
    'zone.walk': 'WALK',
    'zone.jog': 'JOG',
    'zone.run': 'RUN',
    'zone.fast': 'FAST RUN',
    'zone.sprint': 'SPRINT',

    'tut.1': 'TAP TO RUN',
    'tut.1b': 'Every tap is a stride',
    'tut.1k': 'Tap the screen, click or press SPACE',
    'tut.2': 'KEEP THE RHYTHM',
    'tut.2b': 'Tap on the same beat, like a song',
    'tut.3': 'PERFECT!',
    'tut.3b': 'Keep it up and get into FLOW',
    'tut.4': 'SWIPE TO CHOOSE YOUR PATH',
    'tut.4b': 'Swipe sideways (or use the arrow keys)',
    'tut.done': 'All set! Now it is up to you',

    'fork.title': 'CHOOSE YOUR PATH',
    'fork.hint': 'Swipe sideways',
    'route.bairro': 'NEIGHBORHOOD',
    'route.parque': 'PARK',
    'route.centro': 'DOWNTOWN',
    'route.entered': 'Route: {name}',
    'route.back': 'Back to the neighborhood',
    'perk.energy10': 'Energy +10%',
    'perk.fewerRunners': 'Fewer runners',
    'perk.coins20': 'Coins +20%',
    'perk.moreRunners': 'More runners',

    'ch.label': 'CHALLENGE',
    'ch.flow.title': 'FLOW',
    'ch.flow.desc': 'Hit {n} PERFECT in a row',
    'ch.pace.title': 'PACE',
    'ch.pace.desc': 'Hold {v} km/h (±1) for {n} s',
    'ch.overtake.title': 'OVERTAKE',
    'ch.overtake.desc': 'Pass {n} runners',
    'ch.combo.title': 'COMBO',
    'ch.combo.desc': 'Reach a ×{n} combo',
    'ch.energy.title': 'STAMINA',
    'ch.energy.desc': 'Run hard for {n} s without dropping below 35% energy',
    'ch.sprint.title': 'SPRINT',
    'ch.sprint.desc': 'Run {n} m as fast as you can',
    'ch.draft.title': 'DRAFT',
    'ch.draft.desc': 'Stay right behind another runner for {n} s',
    'ch.pacer.title': 'PACER',
    'ch.pacer.desc': 'Keep up with the flag runner for {n} m',
    'ch.hint.faster': 'speed up',
    'ch.hint.slower': 'ease off',
    'ch.sprintTime': '{t} s',
    'ch.record': 'New 200 m record: {t} s!',
    'hud.draft': 'DRAFT',
    'ch.done': 'CHALLENGE COMPLETE!',
    'ch.failed': 'So close! Next time',
    'ch.reward': '+{n} coins',

    'toast.km': '{n} km this run!',
    'toast.flowUp': 'FLOW ×{n}',

    'pause.title': 'PAUSED',
    'pause.resume': 'Keep running',
    'pause.finish': 'Finish run',
    'pause.options': 'Options',
    'pause.hint': 'Your progress is already saved.',

    'sum.title': 'RUN COMPLETE',
    'sum.first': 'FIRST RUN!',
    'sum.distance': 'Distance',
    'sum.time': 'Time',
    'sum.pace': 'Average pace',
    'sum.avg': 'Average speed',
    'sum.top': 'Top speed',
    'sum.overtakes': 'Overtakes',
    'sum.flow': 'Best FLOW',
    'sum.combo': 'Best combo',
    'sum.perfects': 'PERFECT',
    'sum.challenges': 'Challenges',
    'sum.coins': 'Coins earned',
    'sum.total': 'Your runner has covered {d}',
    'sum.record': 'RECORD',
    'sum.paceUnit': '/km',

    'rec.title': 'RECORDS',
    'rec.profile': 'Profile',
    'rec.totalDistance': 'Total distance',
    'rec.totalTime': 'Time running',
    'rec.runs': 'Runs',
    'rec.overtakes': 'Overtakes',
    'rec.perfects': 'Total PERFECT',
    'rec.challenges': 'Challenges completed',
    'rec.regions': 'Regions',
    'rec.best': 'Personal bests',
    'rec.topSpeed': 'Top speed',
    'rec.maxFlow': 'Best FLOW',
    'rec.maxCombo': 'Best combo',
    'rec.longestRun': 'Longest run',
    'rec.mostOvertakes': 'Most overtakes in one run',

    'opt.title': 'OPTIONS',
    'opt.lang': 'Language',
    'opt.music': 'Music',
    'opt.sfx': 'Sound effects',
    'opt.vibration': 'Vibration',
    'opt.reduceMotion': 'Reduce camera motion',
    'opt.bigUi': 'Larger interface',
    'opt.quality': 'Graphics quality',
    'opt.qualityNote': 'Applies next time you open the game.',
    'q.auto': 'Automatic',
    'q.high': 'High',
    'q.low': 'Light',
    'opt.controls': 'Controls',
    'opt.controlsText': 'Tap: stride. Swipe: move sideways and choose your path. Keyboard: SPACE and arrows. ESC pauses.',
    'opt.reset': 'Erase progress',
    'opt.resetConfirm': 'Erase all progress on this device? This cannot be undone.',
    'opt.version': 'Version {v}',
    'opt.privacy': 'Privacy',

    'region.welcome': 'WELCOME TO',
    'biome.cidade': 'City',
    'sign.choose': 'CHOOSE'
  };
})(window.EP);
