// English (US) texts. Same keys in all three languages.
(function (EP) {
  EP.texts['en-US'] = {
    'lang.name': 'English',
    'app.tagline': 'How far can you run?',
    'boot.loading': 'Warming up…',
    'boot.noWebgl': 'This browser could not open the 3D view. Update your browser or try another one.',
    'boot.noSave': 'Your browser blocked storage: you can run, but progress will not be saved.',

    'create.title': 'CREATE YOUR RUNNER',
    'create.step': 'Step {n} of 4',
    'create.who': 'Who is running?',
    'gender.m': 'Male runner',
    'gender.f': 'Female runner',
    'create.nameTitle': 'What is the name?',
    'create.namePh': 'Runner name',
    'create.nameHint': 'Up to 15 letters. It shows on your profile.',
    'create.looks': 'Look',
    'create.skin': 'Skin tone',
    'create.hairStyle': 'Hair',
    'create.hairColor': 'Hair color',
    'hair.curto': 'Short',
    'hair.cacheado': 'Curly',
    'hair.rabo': 'Ponytail',
    'hair.coque': 'Bun',
    'hair.longo': 'Long',
    'hair.raspado': 'Buzz cut',
    'create.outfit': 'Starting outfit',
    'create.outfitHint': 'T-shirt, shorts and sneakers. Pick the colors.',
    'create.shirt': 'T-shirt',
    'create.shorts': 'Shorts',
    'create.shoes': 'Sneakers',
    'create.rotate': 'Drag to turn',
    'ui.next': 'Next',
    'ui.back': 'Back',
    'ui.start': 'Start running',
    'ui.save': 'Save',
    'ui.continue': 'Continue',
    'ui.close': 'Close',
    'ui.cancel': 'Cancel',
    'ui.confirm': 'Erase',

    'home.run': 'RUN',
    'home.total': 'covered',
    'home.coins': 'Coins',
    'home.runner': 'Runner',
    'home.records': 'Records',
    'home.options': 'Options',
    'home.firstRun': 'Your journey starts now',
    'home.best': 'Longest run: {d}',

    'hud.distance': 'DISTANCE',
    'hud.speed': 'KM/H',
    'hud.energy': 'ENERGY',
    'hud.overtakes': 'OVERTAKES',
    'hud.pause': 'Pause',
    'hud.flow': 'FLOW ×{n}',
    'hud.combo': 'COMBO ×{n}',
    'hud.lowEnergy': 'Low energy: ease off and recover',
    'hud.spam': 'Easy! Rhythm beats force',
    'rating.perfect': 'PERFECT',
    'rating.great': 'GREAT',
    'rating.good': 'GOOD',
    'rating.off': 'OFF BEAT',
    'zone.walk': 'WALK',
    'zone.jog': 'JOG',
    'zone.run': 'RUN',
    'zone.fast': 'FAST RUN',
    'zone.sprint': 'SPRINT',

    'tut.1': 'TAP TO RUN',
    'tut.1b': 'Every tap is a stride',
    'tut.1k': 'Tap the screen, click or press SPACE',
    'tut.2': 'KEEP THE RHYTHM',
    'tut.2b': 'Tap on the same beat, like a song',
    'tut.3': 'PERFECT!',
    'tut.3b': 'Keep it up and get into FLOW',
    'tut.4': 'SWIPE TO CHOOSE YOUR PATH',
    'tut.4b': 'Swipe sideways (or use the arrow keys)',
    'tut.done': 'All set! Now it is up to you',

    'fork.title': 'CHOOSE YOUR PATH',
    'fork.hint': 'Swipe sideways',
    'route.bairro': 'NEIGHBORHOOD',
    'route.parque': 'PARK',
    'route.centro': 'DOWNTOWN',
    'route.entered': 'Route: {name}',
    'route.back': 'Back to the neighborhood',
    'perk.energy10': 'Energy +10%',
    'perk.fewerRunners': 'Fewer runners',
    'perk.coins20': 'Coins +20%',
    'perk.moreRunners': 'More runners',

    'ch.label': 'CHALLENGE',
    'ch.flow.title': 'FLOW',
    'ch.flow.desc': 'Hit {n} PERFECT in a row',
    'ch.pace.title': 'PACE',
    'ch.pace.desc': 'Hold {v} km/h (±1) for {n} s',
    'ch.overtake.title': 'OVERTAKE',
    'ch.overtake.desc': 'Pass {n} runners',
    'ch.combo.title': 'COMBO',
    'ch.combo.desc': 'Reach a ×{n} combo',
    'ch.energy.title': 'STAMINA',
    'ch.energy.desc': 'Run hard for {n} s without dropping below 35% energy',
    'ch.sprint.title': 'SPRINT',
    'ch.sprint.desc': 'Run {n} m as fast as you can',
    'ch.draft.title': 'DRAFT',
    'ch.draft.desc': 'Stay right behind another runner for {n} s',
    'ch.pacer.title': 'PACER',
    'ch.pacer.desc': 'Keep up with the flag runner for {n} m',
    'ch.hint.faster': 'speed up',
    'ch.hint.slower': 'ease off',
    'ch.sprintTime': '{t} s',
    'ch.record': 'New 200 m record: {t} s!',
    'hud.draft': 'DRAFT',
    'ch.done': 'CHALLENGE COMPLETE!',
    'ch.failed': 'So close! Next time',
    'ch.reward': '+{n} coins',

    'toast.km': '{n} km this run!',
    'toast.flowUp': 'FLOW ×{n}',

    'pause.title': 'PAUSED',
    'pause.resume': 'Keep running',
    'pause.finish': 'Finish run',
    'pause.options': 'Options',
    'pause.hint': 'Your progress is already saved.',

    'sum.title': 'RUN COMPLETE',
    'sum.first': 'FIRST RUN!',
    'sum.distance': 'Distance',
    'sum.time': 'Time',
    'sum.pace': 'Average pace',
    'sum.avg': 'Average speed',
    'sum.top': 'Top speed',
    'sum.overtakes': 'Overtakes',
    'sum.flow': 'Best FLOW',
    'sum.combo': 'Best combo',
    'sum.perfects': 'PERFECT',
    'sum.challenges': 'Challenges',
    'sum.coins': 'Coins earned',
    'sum.total': 'Your runner has covered {d}',
    'sum.record': 'RECORD',
    'sum.paceUnit': '/km',

    'rec.title': 'RECORDS',
    'rec.profile': 'Profile',
    'rec.totalDistance': 'Total distance',
    'rec.totalTime': 'Time running',
    'rec.runs': 'Runs',
    'rec.overtakes': 'Overtakes',
    'rec.perfects': 'Total PERFECT',
    'rec.challenges': 'Challenges completed',
    'rec.regions': 'Regions',
    'rec.best': 'Personal bests',
    'rec.topSpeed': 'Top speed',
    'rec.maxFlow': 'Best FLOW',
    'rec.maxCombo': 'Best combo',
    'rec.longestRun': 'Longest run',
    'rec.mostOvertakes': 'Most overtakes in one run',

    'opt.title': 'OPTIONS',
    'opt.lang': 'Language',
    'opt.music': 'Music',
    'opt.sfx': 'Sound effects',
    'opt.vibration': 'Vibration',
    'opt.reduceMotion': 'Reduce camera motion',
    'opt.bigUi': 'Larger interface',
    'opt.quality': 'Graphics quality',
    'opt.qualityNote': 'Applies next time you open the game.',
    'q.auto': 'Automatic',
    'q.high': 'High',
    'q.low': 'Light',
    'opt.controls': 'Controls',
    'opt.controlsText': 'Tap: stride. Swipe: move sideways and choose your path. Keyboard: SPACE and arrows. ESC pauses.',
    'opt.reset': 'Erase progress',
    'opt.resetConfirm': 'Erase all progress on this device? This cannot be undone.',
    'opt.version': 'Version {v}',
    'opt.privacy': 'Privacy',

    'region.welcome': 'WELCOME TO',
    'biome.cidade': 'City',
    'sign.choose': 'CHOOSE',

    // loja, equipar, nível, conquistas, missões e avisos
    'home.shop': 'Shop',
    'home.shopSub': 'Sneakers, clothes & gear',
    'home.equip': 'Gear',
    'home.achievements': 'Awards',
    'home.missions': 'Missions',
    'home.profile': 'Profile and records',
    'lvl.short': 'LV',
    'lvl.level': 'Level {n}',
    'lvl.title.1': 'Rookie',
    'lvl.title.2': 'In Rhythm',
    'lvl.title.3': 'Distance Runner',
    'lvl.title.4': 'Marathoner',
    'lvl.title.5': 'Ultrarunner',
    'lvl.title.6': 'Elite',
    'lvl.title.7': 'Legend',
    'slot.head': 'Head',
    'slot.eyes': 'Eyewear',
    'slot.ears': 'Audio',
    'slot.shirt': 'Top',
    'slot.shorts': 'Bottoms',
    'slot.shoes': 'Shoes',
    'slot.wrist': 'Wrist',
    'rarity.comum': 'Common',
    'rarity.raro': 'Rare',
    'rarity.epico': 'Epic',
    'rarity.lendario': 'Legendary',
    'stat.speed': 'Speed',
    'stat.energy': 'Energy',
    'stat.recovery': 'Recovery',
    'stat.flow': 'FLOW',
    'stat.flowWindow': 'PERFECT window',
    'stat.flowBonus': 'FLOW bonus',
    'stat.efficiency': 'Efficiency',
    'stat.offline': 'Offline training',
    'stat.speed.fx': 'Speed and top speed +{v}%',
    'stat.energy.fx': '+{v} max energy',
    'stat.recovery.fx': 'Recovers energy {v}% faster',
    'stat.flow.fx': 'FLOW builds {v}% faster and drains slower',
    'stat.flowWindow.fx': 'PERFECT and GREAT {v}% easier to hit',
    'stat.flowBonus.fx': '+{v}% coins while in FLOW',
    'stat.efficiency.fx': 'Uses {v}% less energy',
    'stat.offline.fx': 'Trains up to {h} h while the game is closed, {v}% faster',
    'shop.title': 'SHOP',
    'shop.cat.tenis': 'Sneakers',
    'shop.cat.roupas': 'Clothes',
    'shop.cat.bones': 'Caps',
    'shop.cat.oculos': 'Eyewear',
    'shop.cat.fones': 'Audio',
    'shop.cat.relogios': 'Watches',
    'shop.buy': 'Buy',
    'shop.owned': 'Owned',
    'shop.equipped': 'Equipped',
    'shop.equip': 'Equip',
    'shop.equipNow': 'Equip now',
    'shop.keep': 'Keep shopping',
    'shop.needCoins': 'You need {n} more coins. One more run and you\'re there!',
    'shop.needLevel': 'Unlocks at level {n}',
    'shop.levelTag': 'Level {n}',
    'shop.freeAt': 'Free at level {n}',
    'shop.freeAtDesc': 'Level {n} gift: keep running and it\'s yours for free. Buy it sooner and you get the coins back when you get there.',
    'shop.bought': 'Purchased!',
    'shop.compare': 'Compared with what you wear',
    'shop.current': 'Now wearing: {name}',
    'shop.same': 'Same stats',
    'shop.noStats': 'Looks only, no stats.',
    'shop.set': '{name} set',
    'shop.effects': 'What it does in a run',
    'set.tropical': 'Tropical',
    'set.nuvem': 'Cloud',
    'set.montanha': 'Mountain',
    'set.cometa': 'Comet',
    'set.aurora': 'Aurora',
    'set.neon': 'Neon',
    'equip.title': 'GEAR',
    'equip.hint': 'Tap an item to wear it. Drag the runner to turn.',
    'equip.totals': 'Your bonuses',
    'equip.noBonus': 'Basic clothes give no bonus. Shop items make you faster, with more energy and more FLOW.',
    'equip.none': 'None',
    'equip.toShop': 'Shop',
    'item.camiseta-basica': 'Basic Tee',
    'item.short-basico': 'Basic Shorts',
    'item.tenis-basico': 'Basic Sneakers',
    'item.tenis-leve': 'Light Runners',
    'item.tenis-asfalto': 'Asphalt Runners',
    'item.tenis-tropical': 'Tropical Runners',
    'item.tenis-pista': 'Track Runners',
    'item.tenis-nuvem': 'Cloud Runners',
    'item.tenis-brisa': 'Breeze Runners',
    'item.tenis-urbano': 'Urban Runners',
    'item.tenis-trilha': 'Trail Runners',
    'item.tenis-cometa': 'Comet Racers',
    'item.tenis-aurora': 'Aurora Racers',
    'item.tenis-maratona': 'Marathon Racers',
    'item.tenis-relampago': 'Lightning Racers',
    'item.camiseta-sol': 'Sun Tee',
    'item.camiseta-oceano': 'Ocean Tee',
    'item.regata-verao': 'Summer Tank',
    'item.regata-tropical': 'Tropical Tank',
    'item.camiseta-listrada': 'Striped Tee',
    'item.manga-longa-neblina': 'Mist Long Sleeve',
    'item.corta-vento-aurora': 'Aurora Windbreaker',
    'item.camiseta-neon': 'Neon Tee',
    'item.corta-vento-cometa': 'Comet Windbreaker',
    'item.short-classico': 'Classic Shorts',
    'item.short-corrida': 'Running Shorts',
    'item.bermuda-praia': 'Beach Shorts',
    'item.legging-noite': 'Night Leggings',
    'item.saia-short-flor': 'Flower Skort',
    'item.short-pro': 'Pro Shorts',
    'item.legging-aurora': 'Aurora Leggings',
    'item.bone-classico': 'Classic Cap',
    'item.viseira-sol': 'Sun Visor',
    'item.faixa-suor': 'Sweatband',
    'item.bandana-tropical': 'Tropical Bandana',
    'item.gorro-montanha': 'Mountain Beanie',
    'item.bone-aba-reta-neon': 'Neon Snapback',
    'item.viseira-pro': 'Pro Visor',
    'item.bone-aurora': 'Aurora Cap',
    'item.oculos-classico': 'Classic Glasses',
    'item.oculos-sol-classico': 'Classic Sunglasses',
    'item.oculos-esporte-azul': 'Blue Sport Shades',
    'item.oculos-sol-praia': 'Beach Sunglasses',
    'item.oculos-esporte-cometa': 'Comet Sport Shades',
    'item.oculos-aurora': 'Aurora Shades',
    'item.fone-sem-fio-branco': 'White Earbuds',
    'item.fone-classico': 'Classic Headphones',
    'item.fone-esporte-azul': 'Blue Sport Earphones',
    'item.fone-neon': 'Neon Headphones',
    'item.fone-estudio': 'Studio Headphones',
    'item.fone-aurora': 'Aurora Headphones',
    'item.pulseira-amizade': 'Friendship Bracelet',
    'item.relogio-simples': 'Simple Watch',
    'item.relogio-digital': 'Digital Watch',
    'item.pulseira-esporte': 'Sport Band',
    'item.smartwatch-azul': 'Blue Smartwatch',
    'item.relogio-explorador': 'Explorer Watch',
    'item.smartwatch-aurora': 'Aurora Smartwatch',
    'ach.title': 'ACHIEVEMENTS',
    'ach.new': 'New',
    'ach.unlockedOn': 'Unlocked on {d}',
    'ach.best': 'Best: {v}',
    'ach.goal': 'Goal: {v}',
    'ach.goalRef': 'Run a total of {d}',
    'ach.doneRef': 'You\'ve run {d}!',
    'achcat.distancia': 'Journey',
    'achcat.corrida': 'Running',
    'achcat.ritmo': 'Rhythm',
    'achcat.desafio': 'Challenges',
    'achcat.colecao': 'Collection',
    'achcat.exploracao': 'Exploration',
    'ach.primeiro-km.t': 'First Kilometer',
    'ach.primeiro-km.d': 'your first kilometer ({km})',
    'ach.5km.t': '5 km',
    'ach.5km.d': '{km}, a classic road race distance',
    'ach.10km.t': '10 km',
    'ach.10km.d': '{km}, one of the most popular road races',
    'ach.ponte-rio-niteroi.t': 'Rio–Niterói Bridge',
    'ach.ponte-rio-niteroi.d': 'the length of the Rio–Niterói Bridge ({km})',
    'ach.meia-maratona.t': 'Half Marathon',
    'ach.meia-maratona.d': 'a full half marathon ({km})',
    'ach.maratona.t': 'Marathon',
    'ach.maratona.d': 'a full marathon ({km})',
    'ach.ultra-100.t': 'Ultramarathon',
    'ach.ultra-100.d': '{km}, a classic ultramarathon distance',
    'ach.sp-rio.t': 'São Paulo to Rio',
    'ach.sp-rio.d': 'the trip from São Paulo to Rio de Janeiro ({km})',
    'ach.1000km.t': 'A Thousand Kilometers',
    'ach.1000km.d': 'a thousand kilometers ({km})',
    'ach.oiapoque-chui.t': 'Oiapoque to Chuí',
    'ach.oiapoque-chui.d': 'the trip from Oiapoque to Chuí, Brazil\'s northern and southern tips ({km})',
    'ach.rio-amazonas.t': 'Amazon River',
    'ach.rio-amazonas.d': 'the length of the Amazon River ({km})',
    'ach.litoral-brasil.t': 'Brazil\'s Coastline',
    'ach.litoral-brasil.d': 'Brazil\'s entire coastline ({km})',
    'ach.transiberiana.t': 'Trans-Siberian',
    'ach.transiberiana.d': 'the Trans-Siberian Railway, Moscow to Vladivostok ({km})',
    'ach.muralha-china.t': 'Great Wall of China',
    'ach.muralha-china.d': 'the Great Wall of China with all its sections ({km})',
    'ach.volta-ao-mundo.t': 'Around the World',
    'ach.volta-ao-mundo.d': 'a lap around the world along the Equator ({km})',
    'ach.ate-a-lua.t': 'To the Moon',
    'ach.ate-a-lua.d': 'the distance from the Earth to the Moon ({km})',
    'ach.primeira-corrida.t': 'Starting Line',
    'ach.primeira-corrida.d': 'Finish your first run',
    'ach.10-corridas.t': 'Habit',
    'ach.10-corridas.d': 'Finish 10 runs',
    'ach.100-corridas.t': 'Veteran',
    'ach.100-corridas.d': 'Finish 100 runs',
    'ach.corrida-5km.t': '5 km in One Go',
    'ach.corrida-5km.d': 'Run 5 km in a single run',
    'ach.corrida-10km.t': '10 km in One Go',
    'ach.corrida-10km.d': 'Run 10 km in a single run',
    'ach.veloz-18.t': 'Quick',
    'ach.veloz-18.d': 'Reach 18 km/h',
    'ach.veloz-22.t': 'Rocket',
    'ach.veloz-22.d': 'Reach 22 km/h',
    'ach.ultrapassa-1.t': 'Excuse Me!',
    'ach.ultrapassa-1.d': 'Overtake your first runner',
    'ach.ultrapassa-100.t': 'Leaving the Pack',
    'ach.ultrapassa-100.d': 'Overtake 100 runners',
    'ach.ultrapassa-1000.t': 'Hurricane',
    'ach.ultrapassa-1000.d': 'Overtake 1,000 runners',
    'ach.ultrapassa-10000.t': 'Street Legend',
    'ach.ultrapassa-10000.d': 'Overtake 10,000 runners',
    'ach.dias-3.t': 'I\'m Back!',
    'ach.dias-3.d': 'Play on 3 different days',
    'ach.dias-7.t': 'One Week',
    'ach.dias-7.d': 'Play on 7 different days',
    'ach.dias-30.t': 'Athlete\'s Routine',
    'ach.dias-30.d': 'Play on 30 different days',
    'ach.perfect-100.t': 'On the Beat',
    'ach.perfect-100.d': 'Hit 100 PERFECTs',
    'ach.perfect-1000.t': 'Metronome',
    'ach.perfect-1000.d': 'Hit 1,000 PERFECTs',
    'ach.perfect-10000.t': 'Perfect Rhythm',
    'ach.perfect-10000.d': 'Hit 10,000 PERFECTs',
    'ach.flow-4.t': 'Flowing',
    'ach.flow-4.d': 'Reach FLOW ×4',
    'ach.flow-8.t': 'On Fire',
    'ach.flow-8.d': 'Reach FLOW ×8',
    'ach.flow-12.t': 'Flow State',
    'ach.flow-12.d': 'Reach FLOW ×12',
    'ach.combo-5.t': 'Combo',
    'ach.combo-5.d': 'Reach an overtake combo ×5',
    'ach.combo-10.t': 'Insane Combo',
    'ach.combo-10.d': 'Reach an overtake combo ×10',
    'ach.desafio-1.t': 'Challenger',
    'ach.desafio-1.d': 'Complete a challenge',
    'ach.desafio-10.t': 'Challenge Hunter',
    'ach.desafio-10.d': 'Complete 10 challenges',
    'ach.desafio-50.t': 'Challenge Master',
    'ach.desafio-50.d': 'Complete 50 challenges',
    'ach.sprint-40.t': 'Burst',
    'ach.sprint-40.d': 'Run the 200 m SPRINT in 40 s or less',
    'ach.sprint-32.t': 'Lightning',
    'ach.sprint-32.d': 'Run the 200 m SPRINT in 32 s or less',
    'ach.pacer-1.t': 'Pacer Buddy',
    'ach.pacer-1.d': 'Keep up with a pacer to the end',
    'ach.pacer-10.t': 'Race Pace',
    'ach.pacer-10.d': 'Keep up with 10 pacers to the end',
    'ach.vacuo-300.t': 'Aerodynamic',
    'ach.vacuo-300.d': 'Spend 5 minutes drafting behind other runners',
    'ach.primeiro-item.t': 'First Purchase',
    'ach.primeiro-item.d': 'Buy an item in the shop',
    'ach.10-itens.t': 'Collector',
    'ach.10-itens.d': 'Own 10 items',
    'ach.lendario.t': 'Legendary',
    'ach.lendario.d': 'Own a legendary item',
    'ach.nivel-5.t': 'Level 5',
    'ach.nivel-5.d': 'Reach level 5',
    'ach.nivel-10.t': 'Level 10',
    'ach.nivel-10.d': 'Reach level 10',
    'ach.nivel-25.t': 'Level 25',
    'ach.nivel-25.d': 'Reach level 25',
    'ach.regiao-2.t': 'Explorer',
    'ach.regiao-2.d': 'Unlock 2 regions',
    'ach.regiao-4.t': 'Traveler',
    'ach.regiao-4.d': 'Unlock 4 regions',
    'ach.regiao-8.t': 'World Tour',
    'ach.regiao-8.d': 'Unlock 8 regions',
    'ach.offline-10.t': 'Invisible Training',
    'ach.offline-10.d': 'Log 10 km of training while the game is closed',
    'mis.title': 'DAILY MISSIONS',
    'mis.reset': 'New missions in {t}',
    'mis.claim': 'Claim',
    'mis.claimed': 'Claimed',
    'mis.bonus': 'Daily bonus',
    'mis.bonusDesc': 'Claim all three of today\'s missions',
    'mis.dist': 'Run {n}',
    'mis.flow': 'Stay in FLOW for {n}',
    'mis.perfect': 'Hit {n} PERFECTs',
    'mis.overtake': 'Overtake {n} runners',
    'mis.combo': 'Reach an overtake combo ×{n}',
    'mis.challenge': 'Complete {n} challenges',
    'mis.challenge.1': 'Complete 1 challenge',
    'mis.speed': 'Reach {n}',
    'mis.draft': 'Draft behind other runners for {n}',
    'mis.pacer': 'Keep up with {n} pacers to the end',
    'mis.pacer.1': 'Keep up with a pacer to the end',
    'mis.runs': 'Finish {n} runs',
    'mis.runs.1': 'Finish a run',
    'pop.ok': 'OK',
    'pop.later': 'Later',
    'pop.equip': 'Equip now',
    'pop.offline.t': 'WHILE YOU WERE AWAY',
    'pop.offline.d': 'Your runner trained for {h} and ran {d}.',
    'pop.offline.cap': 'Offline training lasts up to {h} h. Watches raise this limit.',
    'pop.level.t': 'LEVEL {n}!',
    'pop.level.d': 'Your title: {title}',
    'pop.level.refund': 'You already had {item}, so the gift became coins.',
    'pop.ach.t': 'ACHIEVEMENT!',
    'pop.region.t': 'NEW REGION',
    'pop.region.d': '{name} is now open to run.',
    'pop.gift.t': 'WELCOME GIFT',
    'pop.gift.d': 'You got {n} coins to try out the shop. How about new sneakers?',
    'pop.gift.go': 'Go to the shop',
    'toast.ach': 'Achievement',
    'toast.mission': 'Mission complete',
    'toast.level': 'Level up',
    'sum.levelUp': 'Up to level {n}!',
    'sum.achievements': 'Achievements this run',
    'sum.missions': 'Missions completed',
    'sum.missionsHint': 'Claim the rewards on the missions screen.'
  };
})(window.EP);
