// Textos en español. Las claves son las mismas en los tres idiomas.
(function (EP) {
  EP.texts['es'] = {
    'lang.name': 'Español',
    'app.tagline': '¿Hasta dónde puedes correr?',
    'boot.loading': 'Calentando…',
    'boot.noWebgl': 'Este navegador no pudo abrir el 3D. Actualiza el navegador o prueba otro.',
    'boot.noSave': 'El navegador bloqueó el almacenamiento: puedes correr, pero el progreso no se guardará.',

    'create.title': 'CREA TU CORREDOR',
    'create.step': 'Paso {n} de 4',
    'create.who': '¿Quién va a correr?',
    'gender.m': 'Corredor',
    'gender.f': 'Corredora',
    'create.nameTitle': '¿Cómo se llama?',
    'create.namePh': 'Nombre del corredor',
    'create.nameHint': 'Hasta 15 letras. Aparece en tu perfil.',
    'create.looks': 'Apariencia',
    'create.skin': 'Tono de piel',
    'create.hairStyle': 'Pelo',
    'create.hairColor': 'Color del pelo',
    'hair.curto': 'Corto',
    'hair.cacheado': 'Rizado',
    'hair.rabo': 'Coleta',
    'hair.coque': 'Moño',
    'hair.longo': 'Largo',
    'hair.raspado': 'Rapado',
    'create.outfit': 'Ropa inicial',
    'create.outfitHint': 'Camiseta, pantalón corto y zapatillas. Elige los colores.',
    'create.shirt': 'Camiseta',
    'create.shorts': 'Pantalón corto',
    'create.shoes': 'Zapatillas',
    'create.rotate': 'Arrastra para girar',
    'ui.next': 'Siguiente',
    'ui.back': 'Volver',
    'ui.start': 'Empezar a correr',
    'ui.save': 'Guardar',
    'ui.continue': 'Continuar',
    'ui.close': 'Cerrar',
    'ui.cancel': 'Cancelar',
    'ui.confirm': 'Borrar',

    'home.run': 'CORRER',
    'home.total': 'recorridos',
    'home.coins': 'Monedas',
    'home.runner': 'Corredor',
    'home.records': 'Récords',
    'home.options': 'Opciones',
    'home.firstRun': 'Tu viaje empieza ahora',
    'home.best': 'Carrera más larga: {d}',

    'hud.distance': 'DISTANCIA',
    'hud.speed': 'KM/H',
    'hud.energy': 'ENERGÍA',
    'hud.overtakes': 'ADELANTAMIENTOS',
    'hud.pause': 'Pausa',
    'hud.flow': 'FLOW ×{n}',
    'hud.combo': 'COMBO ×{n}',
    'hud.lowEnergy': 'Energía baja: baja el ritmo y recupera',
    'hud.spam': '¡Calma! El ritmo vale más que la fuerza',
    'rating.perfect': 'PERFECT',
    'rating.great': 'GREAT',
    'rating.good': 'GOOD',
    'rating.off': 'FUERA DE RITMO',
    'zone.walk': 'CAMINATA',
    'zone.jog': 'TROTE',
    'zone.run': 'CARRERA',
    'zone.fast': 'CARRERA FUERTE',
    'zone.sprint': 'SPRINT',

    'tut.1': 'TOCA PARA CORRER',
    'tut.1b': 'Cada toque es una zancada',
    'tut.1k': 'Toca la pantalla, haz clic o pulsa ESPACIO',
    'tut.2': 'MANTÉN EL RITMO',
    'tut.2b': 'Toca siempre al mismo compás, como una canción',
    'tut.3': '¡PERFECT!',
    'tut.3b': 'Sigue así y entra en FLOW',
    'tut.4': 'DESLIZA PARA ELEGIR TU CAMINO',
    'tut.4b': 'Desliza el dedo hacia un lado (o usa las flechas)',
    'tut.done': '¡Listo! Ahora te toca a ti',

    'fork.title': 'ELIGE TU CAMINO',
    'fork.hint': 'Desliza hacia un lado',
    'route.bairro': 'BARRIO',
    'route.parque': 'PARQUE',
    'route.centro': 'CENTRO',
    'route.entered': 'Ruta: {name}',
    'route.back': 'De vuelta al barrio',
    'perk.energy10': 'Energía +10%',
    'perk.fewerRunners': 'Menos corredores',
    'perk.coins20': 'Monedas +20%',
    'perk.moreRunners': 'Más corredores',

    'ch.label': 'DESAFÍO',
    'ch.flow.title': 'FLOW',
    'ch.flow.desc': 'Haz {n} PERFECT seguidos',
    'ch.done': '¡DESAFÍO COMPLETADO!',
    'ch.failed': '¡Casi! Será en el próximo',
    'ch.reward': '+{n} monedas',

    'toast.km': '¡{n} km en esta carrera!',
    'toast.flowUp': 'FLOW ×{n}',

    'pause.title': 'PAUSA',
    'pause.resume': 'Seguir corriendo',
    'pause.finish': 'Terminar carrera',
    'pause.options': 'Opciones',
    'pause.hint': 'Tu progreso ya está guardado.',

    'sum.title': 'CARRERA TERMINADA',
    'sum.first': '¡PRIMERA CARRERA!',
    'sum.distance': 'Distancia',
    'sum.time': 'Tiempo',
    'sum.pace': 'Ritmo medio',
    'sum.avg': 'Velocidad media',
    'sum.top': 'Velocidad máxima',
    'sum.overtakes': 'Adelantamientos',
    'sum.flow': 'Mejor FLOW',
    'sum.combo': 'Mejor combo',
    'sum.perfects': 'PERFECT',
    'sum.challenges': 'Desafíos',
    'sum.coins': 'Monedas ganadas',
    'sum.total': 'Tu corredor ya recorrió {d}',
    'sum.record': 'RÉCORD',
    'sum.paceUnit': '/km',

    'rec.title': 'RÉCORDS',
    'rec.profile': 'Perfil',
    'rec.totalDistance': 'Distancia total',
    'rec.totalTime': 'Tiempo corriendo',
    'rec.runs': 'Carreras',
    'rec.overtakes': 'Adelantamientos',
    'rec.perfects': 'Total de PERFECT',
    'rec.challenges': 'Desafíos completados',
    'rec.regions': 'Regiones',
    'rec.best': 'Mejores marcas',
    'rec.topSpeed': 'Velocidad máxima',
    'rec.maxFlow': 'Mejor FLOW',
    'rec.maxCombo': 'Mejor combo',
    'rec.longestRun': 'Carrera más larga',
    'rec.mostOvertakes': 'Más adelantamientos en una carrera',

    'opt.title': 'OPCIONES',
    'opt.lang': 'Idioma',
    'opt.music': 'Música',
    'opt.sfx': 'Efectos de sonido',
    'opt.vibration': 'Vibración',
    'opt.reduceMotion': 'Reducir movimiento de la cámara',
    'opt.bigUi': 'Interfaz más grande',
    'opt.quality': 'Calidad gráfica',
    'opt.qualityNote': 'Se aplica al abrir el juego de nuevo.',
    'q.auto': 'Automática',
    'q.high': 'Alta',
    'q.low': 'Ligera',
    'opt.controls': 'Controles',
    'opt.controlsText': 'Toque: zancada. Deslizar: cambia de lado y elige el camino. Teclado: ESPACIO y flechas. ESC pausa.',
    'opt.reset': 'Borrar progreso',
    'opt.resetConfirm': '¿Borrar todo el progreso de este dispositivo? No se puede deshacer.',
    'opt.version': 'Versión {v}',
    'opt.privacy': 'Privacidad',

    'region.welcome': 'BIENVENIDO A',
    'biome.cidade': 'Ciudad',
    'sign.choose': 'ELIGE'
  };
})(window.EP);
