// Textos en español. Las claves son las mismas en los tres idiomas.
(function (EP) {
  EP.texts['es'] = {
    'lang.name': 'Español',
    'app.tagline': '¿Hasta dónde puedes correr?',
    'boot.loading': 'Calentando…',
    'boot.noWebgl': 'Este navegador no pudo abrir el 3D. Actualiza el navegador o prueba otro.',
    'boot.noSave': 'El navegador bloqueó el almacenamiento: puedes correr, pero el progreso no se guardará.',

    'create.title': 'CREA TU CORREDOR',
    'create.step': 'Paso {n} de 4',
    'create.who': '¿Quién va a correr?',
    'gender.m': 'Corredor',
    'gender.f': 'Corredora',
    'create.nameTitle': '¿Cómo se llama?',
    'create.namePh': 'Nombre del corredor',
    'create.nameHint': 'Hasta 15 letras. Aparece en tu perfil.',
    'create.looks': 'Apariencia',
    'create.skin': 'Tono de piel',
    'create.hairStyle': 'Pelo',
    'create.hairColor': 'Color del pelo',
    'hair.curto': 'Corto',
    'hair.cacheado': 'Rizado',
    'hair.rabo': 'Coleta',
    'hair.coque': 'Moño',
    'hair.longo': 'Largo',
    'hair.raspado': 'Rapado',
    'create.outfit': 'Ropa inicial',
    'create.outfitHint': 'Camiseta, pantalón corto y zapatillas. Elige los colores.',
    'create.shirt': 'Camiseta',
    'create.shorts': 'Pantalón corto',
    'create.shoes': 'Zapatillas',
    'create.rotate': 'Arrastra para girar',
    'ui.next': 'Siguiente',
    'ui.back': 'Volver',
    'ui.start': 'Empezar a correr',
    'ui.save': 'Guardar',
    'ui.continue': 'Continuar',
    'ui.close': 'Cerrar',
    'ui.cancel': 'Cancelar',
    'ui.confirm': 'Borrar',

    'home.run': 'CORRER',
    'home.total': 'recorridos',
    'home.coins': 'Monedas',
    'home.runner': 'Corredor',
    'home.records': 'Récords',
    'home.options': 'Opciones',
    'home.firstRun': 'Tu viaje empieza ahora',
    'home.best': 'Carrera más larga: {d}',

    'hud.distance': 'DISTANCIA',
    'hud.speed': 'KM/H',
    'hud.energy': 'ENERGÍA',
    'hud.overtakes': 'ADELANTAMIENTOS',
    'hud.pause': 'Pausa',
    'hud.flow': 'FLOW ×{n}',
    'hud.combo': 'COMBO ×{n}',
    'hud.lowEnergy': 'Energía baja: baja el ritmo y recupera',
    'hud.spam': '¡Calma! El ritmo vale más que la fuerza',
    'rating.perfect': 'PERFECT',
    'rating.great': 'GREAT',
    'rating.good': 'GOOD',
    'rating.off': 'FUERA DE RITMO',
    'zone.walk': 'CAMINATA',
    'zone.jog': 'TROTE',
    'zone.run': 'CARRERA',
    'zone.fast': 'CARRERA FUERTE',
    'zone.sprint': 'SPRINT',

    'tut.1': 'TOCA PARA CORRER',
    'tut.1b': 'Cada toque es una zancada',
    'tut.1k': 'Toca la pantalla, haz clic o pulsa ESPACIO',
    'tut.2': 'MANTÉN EL RITMO',
    'tut.2b': 'Toca siempre al mismo compás, como una canción',
    'tut.3': '¡PERFECT!',
    'tut.3b': 'Sigue así y entra en FLOW',
    'tut.4': 'DESLIZA PARA ELEGIR TU CAMINO',
    'tut.4b': 'Desliza el dedo hacia un lado (o usa las flechas)',
    'tut.done': '¡Listo! Ahora te toca a ti',

    'fork.title': 'ELIGE TU CAMINO',
    'fork.hint': 'Desliza hacia un lado',
    'route.bairro': 'BARRIO',
    'route.parque': 'PARQUE',
    'route.centro': 'CENTRO',
    'route.entered': 'Ruta: {name}',
    'route.back': 'De vuelta al barrio',
    'perk.energy10': 'Energía +10%',
    'perk.fewerRunners': 'Menos corredores',
    'perk.coins20': 'Monedas +20%',
    'perk.moreRunners': 'Más corredores',

    'ch.label': 'DESAFÍO',
    'ch.flow.title': 'FLOW',
    'ch.flow.desc': 'Haz {n} PERFECT seguidos',
    'ch.pace.title': 'RITMO',
    'ch.pace.desc': 'Mantén {v} km/h (±1) durante {n} s',
    'ch.overtake.title': 'ADELANTA',
    'ch.overtake.desc': 'Adelanta a {n} corredores',
    'ch.combo.title': 'COMBO',
    'ch.combo.desc': 'Llega al combo ×{n}',
    'ch.energy.title': 'AGUANTE',
    'ch.energy.desc': 'Corre fuerte {n} s sin bajar del 35% de energía',
    'ch.sprint.title': 'SPRINT',
    'ch.sprint.desc': 'Corre {n} m lo más rápido que puedas',
    'ch.draft.title': 'REBUFO',
    'ch.draft.desc': 'Quédate justo detrás de otro corredor {n} s',
    'ch.pacer.title': 'LIEBRE',
    'ch.pacer.desc': 'Sigue al corredor de la bandera durante {n} m',
    'ch.hint.faster': 'acelera',
    'ch.hint.slower': 'frena',
    'ch.sprintTime': '{t} s',
    'ch.record': '¡Nuevo récord en 200 m: {t} s!',
    'hud.draft': 'REBUFO',
    'ch.done': '¡DESAFÍO COMPLETADO!',
    'ch.failed': '¡Casi! Será en el próximo',
    'ch.reward': '+{n} monedas',

    'toast.km': '¡{n} km en esta carrera!',
    'toast.flowUp': 'FLOW ×{n}',

    'pause.title': 'PAUSA',
    'pause.resume': 'Seguir corriendo',
    'pause.finish': 'Terminar carrera',
    'pause.options': 'Opciones',
    'pause.hint': 'Tu progreso ya está guardado.',

    'sum.title': 'CARRERA TERMINADA',
    'sum.first': '¡PRIMERA CARRERA!',
    'sum.distance': 'Distancia',
    'sum.time': 'Tiempo',
    'sum.pace': 'Ritmo medio',
    'sum.avg': 'Velocidad media',
    'sum.top': 'Velocidad máxima',
    'sum.overtakes': 'Adelantamientos',
    'sum.flow': 'Mejor FLOW',
    'sum.combo': 'Mejor combo',
    'sum.perfects': 'PERFECT',
    'sum.challenges': 'Desafíos',
    'sum.coins': 'Monedas ganadas',
    'sum.total': 'Tu corredor ya recorrió {d}',
    'sum.record': 'RÉCORD',
    'sum.paceUnit': '/km',

    'rec.title': 'RÉCORDS',
    'rec.profile': 'Perfil',
    'rec.totalDistance': 'Distancia total',
    'rec.totalTime': 'Tiempo corriendo',
    'rec.runs': 'Carreras',
    'rec.overtakes': 'Adelantamientos',
    'rec.perfects': 'Total de PERFECT',
    'rec.challenges': 'Desafíos completados',
    'rec.regions': 'Regiones',
    'rec.best': 'Mejores marcas',
    'rec.topSpeed': 'Velocidad máxima',
    'rec.maxFlow': 'Mejor FLOW',
    'rec.maxCombo': 'Mejor combo',
    'rec.longestRun': 'Carrera más larga',
    'rec.mostOvertakes': 'Más adelantamientos en una carrera',

    'opt.title': 'OPCIONES',
    'opt.lang': 'Idioma',
    'opt.music': 'Música',
    'opt.sfx': 'Efectos de sonido',
    'opt.vibration': 'Vibración',
    'opt.reduceMotion': 'Reducir movimiento de la cámara',
    'opt.bigUi': 'Interfaz más grande',
    'opt.quality': 'Calidad gráfica',
    'opt.qualityNote': 'Se aplica al abrir el juego de nuevo.',
    'q.auto': 'Automática',
    'q.high': 'Alta',
    'q.low': 'Ligera',
    'opt.controls': 'Controles',
    'opt.controlsText': 'Toque: zancada. Deslizar: cambia de lado y elige el camino. Teclado: ESPACIO y flechas. ESC pausa.',
    'opt.reset': 'Borrar progreso',
    'opt.resetConfirm': '¿Borrar todo el progreso de este dispositivo? No se puede deshacer.',
    'opt.version': 'Versión {v}',
    'opt.privacy': 'Privacidad',

    'region.welcome': 'BIENVENIDO A',
    'biome.cidade': 'Ciudad',
    'sign.choose': 'ELIGE',

    // loja, equipar, nível, conquistas, missões e avisos
    'home.shop': 'Tienda',
    'home.shopSub': 'Zapatillas, ropa y accesorios',
    'home.equip': 'Equipar',
    'home.achievements': 'Logros',
    'home.missions': 'Misiones',
    'home.profile': 'Perfil y récords',
    'lvl.short': 'NIV',
    'lvl.level': 'Nivel {n}',
    'lvl.title.1': 'Principiante',
    'lvl.title.2': 'Con ritmo',
    'lvl.title.3': 'Fondista',
    'lvl.title.4': 'Maratonista',
    'lvl.title.5': 'Ultramaratonista',
    'lvl.title.6': 'Élite',
    'lvl.title.7': 'Leyenda',
    'slot.head': 'Cabeza',
    'slot.eyes': 'Gafas',
    'slot.ears': 'Auriculares',
    'slot.shirt': 'Camiseta',
    'slot.shorts': 'Pantalón',
    'slot.shoes': 'Zapatillas',
    'slot.wrist': 'Muñeca',
    'rarity.comum': 'Común',
    'rarity.raro': 'Raro',
    'rarity.epico': 'Épico',
    'rarity.lendario': 'Legendario',
    'stat.speed': 'Velocidad',
    'stat.energy': 'Energía',
    'stat.recovery': 'Recuperación',
    'stat.flow': 'FLOW',
    'stat.flowWindow': 'Ventana de PERFECT',
    'stat.flowBonus': 'Bono de FLOW',
    'stat.efficiency': 'Eficiencia',
    'stat.offline': 'Entrenamiento offline',
    'stat.speed.fx': 'Velocidad y velocidad máxima +{v}%',
    'stat.energy.fx': '+{v} de energía máxima',
    'stat.recovery.fx': 'Recupera energía un {v}% más rápido',
    'stat.flow.fx': 'El FLOW sube un {v}% más rápido y baja más despacio',
    'stat.flowWindow.fx': 'PERFECT y GREAT un {v}% más fáciles de lograr',
    'stat.flowBonus.fx': '+{v}% de monedas mientras estés en FLOW',
    'stat.efficiency.fx': 'Gasta un {v}% menos de energía',
    'stat.offline.fx': 'Entrena hasta {h} h con el juego cerrado, un {v}% más rápido',
    'shop.title': 'TIENDA',
    'shop.cat.tenis': 'Zapatillas',
    'shop.cat.roupas': 'Ropa',
    'shop.cat.bones': 'Gorras',
    'shop.cat.oculos': 'Gafas',
    'shop.cat.fones': 'Auriculares',
    'shop.cat.relogios': 'Relojes',
    'shop.buy': 'Comprar',
    'shop.owned': 'En tu mochila',
    'shop.equipped': 'Equipado',
    'shop.equip': 'Equipar',
    'shop.equipNow': 'Equipar ahora',
    'shop.keep': 'Seguir en la tienda',
    'shop.needCoins': 'Te faltan {n} monedas. ¡Una carrera más y lo consigues!',
    'shop.needLevel': 'Se desbloquea en el nivel {n}',
    'shop.levelTag': 'Nivel {n}',
    'shop.freeAt': 'Gratis en el nivel {n}',
    'shop.freeAtDesc': 'Regalo del nivel {n}: sigue corriendo y será tuyo gratis. Si lo compras antes, recuperas las monedas al llegar.',
    'shop.bought': '¡Comprado!',
    'shop.compare': 'Comparado con lo que llevas',
    'shop.current': 'Ahora llevas: {name}',
    'shop.same': 'Mismos atributos',
    'shop.noStats': 'Solo estético, sin atributos.',
    'shop.set': 'Conjunto {name}',
    'shop.effects': 'Qué cambia en la carrera',
    'set.tropical': 'Tropical',
    'set.nuvem': 'Nube',
    'set.montanha': 'Montaña',
    'set.cometa': 'Cometa',
    'set.aurora': 'Aurora',
    'set.neon': 'Neón',
    'equip.title': 'EQUIPAR',
    'equip.hint': 'Toca un artículo para ponértelo. Arrastra al corredor para girarlo.',
    'equip.totals': 'Tus bonificaciones',
    'equip.noBonus': 'La ropa básica no da bonificaciones. Los artículos de la tienda te hacen más rápido, con más energía y más FLOW.',
    'equip.none': 'Ninguno',
    'equip.toShop': 'Tienda',
    'item.camiseta-basica': 'Camiseta básica',
    'item.short-basico': 'Short básico',
    'item.tenis-basico': 'Zapatillas básicas',
    'item.tenis-leve': 'Zapatillas Ligeras',
    'item.tenis-asfalto': 'Zapatillas Asfalto',
    'item.tenis-tropical': 'Zapatillas Tropicales',
    'item.tenis-pista': 'Zapatillas de Pista',
    'item.tenis-nuvem': 'Zapatillas Nube',
    'item.tenis-brisa': 'Zapatillas Brisa',
    'item.tenis-urbano': 'Zapatillas Urbanas',
    'item.tenis-trilha': 'Zapatillas de Trail',
    'item.tenis-cometa': 'Zapatillas Cometa',
    'item.tenis-aurora': 'Zapatillas Aurora',
    'item.tenis-maratona': 'Zapatillas Maratón',
    'item.tenis-relampago': 'Zapatillas Relámpago',
    'item.camiseta-sol': 'Camiseta Sol',
    'item.camiseta-oceano': 'Camiseta Océano',
    'item.regata-verao': 'Sin Mangas Verano',
    'item.regata-tropical': 'Sin Mangas Tropical',
    'item.camiseta-listrada': 'Camiseta a Rayas',
    'item.manga-longa-neblina': 'Manga Larga Neblina',
    'item.corta-vento-aurora': 'Cortavientos Aurora',
    'item.camiseta-neon': 'Camiseta Neón',
    'item.corta-vento-cometa': 'Cortavientos Cometa',
    'item.short-classico': 'Short Clásico',
    'item.short-corrida': 'Short de Running',
    'item.bermuda-praia': 'Bermuda Playa',
    'item.legging-noite': 'Mallas Noche',
    'item.saia-short-flor': 'Falda Short Flor',
    'item.short-pro': 'Short Pro',
    'item.legging-aurora': 'Mallas Aurora',
    'item.bone-classico': 'Gorra Clásica',
    'item.viseira-sol': 'Visera Sol',
    'item.faixa-suor': 'Cinta Antisudor',
    'item.bandana-tropical': 'Bandana Tropical',
    'item.gorro-montanha': 'Gorro Montaña',
    'item.bone-aba-reta-neon': 'Gorra Plana Neón',
    'item.viseira-pro': 'Visera Pro',
    'item.bone-aurora': 'Gorra Aurora',
    'item.oculos-classico': 'Gafas Clásicas',
    'item.oculos-sol-classico': 'Gafas de Sol Clásicas',
    'item.oculos-esporte-azul': 'Gafas Deportivas Azules',
    'item.oculos-sol-praia': 'Gafas de Sol Playa',
    'item.oculos-esporte-cometa': 'Gafas Deportivas Cometa',
    'item.oculos-aurora': 'Gafas Aurora',
    'item.fone-sem-fio-branco': 'Auriculares Inalámbricos Blancos',
    'item.fone-classico': 'Auriculares Clásicos',
    'item.fone-esporte-azul': 'Auriculares Deportivos Azules',
    'item.fone-neon': 'Auriculares Neón',
    'item.fone-estudio': 'Auriculares de Estudio',
    'item.fone-aurora': 'Auriculares Aurora',
    'item.pulseira-amizade': 'Pulsera de la Amistad',
    'item.relogio-simples': 'Reloj Sencillo',
    'item.relogio-digital': 'Reloj Digital',
    'item.pulseira-esporte': 'Pulsera Deportiva',
    'item.smartwatch-azul': 'Smartwatch Azul',
    'item.relogio-explorador': 'Reloj Explorador',
    'item.smartwatch-aurora': 'Smartwatch Aurora',
    'ach.title': 'LOGROS',
    'ach.new': 'Nuevo',
    'ach.unlockedOn': 'Conseguido el {d}',
    'ach.best': 'Mejor: {v}',
    'ach.goal': 'Meta: {v}',
    'ach.goalRef': 'Corre en total {d}',
    'ach.doneRef': '¡Corriste {d}!',
    'achcat.distancia': 'Trayecto',
    'achcat.corrida': 'Carrera',
    'achcat.ritmo': 'Ritmo',
    'achcat.desafio': 'Desafíos',
    'achcat.colecao': 'Colección',
    'achcat.exploracao': 'Exploración',
    'ach.primeiro-km.t': 'Primer kilómetro',
    'ach.primeiro-km.d': 'tu primer kilómetro ({km})',
    'ach.5km.t': '5 km',
    'ach.5km.d': '{km}, la distancia de una clásica carrera de calle',
    'ach.10km.t': '10 km',
    'ach.10km.d': '{km}, una de las carreras de calle más populares',
    'ach.ponte-rio-niteroi.t': 'Puente Río–Niterói',
    'ach.ponte-rio-niteroi.d': 'el equivalente al Puente Río–Niterói ({km})',
    'ach.meia-maratona.t': 'Media maratón',
    'ach.meia-maratona.d': 'una media maratón completa ({km})',
    'ach.maratona.t': 'Maratón',
    'ach.maratona.d': 'una maratón completa ({km})',
    'ach.ultra-100.t': 'Ultramaratón',
    'ach.ultra-100.d': '{km}, la distancia de una ultramaratón clásica',
    'ach.sp-rio.t': 'São Paulo–Río',
    'ach.sp-rio.d': 'el equivalente al viaje de São Paulo a Río de Janeiro ({km})',
    'ach.1000km.t': 'Mil kilómetros',
    'ach.1000km.d': 'mil kilómetros ({km})',
    'ach.oiapoque-chui.t': 'De Oiapoque a Chuí',
    'ach.oiapoque-chui.d': 'el equivalente a ir de Oiapoque a Chuí, de punta a punta de Brasil ({km})',
    'ach.rio-amazonas.t': 'Río Amazonas',
    'ach.rio-amazonas.d': 'la longitud del río Amazonas ({km})',
    'ach.litoral-brasil.t': 'Costa de Brasil',
    'ach.litoral-brasil.d': 'toda la costa de Brasil ({km})',
    'ach.transiberiana.t': 'Transiberiano',
    'ach.transiberiana.d': 'el Ferrocarril Transiberiano, de Moscú a Vladivostok ({km})',
    'ach.muralha-china.t': 'Gran Muralla China',
    'ach.muralha-china.d': 'la Gran Muralla China con todos sus tramos ({km})',
    'ach.volta-ao-mundo.t': 'Vuelta al mundo',
    'ach.volta-ao-mundo.d': 'una vuelta al mundo por la línea del ecuador ({km})',
    'ach.ate-a-lua.t': 'Hasta la Luna',
    'ach.ate-a-lua.d': 'la distancia de la Tierra a la Luna ({km})',
    'ach.primeira-corrida.t': 'La salida',
    'ach.primeira-corrida.d': 'Termina tu primera carrera',
    'ach.10-corridas.t': 'Hábito',
    'ach.10-corridas.d': 'Termina 10 carreras',
    'ach.100-corridas.t': 'Veterano',
    'ach.100-corridas.d': 'Termina 100 carreras',
    'ach.corrida-5km.t': '5 km de un tirón',
    'ach.corrida-5km.d': 'Corre 5 km en una sola carrera',
    'ach.corrida-10km.t': '10 km de un tirón',
    'ach.corrida-10km.d': 'Corre 10 km en una sola carrera',
    'ach.veloz-18.t': 'Veloz',
    'ach.veloz-18.d': 'Llega a 18 km/h',
    'ach.veloz-22.t': 'Cohete',
    'ach.veloz-22.d': 'Llega a 22 km/h',
    'ach.ultrapassa-1.t': '¡Con permiso!',
    'ach.ultrapassa-1.d': 'Adelanta a tu primer corredor',
    'ach.ultrapassa-100.t': 'Atrás el pelotón',
    'ach.ultrapassa-100.d': 'Adelanta a 100 corredores',
    'ach.ultrapassa-1000.t': 'Huracán',
    'ach.ultrapassa-1000.d': 'Adelanta a 1.000 corredores',
    'ach.ultrapassa-10000.t': 'Leyenda de la calle',
    'ach.ultrapassa-10000.d': 'Adelanta a 10.000 corredores',
    'ach.dias-3.t': '¡Volví!',
    'ach.dias-3.d': 'Juega en 3 días distintos',
    'ach.dias-7.t': 'Una semana',
    'ach.dias-7.d': 'Juega en 7 días distintos',
    'ach.dias-30.t': 'Rutina de atleta',
    'ach.dias-30.d': 'Juega en 30 días distintos',
    'ach.perfect-100.t': 'Al compás',
    'ach.perfect-100.d': 'Logra 100 PERFECT',
    'ach.perfect-1000.t': 'Metrónomo',
    'ach.perfect-1000.d': 'Logra 1.000 PERFECT',
    'ach.perfect-10000.t': 'Ritmo perfecto',
    'ach.perfect-10000.d': 'Logra 10.000 PERFECT',
    'ach.flow-4.t': 'Fluyendo',
    'ach.flow-4.d': 'Llega a FLOW ×4',
    'ach.flow-8.t': 'En llamas',
    'ach.flow-8.d': 'Llega a FLOW ×8',
    'ach.flow-12.t': 'Estado de FLOW',
    'ach.flow-12.d': 'Llega a FLOW ×12',
    'ach.combo-5.t': 'Combo',
    'ach.combo-5.d': 'Llega a un combo ×5 de adelantamientos',
    'ach.combo-10.t': 'Combo brutal',
    'ach.combo-10.d': 'Llega a un combo ×10 de adelantamientos',
    'ach.desafio-1.t': 'Desafiado',
    'ach.desafio-1.d': 'Completa un desafío',
    'ach.desafio-10.t': 'Cazador de desafíos',
    'ach.desafio-10.d': 'Completa 10 desafíos',
    'ach.desafio-50.t': 'Maestro de desafíos',
    'ach.desafio-50.d': 'Completa 50 desafíos',
    'ach.sprint-40.t': 'Arrancada',
    'ach.sprint-40.d': 'Haz los 200 m del SPRINT en 40 s o menos',
    'ach.sprint-32.t': 'Relámpago',
    'ach.sprint-32.d': 'Haz los 200 m del SPRINT en 32 s o menos',
    'ach.pacer-1.t': 'Pegado al pacer',
    'ach.pacer-1.d': 'Sigue a un pacer hasta el final',
    'ach.pacer-10.t': 'Ritmo de carrera',
    'ach.pacer-10.d': 'Sigue a 10 pacers hasta el final',
    'ach.vacuo-300.t': 'Aerodinámico',
    'ach.vacuo-300.d': 'Corre 5 minutos al rebufo de otros corredores',
    'ach.primeiro-item.t': 'Primera compra',
    'ach.primeiro-item.d': 'Compra un artículo en la tienda',
    'ach.10-itens.t': 'Coleccionista',
    'ach.10-itens.d': 'Ten 10 artículos',
    'ach.lendario.t': 'Legendario',
    'ach.lendario.d': 'Ten un artículo legendario',
    'ach.nivel-5.t': 'Nivel 5',
    'ach.nivel-5.d': 'Llega al nivel 5',
    'ach.nivel-10.t': 'Nivel 10',
    'ach.nivel-10.d': 'Llega al nivel 10',
    'ach.nivel-25.t': 'Nivel 25',
    'ach.nivel-25.d': 'Llega al nivel 25',
    'ach.regiao-2.t': 'Explorador',
    'ach.regiao-2.d': 'Desbloquea 2 regiones',
    'ach.regiao-4.t': 'Viajero',
    'ach.regiao-4.d': 'Desbloquea 4 regiones',
    'ach.regiao-8.t': 'Gira mundial',
    'ach.regiao-8.d': 'Desbloquea 8 regiones',
    'ach.offline-10.t': 'Entrenamiento invisible',
    'ach.offline-10.d': 'Suma 10 km de entrenamiento con el juego cerrado',
    'mis.title': 'MISIONES DEL DÍA',
    'mis.reset': 'Nuevas misiones en {t}',
    'mis.claim': 'Reclamar',
    'mis.claimed': 'Reclamada',
    'mis.bonus': 'Bono del día',
    'mis.bonusDesc': 'Reclama las tres misiones de hoy',
    'mis.dist': 'Corre {n}',
    'mis.flow': 'Mantente {n} en FLOW',
    'mis.perfect': 'Logra {n} PERFECT',
    'mis.overtake': 'Adelanta a {n} corredores',
    'mis.combo': 'Llega a un combo ×{n} de adelantamientos',
    'mis.challenge': 'Completa {n} desafíos',
    'mis.challenge.1': 'Completa 1 desafío',
    'mis.speed': 'Alcanza {n}',
    'mis.draft': 'Corre {n} al rebufo de otro corredor',
    'mis.pacer': 'Sigue a {n} pacers hasta el final',
    'mis.pacer.1': 'Sigue a un pacer hasta el final',
    'mis.runs': 'Termina {n} carreras',
    'mis.runs.1': 'Termina una carrera',
    'pop.ok': 'OK',
    'pop.later': 'Después',
    'pop.equip': 'Equipar ahora',
    'pop.offline.t': 'MIENTRAS NO ESTABAS',
    'pop.offline.d': 'Tu corredor entrenó {h} y corrió {d}.',
    'pop.offline.cap': 'El entrenamiento offline dura hasta {h} h. Los relojes amplían ese límite.',
    'pop.level.t': '¡NIVEL {n}!',
    'pop.level.d': 'Tu título: {title}',
    'pop.level.refund': 'Ya tenías {item}: el regalo se convirtió en monedas.',
    'pop.ach.t': '¡LOGRO!',
    'pop.region.t': 'NUEVA REGIÓN',
    'pop.region.d': '{name} ya está disponible para correr.',
    'pop.gift.t': 'REGALO DE BIENVENIDA',
    'pop.gift.d': 'Recibiste {n} monedas para estrenar la tienda. ¿Qué tal unas zapatillas nuevas?',
    'pop.gift.go': 'Ir a la tienda',
    'toast.ach': 'Logro',
    'toast.mission': 'Misión cumplida',
    'toast.level': 'Subiste de nivel',
    'sum.levelUp': '¡Subiste al nivel {n}!',
    'sum.achievements': 'Logros de esta carrera',
    'sum.missions': 'Misiones cumplidas',
    'sum.missionsHint': 'Reclama los premios en la pantalla de misiones.'
  };
})(window.EP);
