// Textos em português do Brasil. As chaves são as mesmas nos três idiomas.
(function (EP) {
  EP.texts['pt-BR'] = {
    'lang.name': 'Português',
    'app.tagline': 'Até onde você consegue correr?',
    'boot.loading': 'Aquecendo…',
    'boot.noWebgl': 'Este navegador não conseguiu abrir o 3D. Atualize o navegador ou tente outro.',
    'boot.noSave': 'O navegador bloqueou o armazenamento: dá para correr, mas o progresso não fica salvo.',

    'create.title': 'CRIE SEU CORREDOR',
    'create.step': 'Passo {n} de 4',
    'create.who': 'Quem vai correr?',
    'gender.m': 'Corredor',
    'gender.f': 'Corredora',
    'create.nameTitle': 'Qual é o nome?',
    'create.namePh': 'Nome do corredor',
    'create.nameHint': 'Até 15 letras. Ele aparece no seu perfil.',
    'create.looks': 'Aparência',
    'create.skin': 'Tom de pele',
    'create.hairStyle': 'Cabelo',
    'create.hairColor': 'Cor do cabelo',
    'hair.curto': 'Curto',
    'hair.cacheado': 'Cacheado',
    'hair.rabo': 'Rabo de cavalo',
    'hair.coque': 'Coque',
    'hair.longo': 'Longo',
    'hair.raspado': 'Raspado',
    'create.outfit': 'Roupa inicial',
    'create.outfitHint': 'Camiseta, short e tênis. Escolha as cores.',
    'create.shirt': 'Camiseta',
    'create.shorts': 'Short',
    'create.shoes': 'Tênis',
    'create.rotate': 'Arraste para girar',
    'ui.next': 'Próximo',
    'ui.back': 'Voltar',
    'ui.start': 'Começar a correr',
    'ui.save': 'Salvar',
    'ui.continue': 'Continuar',
    'ui.close': 'Fechar',
    'ui.cancel': 'Cancelar',
    'ui.confirm': 'Apagar',

    'home.run': 'CORRER',
    'home.total': 'percorridos',
    'home.coins': 'Moedas',
    'home.runner': 'Corredor',
    'home.records': 'Recordes',
    'home.options': 'Opções',
    'home.firstRun': 'Sua jornada começa agora',
    'home.best': 'Maior corrida: {d}',

    'hud.distance': 'DISTÂNCIA',
    'hud.speed': 'KM/H',
    'hud.energy': 'ENERGIA',
    'hud.overtakes': 'ULTRAPASSAGENS',
    'hud.pause': 'Pausar',
    'hud.flow': 'FLOW ×{n}',
    'hud.combo': 'COMBO ×{n}',
    'hud.lowEnergy': 'Energia baixa: diminua e recupere',
    'hud.spam': 'Calma! Ritmo vale mais que força',
    'rating.perfect': 'PERFECT',
    'rating.great': 'GREAT',
    'rating.good': 'GOOD',
    'rating.off': 'FORA DO RITMO',
    'zone.walk': 'CAMINHADA',
    'zone.jog': 'TROTE',
    'zone.run': 'CORRIDA',
    'zone.fast': 'CORRIDA FORTE',
    'zone.sprint': 'SPRINT',

    'tut.1': 'TOQUE PARA CORRER',
    'tut.1b': 'Cada toque é uma passada',
    'tut.1k': 'Toque na tela, clique ou aperte ESPAÇO',
    'tut.2': 'MANTENHA O RITMO',
    'tut.2b': 'Toque sempre no mesmo compasso, como uma música',
    'tut.3': 'PERFECT!',
    'tut.3b': 'Siga assim e entre no FLOW',
    'tut.4': 'DESLIZE PARA ESCOLHER SEU CAMINHO',
    'tut.4b': 'Deslize o dedo para o lado (ou use as setas)',
    'tut.done': 'Pronto! Agora é com você',

    'fork.title': 'ESCOLHA SEU CAMINHO',
    'fork.hint': 'Deslize para o lado',
    'route.bairro': 'BAIRRO',
    'route.parque': 'PARQUE',
    'route.centro': 'CENTRO',
    'route.entered': 'Rota: {name}',
    'route.back': 'De volta ao bairro',
    'perk.energy10': 'Energia +10%',
    'perk.fewerRunners': 'Menos corredores',
    'perk.coins20': 'Moedas +20%',
    'perk.moreRunners': 'Mais corredores',

    'ch.label': 'DESAFIO',
    'ch.flow.title': 'FLOW',
    'ch.flow.desc': 'Faça {n} PERFECT seguidos',
    'ch.pace.title': 'PACE',
    'ch.pace.desc': 'Segure {v} km/h (±1) por {n} s',
    'ch.overtake.title': 'ULTRAPASSE',
    'ch.overtake.desc': 'Passe {n} corredores',
    'ch.combo.title': 'COMBO',
    'ch.combo.desc': 'Chegue ao combo ×{n}',
    'ch.energy.title': 'FÔLEGO',
    'ch.energy.desc': 'Corra forte por {n} s sem deixar a energia cair de 35%',
    'ch.sprint.title': 'SPRINT',
    'ch.sprint.desc': 'Corra {n} m o mais rápido que puder',
    'ch.draft.title': 'VÁCUO',
    'ch.draft.desc': 'Fique {n} s logo atrás de outro corredor',
    'ch.pacer.title': 'PACER',
    'ch.pacer.desc': 'Acompanhe o corredor de bandeira por {n} m',
    'ch.hint.faster': 'acelere',
    'ch.hint.slower': 'segure',
    'ch.sprintTime': '{t} s',
    'ch.record': 'Novo recorde nos 200 m: {t} s!',
    'hud.draft': 'VÁCUO',
    'ch.done': 'DESAFIO COMPLETO!',
    'ch.failed': 'Quase! Fica para o próximo',
    'ch.reward': '+{n} moedas',

    'toast.km': '{n} km nesta corrida!',
    'toast.flowUp': 'FLOW ×{n}',

    'pause.title': 'PAUSA',
    'pause.resume': 'Continuar correndo',
    'pause.finish': 'Encerrar corrida',
    'pause.options': 'Opções',
    'pause.hint': 'Seu progresso já está salvo.',

    'sum.title': 'CORRIDA CONCLUÍDA',
    'sum.first': 'PRIMEIRA CORRIDA!',
    'sum.distance': 'Distância',
    'sum.time': 'Tempo',
    'sum.pace': 'Ritmo médio',
    'sum.avg': 'Velocidade média',
    'sum.top': 'Maior velocidade',
    'sum.overtakes': 'Ultrapassagens',
    'sum.flow': 'Maior FLOW',
    'sum.combo': 'Maior combo',
    'sum.perfects': 'PERFECT',
    'sum.challenges': 'Desafios',
    'sum.coins': 'Moedas ganhas',
    'sum.total': 'O seu corredor já percorreu {d}',
    'sum.record': 'RECORDE',
    'sum.paceUnit': '/km',

    'rec.title': 'RECORDES',
    'rec.profile': 'Perfil',
    'rec.totalDistance': 'Distância total',
    'rec.totalTime': 'Tempo correndo',
    'rec.runs': 'Corridas',
    'rec.overtakes': 'Ultrapassagens',
    'rec.perfects': 'Total de PERFECT',
    'rec.challenges': 'Desafios completados',
    'rec.regions': 'Regiões',
    'rec.best': 'Melhores marcas',
    'rec.topSpeed': 'Maior velocidade',
    'rec.maxFlow': 'Maior FLOW',
    'rec.maxCombo': 'Maior combo',
    'rec.longestRun': 'Maior corrida',
    'rec.mostOvertakes': 'Mais ultrapassagens numa corrida',

    'opt.title': 'OPÇÕES',
    'opt.lang': 'Idioma',
    'opt.music': 'Música',
    'opt.sfx': 'Efeitos sonoros',
    'opt.vibration': 'Vibração',
    'opt.reduceMotion': 'Reduzir movimento da câmera',
    'opt.bigUi': 'Interface maior',
    'opt.quality': 'Qualidade gráfica',
    'opt.qualityNote': 'Muda ao abrir o jogo de novo.',
    'q.auto': 'Automática',
    'q.high': 'Alta',
    'q.low': 'Leve',
    'opt.controls': 'Controles',
    'opt.controlsText': 'Toque: passada. Deslize: muda de lado e escolhe o caminho. No teclado: ESPAÇO e setas. ESC pausa.',
    'opt.reset': 'Apagar progresso',
    'opt.resetConfirm': 'Apagar todo o progresso deste aparelho? Não dá para desfazer.',
    'opt.version': 'Versão {v}',
    'opt.privacy': 'Privacidade',

    'region.welcome': 'BEM-VINDO À REGIÃO',
    'biome.cidade': 'Cidade',
    'sign.choose': 'ESCOLHA',

    // loja, equipar, nível, conquistas, missões e avisos
    'home.shop': 'Loja',
    'home.shopSub': 'Tênis, roupas e acessórios',
    'home.equip': 'Equipar',
    'home.achievements': 'Conquistas',
    'home.missions': 'Missões',
    'home.profile': 'Perfil e recordes',
    'lvl.short': 'NÍV',
    'lvl.level': 'Nível {n}',
    'lvl.title.1': 'Iniciante',
    'lvl.title.2': 'Em ritmo',
    'lvl.title.3': 'Fundista',
    'lvl.title.4': 'Maratonista',
    'lvl.title.5': 'Ultramaratonista',
    'lvl.title.6': 'Elite',
    'lvl.title.7': 'Lenda',
    'slot.head': 'Cabeça',
    'slot.eyes': 'Óculos',
    'slot.ears': 'Fones',
    'slot.shirt': 'Camiseta',
    'slot.shorts': 'Short',
    'slot.shoes': 'Tênis',
    'slot.wrist': 'Pulso',
    'rarity.comum': 'Comum',
    'rarity.raro': 'Raro',
    'rarity.epico': 'Épico',
    'rarity.lendario': 'Lendário',
    'stat.speed': 'Velocidade',
    'stat.energy': 'Energia',
    'stat.recovery': 'Recuperação',
    'stat.flow': 'FLOW',
    'stat.flowWindow': 'Janela do PERFECT',
    'stat.flowBonus': 'Bônus de FLOW',
    'stat.efficiency': 'Eficiência',
    'stat.offline': 'Treino offline',
    'stat.speed.fx': 'Velocidade e velocidade máxima +{v}%',
    'stat.energy.fx': '+{v} de energia máxima',
    'stat.recovery.fx': 'Recupera energia {v}% mais rápido',
    'stat.flow.fx': 'FLOW sobe {v}% mais rápido e cai mais devagar',
    'stat.flowWindow.fx': 'PERFECT e GREAT {v}% mais fáceis de acertar',
    'stat.flowBonus.fx': '+{v}% de moedas enquanto estiver em FLOW',
    'stat.efficiency.fx': 'Gasta {v}% menos energia',
    'stat.offline.fx': 'Treina até {h} h com o jogo fechado, {v}% mais rápido',
    'shop.title': 'LOJA',
    'shop.cat.tenis': 'Tênis',
    'shop.cat.roupas': 'Roupas',
    'shop.cat.bones': 'Bonés',
    'shop.cat.oculos': 'Óculos',
    'shop.cat.fones': 'Fones',
    'shop.cat.relogios': 'Relógios',
    'shop.buy': 'Comprar',
    'shop.owned': 'Seu',
    'shop.equipped': 'Equipado',
    'shop.equip': 'Equipar',
    'shop.equipNow': 'Equipar agora',
    'shop.keep': 'Continuar na loja',
    'shop.needCoins': 'Faltam {n} moedas. Mais uma corrida e chega lá!',
    'shop.needLevel': 'Liberado no nível {n}',
    'shop.levelTag': 'Nível {n}',
    'shop.bought': 'Comprado!',
    'shop.compare': 'Comparado com o que você usa',
    'shop.current': 'Agora você usa: {name}',
    'shop.same': 'Mesmos atributos',
    'shop.noStats': 'Item só de visual.',
    'shop.set': 'Conjunto {name}',
    'shop.effects': 'O que muda na corrida',
    'set.tropical': 'Tropical',
    'set.nuvem': 'Nuvem',
    'set.montanha': 'Montanha',
    'set.cometa': 'Cometa',
    'set.aurora': 'Aurora',
    'set.neon': 'Neon',
    'equip.title': 'EQUIPAR',
    'equip.hint': 'Toque num item para vestir. Arraste o corredor para girar.',
    'equip.totals': 'Seus bônus',
    'equip.noBonus': 'A roupa básica não dá bônus. Itens da loja deixam você mais rápido, com mais energia e mais FLOW.',
    'equip.none': 'Nenhum',
    'equip.toShop': 'Loja',
    'item.camiseta-basica': 'Camiseta básica',
    'item.short-basico': 'Short básico',
    'item.tenis-basico': 'Tênis básico',
    'item.tenis-leve': 'Tênis Leve',
    'item.tenis-asfalto': 'Tênis Asfalto',
    'item.tenis-tropical': 'Tênis Tropical',
    'item.tenis-pista': 'Tênis Pista',
    'item.tenis-nuvem': 'Tênis Nuvem',
    'item.tenis-brisa': 'Tênis Brisa',
    'item.tenis-urbano': 'Tênis Urbano',
    'item.tenis-trilha': 'Tênis Trilha',
    'item.tenis-cometa': 'Tênis Cometa',
    'item.tenis-aurora': 'Tênis Aurora',
    'item.tenis-maratona': 'Tênis Maratona',
    'item.tenis-relampago': 'Tênis Relâmpago',
    'item.camiseta-sol': 'Camiseta Sol',
    'item.camiseta-oceano': 'Camiseta Oceano',
    'item.regata-verao': 'Regata Verão',
    'item.regata-tropical': 'Regata Tropical',
    'item.camiseta-listrada': 'Camiseta Listrada',
    'item.manga-longa-neblina': 'Manga Longa Neblina',
    'item.corta-vento-aurora': 'Corta-vento Aurora',
    'item.camiseta-neon': 'Camiseta Neon',
    'item.corta-vento-cometa': 'Corta-vento Cometa',
    'item.short-classico': 'Short Clássico',
    'item.short-corrida': 'Short de Corrida',
    'item.bermuda-praia': 'Bermuda Praia',
    'item.legging-noite': 'Legging Noite',
    'item.saia-short-flor': 'Saia-short Flor',
    'item.short-pro': 'Short Pro',
    'item.legging-aurora': 'Legging Aurora',
    'item.bone-classico': 'Boné Clássico',
    'item.viseira-sol': 'Viseira Sol',
    'item.faixa-suor': 'Faixa de Suor',
    'item.bandana-tropical': 'Bandana Tropical',
    'item.gorro-montanha': 'Gorro Montanha',
    'item.bone-aba-reta-neon': 'Boné Aba Reta Neon',
    'item.viseira-pro': 'Viseira Pro',
    'item.bone-aurora': 'Boné Aurora',
    'item.oculos-classico': 'Óculos Clássico',
    'item.oculos-sol-classico': 'Óculos de Sol Clássico',
    'item.oculos-esporte-azul': 'Óculos Esporte Azul',
    'item.oculos-sol-praia': 'Óculos de Sol Praia',
    'item.oculos-esporte-cometa': 'Óculos Esporte Cometa',
    'item.oculos-aurora': 'Óculos Aurora',
    'item.fone-sem-fio-branco': 'Fone sem Fio Branco',
    'item.fone-classico': 'Fone Clássico',
    'item.fone-esporte-azul': 'Fone Esporte Azul',
    'item.fone-neon': 'Fone Neon',
    'item.fone-estudio': 'Fone Estúdio',
    'item.fone-aurora': 'Fone Aurora',
    'item.pulseira-amizade': 'Pulseira da Amizade',
    'item.relogio-simples': 'Relógio Simples',
    'item.relogio-digital': 'Relógio Digital',
    'item.pulseira-esporte': 'Pulseira Esporte',
    'item.smartwatch-azul': 'Smartwatch Azul',
    'item.relogio-explorador': 'Relógio Explorador',
    'item.smartwatch-aurora': 'Smartwatch Aurora',
    'ach.title': 'CONQUISTAS',
    'ach.new': 'Nova',
    'ach.unlockedOn': 'Conquistada em {d}',
    'ach.best': 'Melhor: {v}',
    'ach.goal': 'Meta: {v}',
    'ach.goalRef': 'Corra no total {d}',
    'ach.doneRef': 'Você correu {d}!',
    'achcat.distancia': 'Jornada',
    'achcat.corrida': 'Corrida',
    'achcat.ritmo': 'Ritmo',
    'achcat.desafio': 'Desafios',
    'achcat.colecao': 'Coleção',
    'achcat.exploracao': 'Exploração',
    'ach.primeiro-km.t': 'Primeiro quilômetro',
    'ach.primeiro-km.d': 'o seu primeiro quilômetro ({km})',
    'ach.5km.t': '5 km',
    'ach.5km.d': '{km}, a distância de uma clássica prova de rua',
    'ach.10km.t': '10 km',
    'ach.10km.d': '{km}, uma das provas de rua mais populares',
    'ach.ponte-rio-niteroi.t': 'Ponte Rio–Niterói',
    'ach.ponte-rio-niteroi.d': 'o equivalente à Ponte Rio–Niterói ({km})',
    'ach.meia-maratona.t': 'Meia maratona',
    'ach.meia-maratona.d': 'uma meia maratona inteira ({km})',
    'ach.maratona.t': 'Maratona',
    'ach.maratona.d': 'uma maratona inteira ({km})',
    'ach.ultra-100.t': 'Ultramaratona',
    'ach.ultra-100.d': '{km}, a distância de uma ultramaratona clássica',
    'ach.sp-rio.t': 'São Paulo–Rio',
    'ach.sp-rio.d': 'o equivalente à viagem de São Paulo ao Rio de Janeiro ({km})',
    'ach.1000km.t': 'Mil quilômetros',
    'ach.1000km.d': 'mil quilômetros ({km})',
    'ach.oiapoque-chui.t': 'Do Oiapoque ao Chuí',
    'ach.oiapoque-chui.d': 'o equivalente a ir do Oiapoque ao Chuí, de ponta a ponta do Brasil ({km})',
    'ach.rio-amazonas.t': 'Rio Amazonas',
    'ach.rio-amazonas.d': 'o comprimento do Rio Amazonas ({km})',
    'ach.litoral-brasil.t': 'Litoral do Brasil',
    'ach.litoral-brasil.d': 'todo o litoral do Brasil ({km})',
    'ach.transiberiana.t': 'Transiberiana',
    'ach.transiberiana.d': 'a Ferrovia Transiberiana, de Moscou a Vladivostok ({km})',
    'ach.muralha-china.t': 'Muralha da China',
    'ach.muralha-china.d': 'a Grande Muralha da China com todos os seus trechos ({km})',
    'ach.volta-ao-mundo.t': 'Volta ao mundo',
    'ach.volta-ao-mundo.d': 'uma volta ao mundo pela linha do Equador ({km})',
    'ach.ate-a-lua.t': 'Até a Lua',
    'ach.ate-a-lua.d': 'a distância da Terra até a Lua ({km})',
    'ach.primeira-corrida.t': 'Largada',
    'ach.primeira-corrida.d': 'Termine sua primeira corrida',
    'ach.10-corridas.t': 'Hábito',
    'ach.10-corridas.d': 'Termine 10 corridas',
    'ach.100-corridas.t': 'Veterano',
    'ach.100-corridas.d': 'Termine 100 corridas',
    'ach.corrida-5km.t': 'Fôlego de 5 km',
    'ach.corrida-5km.d': 'Corra 5 km numa única corrida',
    'ach.corrida-10km.t': 'Fôlego de 10 km',
    'ach.corrida-10km.d': 'Corra 10 km numa única corrida',
    'ach.veloz-18.t': 'Veloz',
    'ach.veloz-18.d': 'Chegue a 18 km/h',
    'ach.veloz-22.t': 'Foguete',
    'ach.veloz-22.d': 'Chegue a 22 km/h',
    'ach.ultrapassa-1.t': 'Com licença!',
    'ach.ultrapassa-1.d': 'Ultrapasse seu primeiro corredor',
    'ach.ultrapassa-100.t': 'Pelotão para trás',
    'ach.ultrapassa-100.d': 'Ultrapasse 100 corredores',
    'ach.ultrapassa-1000.t': 'Furacão',
    'ach.ultrapassa-1000.d': 'Ultrapasse 1.000 corredores',
    'ach.ultrapassa-10000.t': 'Lenda das ruas',
    'ach.ultrapassa-10000.d': 'Ultrapasse 10.000 corredores',
    'ach.dias-3.t': 'Voltei!',
    'ach.dias-3.d': 'Jogue em 3 dias diferentes',
    'ach.dias-7.t': 'Uma semana',
    'ach.dias-7.d': 'Jogue em 7 dias diferentes',
    'ach.dias-30.t': 'Rotina de atleta',
    'ach.dias-30.d': 'Jogue em 30 dias diferentes',
    'ach.perfect-100.t': 'No compasso',
    'ach.perfect-100.d': 'Faça 100 PERFECT',
    'ach.perfect-1000.t': 'Metrônomo',
    'ach.perfect-1000.d': 'Faça 1.000 PERFECT',
    'ach.perfect-10000.t': 'Ritmo perfeito',
    'ach.perfect-10000.d': 'Faça 10.000 PERFECT',
    'ach.flow-4.t': 'Fluindo',
    'ach.flow-4.d': 'Chegue ao FLOW ×4',
    'ach.flow-8.t': 'Em chamas',
    'ach.flow-8.d': 'Chegue ao FLOW ×8',
    'ach.flow-12.t': 'Estado de FLOW',
    'ach.flow-12.d': 'Chegue ao FLOW ×12',
    'ach.combo-5.t': 'Combo',
    'ach.combo-5.d': 'Chegue ao combo ×5 de ultrapassagens',
    'ach.combo-10.t': 'Combo insano',
    'ach.combo-10.d': 'Chegue ao combo ×10 de ultrapassagens',
    'ach.desafio-1.t': 'Desafiado',
    'ach.desafio-1.d': 'Complete um desafio',
    'ach.desafio-10.t': 'Caçador de desafios',
    'ach.desafio-10.d': 'Complete 10 desafios',
    'ach.desafio-50.t': 'Mestre dos desafios',
    'ach.desafio-50.d': 'Complete 50 desafios',
    'ach.sprint-40.t': 'Arrancada',
    'ach.sprint-40.d': 'Faça os 200 m do SPRINT em 40 s ou menos',
    'ach.sprint-32.t': 'Relâmpago',
    'ach.sprint-32.d': 'Faça os 200 m do SPRINT em 32 s ou menos',
    'ach.pacer-1.t': 'Na cola do pacer',
    'ach.pacer-1.d': 'Acompanhe um pacer até o fim',
    'ach.pacer-10.t': 'Ritmo de prova',
    'ach.pacer-10.d': 'Acompanhe 10 pacers até o fim',
    'ach.vacuo-300.t': 'Aerodinâmico',
    'ach.vacuo-300.d': 'Corra 5 minutos no vácuo de outros corredores',
    'ach.primeiro-item.t': 'Primeira compra',
    'ach.primeiro-item.d': 'Compre um item na loja',
    'ach.10-itens.t': 'Colecionador',
    'ach.10-itens.d': 'Tenha 10 itens',
    'ach.lendario.t': 'Lendário',
    'ach.lendario.d': 'Tenha um item lendário',
    'ach.nivel-5.t': 'Nível 5',
    'ach.nivel-5.d': 'Chegue ao nível 5',
    'ach.nivel-10.t': 'Nível 10',
    'ach.nivel-10.d': 'Chegue ao nível 10',
    'ach.nivel-25.t': 'Nível 25',
    'ach.nivel-25.d': 'Chegue ao nível 25',
    'ach.regiao-2.t': 'Explorador',
    'ach.regiao-2.d': 'Libere 2 regiões',
    'ach.regiao-4.t': 'Viajante',
    'ach.regiao-4.d': 'Libere 4 regiões',
    'ach.regiao-8.t': 'Volta ao mapa',
    'ach.regiao-8.d': 'Libere 8 regiões',
    'ach.offline-10.t': 'Treino invisível',
    'ach.offline-10.d': 'Some 10 km de treino com o jogo fechado',
    'mis.title': 'MISSÕES DO DIA',
    'mis.reset': 'Novas missões em {t}',
    'mis.claim': 'Resgatar',
    'mis.claimed': 'Resgatada',
    'mis.bonus': 'Bônus do dia',
    'mis.bonusDesc': 'Resgate as três missões de hoje',
    'mis.dist': 'Corra {n}',
    'mis.flow': 'Fique {n} em FLOW',
    'mis.perfect': 'Faça {n} PERFECT',
    'mis.overtake': 'Ultrapasse {n} corredores',
    'mis.combo': 'Chegue ao combo ×{n} de ultrapassagens',
    'mis.challenge': 'Complete {n} desafios',
    'mis.challenge.1': 'Complete 1 desafio',
    'mis.speed': 'Alcance {n}',
    'mis.draft': 'Corra {n} no vácuo de outro corredor',
    'mis.pacer': 'Acompanhe {n} pacers até o fim',
    'mis.pacer.1': 'Acompanhe um pacer até o fim',
    'mis.runs': 'Termine {n} corridas',
    'mis.runs.1': 'Termine uma corrida',
    'pop.ok': 'OK',
    'pop.later': 'Depois',
    'pop.equip': 'Equipar agora',
    'pop.offline.t': 'ENQUANTO VOCÊ ESTEVE FORA',
    'pop.offline.d': 'Seu corredor treinou por {h} e correu {d}.',
    'pop.offline.cap': 'O treino offline vai até {h} h. Relógios aumentam esse limite.',
    'pop.level.t': 'NÍVEL {n}!',
    'pop.level.d': 'Seu título: {title}',
    'pop.ach.t': 'CONQUISTA!',
    'pop.region.t': 'NOVA REGIÃO',
    'pop.region.d': '{name} liberada para correr.',
    'pop.gift.t': 'PRESENTE DE BOAS-VINDAS',
    'pop.gift.d': 'Você ganhou {n} moedas para estrear a loja. Que tal um tênis novo?',
    'pop.gift.go': 'Ir à loja',
    'toast.ach': 'Conquista',
    'toast.mission': 'Missão cumprida',
    'toast.level': 'Subiu de nível',
    'sum.levelUp': 'Subiu para o nível {n}!',
    'sum.achievements': 'Conquistas desta corrida',
    'sum.missions': 'Missões cumpridas',
    'sum.missionsHint': 'Resgate os prêmios na tela de missões.'
  };
})(window.EP);
