// Textos em português do Brasil. As chaves são as mesmas nos três idiomas.
(function (EP) {
  EP.texts['pt-BR'] = {
    'lang.name': 'Português',
    'app.tagline': 'Até onde você consegue correr?',
    'boot.loading': 'Aquecendo…',
    'boot.noWebgl': 'Este navegador não conseguiu abrir o 3D. Atualize o navegador ou tente outro.',
    'boot.noSave': 'O navegador bloqueou o armazenamento: dá para correr, mas o progresso não fica salvo.',

    'create.title': 'CRIE SEU CORREDOR',
    'create.step': 'Passo {n} de 4',
    'create.who': 'Quem vai correr?',
    'gender.m': 'Corredor',
    'gender.f': 'Corredora',
    'create.nameTitle': 'Qual é o nome?',
    'create.namePh': 'Nome do corredor',
    'create.nameHint': 'Até 15 letras. Ele aparece no seu perfil.',
    'create.looks': 'Aparência',
    'create.skin': 'Tom de pele',
    'create.hairStyle': 'Cabelo',
    'create.hairColor': 'Cor do cabelo',
    'hair.curto': 'Curto',
    'hair.cacheado': 'Cacheado',
    'hair.rabo': 'Rabo de cavalo',
    'hair.coque': 'Coque',
    'hair.longo': 'Longo',
    'hair.raspado': 'Raspado',
    'create.outfit': 'Roupa inicial',
    'create.outfitHint': 'Camiseta, short e tênis. Escolha as cores.',
    'create.shirt': 'Camiseta',
    'create.shorts': 'Short',
    'create.shoes': 'Tênis',
    'create.rotate': 'Arraste para girar',
    'ui.next': 'Próximo',
    'ui.back': 'Voltar',
    'ui.start': 'Começar a correr',
    'ui.save': 'Salvar',
    'ui.continue': 'Continuar',
    'ui.close': 'Fechar',
    'ui.cancel': 'Cancelar',
    'ui.confirm': 'Apagar',

    'home.run': 'CORRER',
    'home.total': 'percorridos',
    'home.coins': 'Moedas',
    'home.runner': 'Corredor',
    'home.records': 'Recordes',
    'home.options': 'Opções',
    'home.firstRun': 'Sua jornada começa agora',
    'home.best': 'Maior corrida: {d}',

    'hud.distance': 'DISTÂNCIA',
    'hud.speed': 'KM/H',
    'hud.energy': 'ENERGIA',
    'hud.overtakes': 'ULTRAPASSAGENS',
    'hud.pause': 'Pausar',
    'hud.flow': 'FLOW ×{n}',
    'hud.combo': 'COMBO ×{n}',
    'hud.lowEnergy': 'Energia baixa: diminua e recupere',
    'hud.spam': 'Calma! Ritmo vale mais que força',
    'rating.perfect': 'PERFECT',
    'rating.great': 'GREAT',
    'rating.good': 'GOOD',
    'rating.off': 'FORA DO RITMO',
    'zone.walk': 'CAMINHADA',
    'zone.jog': 'TROTE',
    'zone.run': 'CORRIDA',
    'zone.fast': 'CORRIDA FORTE',
    'zone.sprint': 'SPRINT',

    'tut.1': 'TOQUE PARA CORRER',
    'tut.1b': 'Cada toque é uma passada',
    'tut.1k': 'Toque na tela, clique ou aperte ESPAÇO',
    'tut.2': 'MANTENHA O RITMO',
    'tut.2b': 'Toque sempre no mesmo compasso, como uma música',
    'tut.3': 'PERFECT!',
    'tut.3b': 'Siga assim e entre no FLOW',
    'tut.4': 'DESLIZE PARA ESCOLHER SEU CAMINHO',
    'tut.4b': 'Deslize o dedo para o lado (ou use as setas)',
    'tut.done': 'Pronto! Agora é com você',

    'fork.title': 'ESCOLHA SEU CAMINHO',
    'fork.hint': 'Deslize para o lado',
    'route.bairro': 'BAIRRO',
    'route.parque': 'PARQUE',
    'route.centro': 'CENTRO',
    'route.entered': 'Rota: {name}',
    'route.back': 'De volta ao bairro',
    'perk.energy10': 'Energia +10%',
    'perk.fewerRunners': 'Menos corredores',
    'perk.coins20': 'Moedas +20%',
    'perk.moreRunners': 'Mais corredores',

    'ch.label': 'DESAFIO',
    'ch.flow.title': 'FLOW',
    'ch.flow.desc': 'Faça {n} PERFECT seguidos',
    'ch.done': 'DESAFIO COMPLETO!',
    'ch.failed': 'Quase! Fica para o próximo',
    'ch.reward': '+{n} moedas',

    'toast.km': '{n} km nesta corrida!',
    'toast.flowUp': 'FLOW ×{n}',

    'pause.title': 'PAUSA',
    'pause.resume': 'Continuar correndo',
    'pause.finish': 'Encerrar corrida',
    'pause.options': 'Opções',
    'pause.hint': 'Seu progresso já está salvo.',

    'sum.title': 'CORRIDA CONCLUÍDA',
    'sum.first': 'PRIMEIRA CORRIDA!',
    'sum.distance': 'Distância',
    'sum.time': 'Tempo',
    'sum.pace': 'Ritmo médio',
    'sum.avg': 'Velocidade média',
    'sum.top': 'Maior velocidade',
    'sum.overtakes': 'Ultrapassagens',
    'sum.flow': 'Maior FLOW',
    'sum.combo': 'Maior combo',
    'sum.perfects': 'PERFECT',
    'sum.challenges': 'Desafios',
    'sum.coins': 'Moedas ganhas',
    'sum.total': 'O seu corredor já percorreu {d}',
    'sum.record': 'RECORDE',
    'sum.paceUnit': '/km',

    'rec.title': 'RECORDES',
    'rec.profile': 'Perfil',
    'rec.totalDistance': 'Distância total',
    'rec.totalTime': 'Tempo correndo',
    'rec.runs': 'Corridas',
    'rec.overtakes': 'Ultrapassagens',
    'rec.perfects': 'Total de PERFECT',
    'rec.challenges': 'Desafios completados',
    'rec.regions': 'Regiões',
    'rec.best': 'Melhores marcas',
    'rec.topSpeed': 'Maior velocidade',
    'rec.maxFlow': 'Maior FLOW',
    'rec.maxCombo': 'Maior combo',
    'rec.longestRun': 'Maior corrida',
    'rec.mostOvertakes': 'Mais ultrapassagens numa corrida',

    'opt.title': 'OPÇÕES',
    'opt.lang': 'Idioma',
    'opt.music': 'Música',
    'opt.sfx': 'Efeitos sonoros',
    'opt.vibration': 'Vibração',
    'opt.reduceMotion': 'Reduzir movimento da câmera',
    'opt.bigUi': 'Interface maior',
    'opt.quality': 'Qualidade gráfica',
    'opt.qualityNote': 'Muda ao abrir o jogo de novo.',
    'q.auto': 'Automática',
    'q.high': 'Alta',
    'q.low': 'Leve',
    'opt.controls': 'Controles',
    'opt.controlsText': 'Toque: passada. Deslize: muda de lado e escolhe o caminho. No teclado: ESPAÇO e setas. ESC pausa.',
    'opt.reset': 'Apagar progresso',
    'opt.resetConfirm': 'Apagar todo o progresso deste aparelho? Não dá para desfazer.',
    'opt.version': 'Versão {v}',
    'opt.privacy': 'Privacidade',

    'region.welcome': 'BEM-VINDO À REGIÃO',
    'biome.cidade': 'Cidade',
    'sign.choose': 'ESCOLHA'
  };
})(window.EP);
