// English (US). [[id|WORD]] marks words that are level objects.
RULES.L10N['en-US'] = {
  name: 'English',
  strings: {
    UI_PLAY: 'PLAY',
    UI_CONTINUE: 'CONTINUE',
    UI_LEVELS: 'LEVELS',
    UI_SETTINGS: 'SETTINGS',
    UI_BACK: 'Back',
    UI_MENU: 'Menu',
    UI_LEVEL: 'LEVEL {n}',
    UI_HINT: 'HINT',
    UI_RESTART: 'RESTART',
    UI_HINTS_TITLE: 'HINTS',
    UI_HINT_MORE: 'ONE MORE HINT',
    UI_HINT_LAST: 'LAST HINT',
    UI_CLOSE: 'CLOSE',
    UI_ATTEMPTS: 'Attempts: {n}',
    UI_COMPLETED: 'COMPLETE',
    UI_LOCKED: 'Locked',
    UI_MUSIC: 'Music',
    UI_SFX: 'Sound effects',
    UI_VIBRATION: 'Vibration',
    UI_REDUCE_MOTION: 'Reduce motion',
    UI_LANGUAGE: 'Language',
    UI_RESET: 'Erase progress',
    UI_RESET_CONFIRM: 'Tap again to erase',
    UI_RESET_DONE: 'Progress erased',
    UI_TAGLINE: 'Read. Think. Doubt.',
    UI_BY: 'a game by @xadrezcomz',
    UI_MORE_GAMES: 'More games',
    UI_DEMO_END_TITLE: 'NOW YOU KNOW THE FIRST RULES',
    UI_DEMO_END_TEXT: 'MORE LEVELS COMING SOON',
    UI_SKIP: 'tap to continue',

    CHAPTER_LABEL: 'CHAPTER {n}',
    CHAPTER_1: 'LEARN THE RULES',
    CHAPTER_2: "DON'T TRUST THE RULES",
    CHAPTER_3: 'TOUCH EVERYTHING',
    CHAPTER_4: 'THINK DIFFERENT',
    CHAPTER_5: 'BREAK THE RULES',

    SUCCESS_1: 'NICE!',
    SUCCESS_2: 'YOU DID IT!',
    SUCCESS_3: 'YES!',

    FB_ALMOST: 'ALMOST!',
    FB_TRY_DIFFERENT: 'TRY SOMETHING ELSE',
    FB_HMM: 'HMMM...',
    FB_NOT_THIS_TIME: 'NOT THIS TIME',
    FB_NOFIT: "IT DOESN'T FIT...",
    FB_TOO_BIG: 'TOO BIG...',
    FB_OOPS: 'OOPS! ALMOST!',
    FB_AGAIN: 'FROM THE TOP...',

    LEVEL_001_TITLE: 'TAP THE CIRCLE',
    LEVEL_001_HINT_1: 'Sometimes the answer is exactly what it looks like.',
    LEVEL_001_HINT_2: 'The circle is right in the middle of the screen.',
    LEVEL_001_HINT_3: 'Tap the circle once.',

    LEVEL_002_TITLE: 'TAKE THE BALL TO THE BOX',
    LEVEL_002_HINT_1: 'Things can move.',
    LEVEL_002_HINT_2: "Put your finger on the ball and don't let go.",
    LEVEL_002_HINT_3: 'Drag the ball and drop it inside the box.',

    LEVEL_003_TITLE: 'OPEN THE DOOR',
    LEVEL_003_HINT_1: 'Not every door opens the same way.',
    LEVEL_003_HINT_2: "Knocking won't help. Maybe it slides...",
    LEVEL_003_HINT_3: 'Drag the door to the side.',

    LEVEL_005_TITLE: 'PUT THE CIRCLE IN THE SQUARE',
    LEVEL_005_HINT_1: 'The size of things can change.',
    LEVEL_005_HINT_2: 'The circle has to be smaller than the square.',
    LEVEL_005_HINT_3: 'Use two fingers (or the mouse wheel) to shrink the circle. Then drag it.',

    LEVEL_009_TITLE: 'PUT [[w_all|EVERYTHING]] IN THE BOX',
    LEVEL_009_HINT_1: 'Everything means everything.',
    LEVEL_009_HINT_2: 'Look at the instruction again.',
    LEVEL_009_HINT_3: 'Drag the word EVERYTHING into the box.',

    LEVEL_010_TITLE: "DON'T TOUCH ANYTHING",
    LEVEL_010_HINT_1: 'Sometimes the best move is not to move.',
    LEVEL_010_HINT_2: 'Take the instruction literally.',
    LEVEL_010_HINT_3: "Close this hint and don't touch the screen for 3 seconds.",

    LEVEL_011_TITLE: 'GET THE KEY',
    LEVEL_011_HINT_1: "If you can't go to it...",
    LEVEL_011_HINT_2: 'The key only runs away from Ruli.',
    LEVEL_011_HINT_3: 'Drag the key to Ruli.',

    LEVEL_012_TITLE: 'REACH THE DOOR',
    LEVEL_012_HINT_1: "The path doesn't have to be yours.",
    LEVEL_012_HINT_2: "Ruli can't jump. But something else here moves.",
    LEVEL_012_HINT_3: 'Drag the door to Ruli.',

    LEVEL_016_TITLE: 'PUT THE BALL IN THE BOX',
    LEVEL_016_HINT_1: "If the ball won't shrink...",
    LEVEL_016_HINT_2: 'Maybe the problem is the box.',
    LEVEL_016_HINT_3: 'Use two fingers (or the mouse wheel) to grow the box. Then drag the ball.',

    LEVEL_020_TITLE: 'WAIT.',
    LEVEL_020_HINT_1: 'Patience is a rule too.',
    LEVEL_020_HINT_2: 'Every touch restarts the count.',
    LEVEL_020_HINT_3: "Close this hint and don't touch anything for 5 seconds."
  }
};
