// English (US). [[id|WORD]] marks words that are level objects.
RULES.L10N['en-US'] = {
  name: 'English',
  strings: {
    UI_PLAY: 'PLAY',
    UI_CONTINUE: 'CONTINUE',
    UI_LEVELS: 'LEVELS',
    UI_SETTINGS: 'SETTINGS',
    UI_BACK: 'Back',
    UI_MENU: 'Menu',
    UI_LEVEL: 'LEVEL {n}',
    UI_HINT: 'HINT',
    UI_RESTART: 'RESTART',
    UI_HINTS_TITLE: 'HINTS',
    UI_HINT_MORE: 'ONE MORE HINT',
    UI_HINT_LAST: 'LAST HINT',
    UI_CLOSE: 'CLOSE',
    UI_ATTEMPTS: 'Attempts: {n}',
    UI_COMPLETED: 'COMPLETE',
    UI_LOCKED: 'Locked',
    UI_MUSIC: 'Music',
    UI_SFX: 'Sound effects',
    UI_VIBRATION: 'Vibration',
    UI_REDUCE_MOTION: 'Reduce motion',
    UI_LANGUAGE: 'Language',
    UI_RESET: 'Erase progress',
    UI_RESET_CONFIRM: 'Tap again to erase',
    UI_RESET_DONE: 'Progress erased',
    UI_TAGLINE: 'Read. Think. Doubt.',
    UI_BY: 'a game by @xadrezcomz',
    UI_MORE_GAMES: 'More games',
    UI_DEMO_END_TITLE: 'NOW YOU KNOW THE FIRST RULES',
    UI_DEMO_END_TEXT: 'MORE LEVELS COMING SOON',
    UI_SKIP: 'tap to continue',

    CHAPTER_LABEL: 'CHAPTER {n}',
    CHAPTER_1: 'LEARN THE RULES',
    CHAPTER_2: "DON'T TRUST THE RULES",
    CHAPTER_3: 'TOUCH EVERYTHING',
    CHAPTER_4: 'THINK DIFFERENT',
    CHAPTER_5: 'BREAK THE RULES',

    SUCCESS_1: 'NICE!',
    SUCCESS_2: 'YOU DID IT!',
    SUCCESS_3: 'YES!',

    FB_ALMOST: 'ALMOST!',
    FB_TRY_DIFFERENT: 'TRY SOMETHING ELSE',
    FB_HMM: 'HMMM...',
    FB_NOT_THIS_TIME: 'NOT THIS TIME',
    FB_NOFIT: "IT DOESN'T FIT...",
    FB_TOO_BIG: 'TOO BIG...',
    FB_OOPS: 'OOPS! ALMOST!',
    FB_AGAIN: 'FROM THE TOP...',

    LEVEL_001_TITLE: 'TAP THE CIRCLE',
    LEVEL_001_HINT_1: 'Sometimes the answer is exactly what it looks like.',
    LEVEL_001_HINT_2: 'The circle is right in the middle of the screen.',
    LEVEL_001_HINT_3: 'Tap the circle once.',

    LEVEL_002_TITLE: 'TAKE THE BALL TO THE BOX',
    LEVEL_002_HINT_1: 'Things can move.',
    LEVEL_002_HINT_2: "Put your finger on the ball and don't let go.",
    LEVEL_002_HINT_3: 'Drag the ball and drop it inside the box.',

    LEVEL_003_TITLE: 'OPEN THE DOOR',
    LEVEL_003_HINT_1: 'Not every door opens the same way.',
    LEVEL_003_HINT_2: "Knocking won't help. Maybe it slides...",
    LEVEL_003_HINT_3: 'Drag the door to the side.',

    LEVEL_005_TITLE: 'PUT THE CIRCLE IN THE SQUARE',
    LEVEL_005_HINT_1: 'The size of things can change.',
    LEVEL_005_HINT_2: 'The circle has to be smaller than the square.',
    LEVEL_005_HINT_3: 'Use two fingers (or the mouse wheel) to shrink the circle. Then drag it.',

    LEVEL_009_TITLE: 'PUT [[w_all|EVERYTHING]] IN THE BOX',
    LEVEL_009_HINT_1: 'Everything means everything.',
    LEVEL_009_HINT_2: 'Look at the instruction again.',
    LEVEL_009_HINT_3: 'Drag the word EVERYTHING into the box.',

    LEVEL_010_TITLE: "DON'T TOUCH ANYTHING",
    LEVEL_010_HINT_1: 'Sometimes the best move is not to move.',
    LEVEL_010_HINT_2: 'Take the instruction literally.',
    LEVEL_010_HINT_3: "Close this hint and don't touch the screen for 3 seconds.",

    LEVEL_011_TITLE: 'GET THE KEY',
    LEVEL_011_HINT_1: "If you can't go to it...",
    LEVEL_011_HINT_2: 'The key only runs away from Ruli.',
    LEVEL_011_HINT_3: 'Drag the key to Ruli.',

    LEVEL_012_TITLE: 'REACH THE DOOR',
    LEVEL_012_HINT_1: "The path doesn't have to be yours.",
    LEVEL_012_HINT_2: "Ruli can't jump. But something else here moves.",
    LEVEL_012_HINT_3: 'Drag the door to Ruli.',

    LEVEL_016_TITLE: 'PUT THE BALL IN THE BOX',
    LEVEL_016_HINT_1: "If the ball won't shrink...",
    LEVEL_016_HINT_2: 'Maybe the problem is the box.',
    LEVEL_016_HINT_3: 'Use two fingers (or the mouse wheel) to grow the box. Then drag the ball.',

    LEVEL_020_TITLE: 'WAIT.',
    LEVEL_020_HINT_1: 'Patience is a rule too.',
    LEVEL_020_HINT_2: 'Every touch restarts the count.',
    LEVEL_020_HINT_3: "Close this hint and don't touch anything for 5 seconds.",
    FB_PRESSED: 'YOU PRESSED IT!',
    FB_DONT_MOVE: 'DON\'T MOVE RULI!',
    FB_BIGGER: 'THERE\'S A BIGGER ONE...',
    FB_SAME: 'THAT ONE IS THE SAME...',
    FB_NOT_BLUE: 'THAT\'S NOT BLUE',
    FB_SERIOUS: 'RULI IS STILL SERIOUS',
    FB_OLDEST: 'THE OLDEST ONE WENT OUT',
    FB_NOT_UP: 'IT WON\'T GO UP...',

    LEVEL_004_TITLE: 'TURN ON THE LIGHT',
    LEVEL_004_HINT_1: 'Every bulb has a way to turn on.',
    LEVEL_004_HINT_2: 'The bulb won\'t turn on by itself.',
    LEVEL_004_HINT_3: 'Tap the switch.',

    LEVEL_006_TITLE: 'FIND THE STAR',
    LEVEL_006_HINT_1: 'Not everything is in plain sight.',
    LEVEL_006_HINT_2: 'One of the circles isn\'t stuck.',
    LEVEL_006_HINT_3: 'Drag the red circle and tap the star.',

    LEVEL_007_TITLE: 'MAKE THEM MEET',
    LEVEL_007_HINT_1: 'It takes two to meet.',
    LEVEL_007_HINT_2: 'Neither can go all the way alone.',
    LEVEL_007_HINT_3: 'Bring each one to the middle.',

    LEVEL_008_TITLE: 'FILL THE GLASS',
    LEVEL_008_HINT_1: 'Water won\'t jump out of the jug.',
    LEVEL_008_HINT_2: 'Jugs need to tilt.',
    LEVEL_008_HINT_3: 'Hold the jug just above the glass until it fills.',

    LEVEL_013_TITLE: 'L[[w_o|O]]OK FOR THE BIGGEST CIRCLE',
    LEVEL_013_HINT_1: 'The biggest one may not be among the things.',
    LEVEL_013_HINT_2: 'A letter is round too.',
    LEVEL_013_HINT_3: 'Tap the big O in the instruction.',

    LEVEL_014_TITLE: 'MAKE THE SUN APPEAR',
    LEVEL_014_HINT_1: 'The sun never left.',
    LEVEL_014_HINT_2: 'Something is in front of it.',
    LEVEL_014_HINT_3: 'Drag the cloud away from the sun.',

    LEVEL_015_TITLE: 'DON\'T PRESS THE BUTTON',
    LEVEL_015_HINT_1: 'You can move a button without pressing it.',
    LEVEL_015_HINT_2: 'What could be under it?',
    LEVEL_015_HINT_3: 'Drag the button aside and tap what shows up.',

    LEVEL_017_TITLE: 'FIND THE ODD ONE',
    LEVEL_017_HINT_1: 'Watch calmly.',
    LEVEL_017_HINT_2: 'They all move together... almost all.',
    LEVEL_017_HINT_3: 'One grows when the others shrink. Tap it.',

    LEVEL_018_TITLE: 'TURN ON ALL THE LIGHTS',
    LEVEL_018_HINT_1: 'Only two can stay on. The oldest one always goes out.',
    LEVEL_018_HINT_2: 'What if two were turned on at exactly the same time? The switches can move, too.',
    LEVEL_018_HINT_3: 'Drag one switch on top of another and tap the stack: both turn on together. Then turn on the third. (With two fingers you can also tap two at once.)',

    LEVEL_019_TITLE: 'DON\'T LET THE BALL FALL',
    LEVEL_019_HINT_1: 'The ball won\'t float forever.',
    LEVEL_019_HINT_2: 'It needs something under it.',
    LEVEL_019_HINT_3: 'Drag the platform under the ball before it falls.',

    LEVEL_021_TITLE: 'FIND THE EXIT',
    LEVEL_021_HINT_1: 'Walls are things too.',
    LEVEL_021_HINT_2: 'A wall can hide what is behind it.',
    LEVEL_021_HINT_3: 'Drag the wall and tap the door.',

    LEVEL_022_TITLE: 'MAKE 2 + 2 = 5',
    LEVEL_022_HINT_1: 'Math doesn\'t change. Numbers do.',
    LEVEL_022_HINT_2: 'One stick looks a bit loose.',
    LEVEL_022_HINT_3: 'Move the crooked stick of the second 2 to the right: the 2 becomes a 3.',

    LEVEL_023_TITLE: 'PUT THE FISH IN THE WATER',
    LEVEL_023_HINT_1: 'This glass is too small for a fish.',
    LEVEL_023_HINT_2: 'Remember the box and the ball?',
    LEVEL_023_HINT_3: 'Grow the glass with two fingers (or the mouse wheel), then put the fish in.',

    LEVEL_024_TITLE: 'FIND THE [[w_blue|BLUE]]',
    LEVEL_024_HINT_1: 'Look everywhere, even outside the scene.',
    LEVEL_024_HINT_2: 'No object is blue.',
    LEVEL_024_HINT_3: 'Tap the word BLUE.',

    LEVEL_025_TITLE: 'MAKE RULI SMILE',
    LEVEL_025_HINT_1: 'Ruli is serious, but has a weak spot.',
    LEVEL_025_HINT_2: 'Tickles!',
    LEVEL_025_HINT_3: 'Rub Ruli fast, side to side (with your finger or the feather).',

    LEVEL_026_TITLE: 'SORT FROM [[w_min|SMALLEST]] TO [[w_max|BIGGEST]]',
    LEVEL_026_HINT_1: 'Count the spots.',
    LEVEL_026_HINT_2: 'Five spots, three circles. What is missing?',
    LEVEL_026_HINT_3: 'Put SMALLEST in the first spot, the circles in order, and BIGGEST in the last.',

    LEVEL_027_TITLE: '[[w_open|OPEN]] THE BOX',
    LEVEL_027_HINT_1: 'This box has no lid and no lock.',
    LEVEL_027_HINT_2: 'You need a tool. It\'s written down.',
    LEVEL_027_HINT_3: 'Drag the word OPEN onto the box.',

    LEVEL_028_TITLE: 'TAKE THE STAR [[w_up|UP]]',
    LEVEL_028_HINT_1: 'The star is too heavy.',
    LEVEL_028_HINT_2: 'If it won\'t go up...',
    LEVEL_028_HINT_3: 'Drag the word UP to the star.',

    LEVEL_029_TITLE: 'MAKE IT RAIN',
    LEVEL_029_HINT_1: 'Clouds need to gather water.',
    LEVEL_029_HINT_2: 'One tap is not enough.',
    LEVEL_029_HINT_3: 'Rub the cloud until it gets really dark.',

    LEVEL_030_TITLE: 'DON\'T MOVE RULI',
    LEVEL_030_HINT_1: 'If Ruli can\'t go to the door...',
    LEVEL_030_HINT_2: 'The ground is an object too.',
    LEVEL_030_HINT_3: 'Drag the ground to the left until the door reaches Ruli.',
    FB_ONLY_TWO: 'ONLY TWO...',
    FB_THIRSTY: 'IT\'S THIRSTY...',
    FB_GLUG: 'GLUG GLUG!',
    FB_NOTHING: 'NOTHING HERE...',
    FB_HEAVY: 'TOO HEAVY...',
    FB_NOT_SAME: 'THEY\'RE NOT THE SAME...',
    FB_TICTAC: 'TICK... TOCK...',
    FB_TIRED: 'RULI IS TIRED',
    FB_GREEN: 'IT\'S GREEN!',
    FB_FIXED: 'THESE DON\'T MOVE',
    FB_WRONG: 'WRONG...',
    FB_LOCKED: 'LOCKED',
    FB_UNLOCKED: 'CLICK!',
    FB_ORDER: 'OUT OF ORDER',
    FB_AGAIN_WATCH: 'WATCH AGAIN...',
    FINALE_1: 'NOW YOU KNOW THE',
    FINALE_WORD: 'RULES.',
    FINALE_2: '...OR NOT. 😉',
    CHAPTER_6: 'THE SCREEN PLAYS TOO',
    CHAPTER_7: 'WORDS CHANGE EVERYTHING',
    CHAPTER_8: 'TOY PHYSICS',
    CHAPTER_9: 'LOOK AGAIN',
    CHAPTER_10: 'OUTSIDE THE BOX',
    LEVEL_046_WORD: 'NOTHING',
    LEVEL_048_Q: '2 + 3 = ?',
    LEVEL_049_SIGN: 'DON\'T MOVE THE DOOR',

    LEVEL_031_TITLE: 'FIND 3 TRIANGLES',
    LEVEL_031_HINT_1: 'Two is easy. What about the third?',
    LEVEL_031_HINT_2: 'Two halves make a whole.',
    LEVEL_031_HINT_3: 'Put the two purple halves together.',

    LEVEL_032_TITLE: 'CROSS THE BRIDGE',
    LEVEL_032_HINT_1: 'This bridge doesn\'t reach the other side.',
    LEVEL_032_HINT_2: 'Bridges can grow too... sideways.',
    LEVEL_032_HINT_3: 'Stretch the bridge with two fingers (or the mouse wheel), then walk Ruli across.',

    LEVEL_033_TITLE: 'PUT 5 BALLS IN THE BOX',
    LEVEL_033_HINT_1: 'Count the balls.',
    LEVEL_033_HINT_2: 'There are only four. Could one become two?',
    LEVEL_033_HINT_3: 'Stretch the green ball with two fingers (or the mouse wheel) until it splits.',

    LEVEL_034_TITLE: 'MAKE [[w_all|EVERYTHING]] SMALL',
    LEVEL_034_HINT_1: 'Everything, really.',
    LEVEL_034_HINT_2: 'There\'s still something big on the screen.',
    LEVEL_034_HINT_3: 'Shrink the word EVERYTHING too, with two fingers (or the mouse wheel).',

    LEVEL_035_TITLE: 'MAKE THE PLANT GROW',
    LEVEL_035_HINT_1: 'Plants need two things.',
    LEVEL_035_HINT_2: 'Order matters.',
    LEVEL_035_HINT_3: 'Bring the watering can to the plant first. Then the sun.',

    LEVEL_036_TITLE: '[[w_all|FIND WHAT IS HIDDEN]]',
    LEVEL_036_HINT_1: 'It\'s not behind the boxes.',
    LEVEL_036_HINT_2: 'Something is in front of everything.',
    LEVEL_036_HINT_3: 'Drag the instruction itself and tap what appears.',

    LEVEL_037_TITLE: 'PUT THE MOON IN THE SKY',
    LEVEL_037_HINT_1: 'The moon won\'t go up.',
    LEVEL_037_HINT_2: 'If it can\'t reach the sky...',
    LEVEL_037_HINT_3: 'Drag the sky down until the moon is inside it.',

    LEVEL_038_TITLE: 'JOIN THE SAME ONES',
    LEVEL_038_HINT_1: 'They are the same in everything but one thing.',
    LEVEL_038_HINT_2: 'Same means same size.',
    LEVEL_038_HINT_3: 'Make both circles the same size (two fingers or mouse wheel) and join them.',

    LEVEL_039_TITLE: 'MAKE THE CLOCK GO FASTER',
    LEVEL_039_HINT_1: 'Clocks don\'t like to hurry.',
    LEVEL_039_HINT_2: 'But hands can take a push.',
    LEVEL_039_HINT_3: 'Spin the long hand with your finger, two full turns.',

    LEVEL_040_TITLE: 'REACH THE [[w_final|END]]',
    LEVEL_040_HINT_1: 'The path is too long for Ruli.',
    LEVEL_040_HINT_2: 'Maybe the end can come to him.',
    LEVEL_040_HINT_3: 'Drag the word END to Ruli.',

    LEVEL_041_TITLE: 'DON\'T TOUCH THE GREEN',
    LEVEL_041_HINT_1: 'Green is the problem.',
    LEVEL_041_HINT_2: 'What if it was not green anymore?',
    LEVEL_041_HINT_3: 'Bring the blue paint to the green circle, then tap it.',

    LEVEL_042_TITLE: 'PUT THE STAR OUTSIDE THE BOX',
    LEVEL_042_HINT_1: 'The box won\'t open.',
    LEVEL_042_HINT_2: 'Inside and outside depend on size.',
    LEVEL_042_HINT_3: 'Grow the star (two fingers or mouse wheel) until the box is inside it.',

    LEVEL_043_TITLE: 'MAKE BOTH SIDES EQUAL',
    LEVEL_043_HINT_1: 'The circles don\'t move.',
    LEVEL_043_HINT_2: 'What decides the sides?',
    LEVEL_043_HINT_3: 'Drag the line until there are three circles on each side.',

    LEVEL_044_TITLE: 'FIND THE DOOR',
    LEVEL_044_HINT_1: 'There is no door. Yet.',
    LEVEL_044_HINT_2: 'Shapes can build things.',
    LEVEL_044_HINT_3: 'Bring the purple rectangle to the outline and the yellow dot to the knob.',

    LEVEL_045_TITLE: 'HELP RULI REACH HIGHER',
    LEVEL_045_HINT_1: 'The steps are too small.',
    LEVEL_045_HINT_2: 'Boxes can become stairs.',
    LEVEL_045_HINT_3: 'Stack the three boxes under the star and put Ruli on top.',

    LEVEL_046_TITLE: 'LEAVE NOTHING ON THE FLOOR',
    LEVEL_046_HINT_1: 'Look closely at the floor.',
    LEVEL_046_HINT_2: 'There\'s a word hidden down there.',
    LEVEL_046_HINT_3: 'Lift the little word NOTHING too.',

    LEVEL_047_TITLE: 'TURN DAY INTO NIGHT',
    LEVEL_047_HINT_1: 'When does night come?',
    LEVEL_047_HINT_2: 'The sun has to leave.',
    LEVEL_047_HINT_3: 'Drag the sun below the horizon.',

    LEVEL_048_TITLE: 'FIND THE [[w_ans|ANSWER]]',
    LEVEL_048_HINT_1: 'None of these numbers fit.',
    LEVEL_048_HINT_2: 'The answer is written down.',
    LEVEL_048_HINT_3: 'Drag the word ANSWER into the empty space.',

    LEVEL_049_TITLE: 'BREAK THE RULE',
    LEVEL_049_HINT_1: 'Read the sign.',
    LEVEL_049_HINT_2: 'The instruction says to break it.',
    LEVEL_049_HINT_3: 'Move the door.',

    LEVEL_050_TITLE: 'YOU ALREADY KNOW WHAT TO DO',
    LEVEL_050_HINT_1: 'Everything you learned counts here.',
    LEVEL_050_HINT_2: 'The door is locked. What opens doors?',
    LEVEL_050_HINT_3: 'Move the box, bring the key to the door, then bring Ruli to it.',
    FB_HELP: 'NEED HELP?',
    FB_READING: 'I\'M READING...',
    FB_SEEN: 'YOU CAN STILL SEE RULI',
    FB_NOT_ALLOWED: 'NOT ALLOWED!',
    FB_NOT_SEVEN: 'THAT\'S NOT 7',
    FB_PAINTING: 'IT\'S JUST A PAINTING',
    FB_SPLASH: 'SPLASH!',
    FB_ALREADY_DAY: 'IT\'S ALREADY DAY...',
    FB_ROUND: 'THAT\'S ROUND',
    FB_BACKWARDS: 'HERE THE DOOR OPENS THE KEY...',
    FB_MAKES_SENSE: 'NOW IT MAKES SENSE!',
    LEVEL_054_LABEL: '[[w_fase|LEVEL]] 54',
    LEVEL_057_LABEL: 'LEVEL 5[[w_seven|7]]',
    LEVEL_059_LABEL: 'LEVEL [[w_five|5]]9',
    LEVEL_061_L1: 'C',
    LEVEL_061_L2: 'A',
    LEVEL_061_L3: 'T',
    LEVEL_061_L4: '',
    LEVEL_061_NEW: 'B',
    LEVEL_061_DECOY: 'R',
    LEVEL_066_A: 'S',
    LEVEL_066_B: 'U',
    LEVEL_066_C: 'N',
    LEVEL_066_X1: 'O',
    LEVEL_066_X2: 'R',

    LEVEL_051_TITLE: 'ASK FOR HELP',
    LEVEL_051_HINT_1: 'That\'s it. You asked for help. Close this window.',
    LEVEL_051_HINT_2: 'That was really all.',
    LEVEL_051_HINT_3: 'Asking for help is a move too.',

    LEVEL_052_TITLE: 'TRY AGAIN',
    LEVEL_052_HINT_1: 'Sometimes it doesn\'t work the first time.',
    LEVEL_052_HINT_2: 'The instruction says exactly what to do.',
    LEVEL_052_HINT_3: 'Tap RESTART.',

    LEVEL_053_TITLE: 'DON\'T READ THIS',
    LEVEL_053_HINT_1: 'Hard not to read, right?',
    LEVEL_053_HINT_2: 'What if the sentence disappeared from view?',
    LEVEL_053_HINT_3: 'Drag the paper over the instruction.',

    LEVEL_054_TITLE: 'PUT THE LEVEL IN THE BOX',
    LEVEL_054_HINT_1: 'The star is not the level.',
    LEVEL_054_HINT_2: 'Look at the top of the screen.',
    LEVEL_054_HINT_3: 'Drag the word LEVEL, up there, into the box.',

    LEVEL_055_TITLE: 'HIDE RULI',
    LEVEL_055_HINT_1: 'Behind the tree he still shows.',
    LEVEL_055_HINT_2: 'Something big on the screen is not part of the scene.',
    LEVEL_055_HINT_3: 'Drag Ruli behind the instruction.',

    LEVEL_056_TITLE: '[[w_not|DON\'T]] TOUCH THE STAR',
    LEVEL_056_HINT_1: 'The sentence says not to touch.',
    LEVEL_056_HINT_2: 'What if the sentence changed?',
    LEVEL_056_HINT_3: 'Take the word DON\'T out of the sentence, then tap the star.',

    LEVEL_057_TITLE: 'FIND THE 7',
    LEVEL_057_HINT_1: 'Count the cards.',
    LEVEL_057_HINT_2: 'No card is a 7. But there is a 7 on the screen.',
    LEVEL_057_HINT_3: 'Tap the 7 in "LEVEL 57", up top.',

    LEVEL_058_TITLE: 'PUT THE [[w_g|GIANT]] IN THE BOX',
    LEVEL_058_HINT_1: 'The ball is not the giant.',
    LEVEL_058_HINT_2: 'The giant is too big for the box.',
    LEVEL_058_HINT_3: 'Shrink the word GIANT (two fingers or mouse wheel) and drag it into the box.',

    LEVEL_059_TITLE: 'TAP FROM 1 TO 5',
    LEVEL_059_HINT_1: 'Look for the 5.',
    LEVEL_059_HINT_2: 'It\'s not among the cards.',
    LEVEL_059_HINT_3: 'Tap 1, 2, 3, 4, then the 5 in "LEVEL 59".',

    LEVEL_060_TITLE: 'TAKE [[w_ruli|RULI]] TO THE DOOR',
    LEVEL_060_HINT_1: 'This Ruli doesn\'t move.',
    LEVEL_060_HINT_2: 'He\'s just a painting on the wall.',
    LEVEL_060_HINT_3: 'Drag the word RULI to the door.',

    LEVEL_061_TITLE: 'TURN THE CAT INTO A BAT',
    LEVEL_061_HINT_1: 'One letter makes all the difference.',
    LEVEL_061_HINT_2: 'CAT and BAT only change at the start.',
    LEVEL_061_HINT_3: 'Drop the letter B on the C.',

    LEVEL_062_TITLE: 'USE THE [[w_bridge|BRIDGE]]',
    LEVEL_062_HINT_1: 'There is no bridge.',
    LEVEL_062_HINT_2: 'The bridge is written down.',
    LEVEL_062_HINT_3: 'Drag the word BRIDGE onto the river, then walk Ruli across.',

    LEVEL_063_TITLE: 'PAINT THE SKY [[w_blue|BLUE]]',
    LEVEL_063_HINT_1: 'Red and yellow won\'t make blue here.',
    LEVEL_063_HINT_2: 'Where else is there blue?',
    LEVEL_063_HINT_3: 'Drag the word BLUE onto the sky.',

    LEVEL_064_TITLE: 'MAKE THE [[w_small|SMALL]] ONE BIG',
    LEVEL_064_HINT_1: 'The ball won\'t grow.',
    LEVEL_064_HINT_2: 'Small what?',
    LEVEL_064_HINT_3: 'Grow the word SMALL with two fingers (or the mouse wheel).',

    LEVEL_065_TITLE: 'MAKE 1 + 1 = 1',
    LEVEL_065_HINT_1: 'One plus one isn\'t always two.',
    LEVEL_065_HINT_2: 'Water drops like to join.',
    LEVEL_065_HINT_3: 'Put one drop on the other.',

    LEVEL_066_TITLE: 'WRITE THE NAME OF THIS',
    LEVEL_066_HINT_1: 'Look at the drawing.',
    LEVEL_066_HINT_2: 'Three letters are enough.',
    LEVEL_066_HINT_3: 'Spell SUN in the three spaces.',

    LEVEL_067_TITLE: 'ERASE THE [[w_x|X]]',
    LEVEL_067_HINT_1: 'Erasers work by rubbing.',
    LEVEL_067_HINT_2: 'There is more than one X on the screen.',
    LEVEL_067_HINT_3: 'Rub the big X and also the X in the instruction.',

    LEVEL_068_TITLE: 'SWAP THE [[w_day|DAY]] FOR THE [[w_night|NIGHT]]',
    LEVEL_068_HINT_1: 'Day is already here.',
    LEVEL_068_HINT_2: 'Night is written down.',
    LEVEL_068_HINT_3: 'Bring the word NIGHT to the sun.',

    LEVEL_069_TITLE: '[[w_all|TAP WHAT IS NOT ROUND]]',
    LEVEL_069_HINT_1: 'Everything in the scene is round.',
    LEVEL_069_HINT_2: 'But not everything on the screen.',
    LEVEL_069_HINT_3: 'Tap the instruction itself.',

    LEVEL_070_TITLE: 'THE [[w_a|DOOR]] OPENS THE [[w_b|KEY]]',
    LEVEL_070_HINT_1: 'That sentence is odd.',
    LEVEL_070_HINT_2: 'What if the words switched places?',
    LEVEL_070_HINT_3: 'Drop DOOR onto KEY. Then bring the key to the door.'
  }
};
