// English (US). [[id|WORD]] marks words that are level objects.
RULES.L10N['en-US'] = {
  name: 'English',
  strings: {
    UI_PLAY: 'PLAY',
    UI_CONTINUE: 'CONTINUE',
    UI_LEVELS: 'LEVELS',
    UI_SETTINGS: 'SETTINGS',
    UI_BACK: 'Back',
    UI_MENU: 'Menu',
    UI_LEVEL: 'LEVEL {n}',
    UI_HINT: 'HINT',
    UI_RESTART: 'RESTART',
    UI_HINTS_TITLE: 'HINTS',
    UI_HINT_MORE: 'ONE MORE HINT',
    UI_HINT_LAST: 'LAST HINT',
    UI_CLOSE: 'CLOSE',
    UI_ATTEMPTS: 'Attempts: {n}',
    UI_COMPLETED: 'COMPLETE',
    UI_LOCKED: 'Locked',
    UI_MUSIC: 'Music',
    UI_SFX: 'Sound effects',
    UI_VIBRATION: 'Vibration',
    UI_REDUCE_MOTION: 'Reduce motion',
    UI_LANGUAGE: 'Language',
    UI_RESET: 'Erase progress',
    UI_RESET_CONFIRM: 'Tap again to erase',
    UI_RESET_DONE: 'Progress erased',
    UI_TAGLINE: 'Read. Think. Doubt.',
    UI_BY: 'a game by @xadrezcomz',
    UI_MORE_GAMES: 'More games',
    UI_DEMO_END_TITLE: 'NOW YOU KNOW THE FIRST RULES',
    UI_DEMO_END_TEXT: 'MORE LEVELS COMING SOON',
    UI_SKIP: 'tap to continue',

    CHAPTER_LABEL: 'CHAPTER {n}',
    CHAPTER_1: 'LEARN THE RULES',
    CHAPTER_2: "DON'T TRUST THE RULES",
    CHAPTER_3: 'TOUCH EVERYTHING',
    CHAPTER_4: 'THINK DIFFERENT',
    CHAPTER_5: 'BREAK THE RULES',

    SUCCESS_1: 'NICE!',
    SUCCESS_2: 'YOU DID IT!',
    SUCCESS_3: 'YES!',

    FB_ALMOST: 'ALMOST!',
    FB_TRY_DIFFERENT: 'TRY SOMETHING ELSE',
    FB_HMM: 'HMMM...',
    FB_NOT_THIS_TIME: 'NOT THIS TIME',
    FB_NOFIT: "IT DOESN'T FIT...",
    FB_TOO_BIG: 'TOO BIG...',
    FB_OOPS: 'OOPS! ALMOST!',
    FB_AGAIN: 'FROM THE TOP...',

    LEVEL_001_TITLE: 'TAP THE CIRCLE',
    LEVEL_001_HINT_1: 'Sometimes the answer is exactly what it looks like.',
    LEVEL_001_HINT_2: 'The circle is right in the middle of the screen.',
    LEVEL_001_HINT_3: 'Tap the circle once.',

    LEVEL_002_TITLE: 'TAKE THE BALL TO THE BOX',
    LEVEL_002_HINT_1: 'Things can move.',
    LEVEL_002_HINT_2: "Put your finger on the ball and don't let go.",
    LEVEL_002_HINT_3: 'Drag the ball and drop it inside the box.',

    LEVEL_003_TITLE: 'OPEN THE DOOR',
    LEVEL_003_HINT_1: 'Not every door opens the same way.',
    LEVEL_003_HINT_2: "Knocking won't help. Maybe it slides...",
    LEVEL_003_HINT_3: 'Drag the door to the side.',

    LEVEL_005_TITLE: 'PUT THE CIRCLE IN THE SQUARE',
    LEVEL_005_HINT_1: 'The size of things can change.',
    LEVEL_005_HINT_2: 'The circle has to be smaller than the square.',
    LEVEL_005_HINT_3: 'Use two fingers (or the mouse wheel) to shrink the circle. Then drag it.',

    LEVEL_009_TITLE: 'PUT [[w_all|EVERYTHING]] IN THE BOX',
    LEVEL_009_HINT_1: 'Everything means everything.',
    LEVEL_009_HINT_2: 'Look at the instruction again.',
    LEVEL_009_HINT_3: 'Drag the word EVERYTHING into the box.',

    LEVEL_010_TITLE: "DON'T TOUCH ANYTHING",
    LEVEL_010_HINT_1: 'Sometimes the best move is not to move.',
    LEVEL_010_HINT_2: 'Take the instruction literally.',
    LEVEL_010_HINT_3: "Close this hint and don't touch the screen for 3 seconds.",

    LEVEL_011_TITLE: 'GET THE KEY',
    LEVEL_011_HINT_1: "If you can't go to it...",
    LEVEL_011_HINT_2: 'The key only runs away from Ruli.',
    LEVEL_011_HINT_3: 'Drag the key to Ruli.',

    LEVEL_012_TITLE: 'REACH THE DOOR',
    LEVEL_012_HINT_1: "The path doesn't have to be yours.",
    LEVEL_012_HINT_2: "Ruli can't jump. But something else here moves.",
    LEVEL_012_HINT_3: 'Drag the door to Ruli.',

    LEVEL_016_TITLE: 'PUT THE BALL IN THE BOX',
    LEVEL_016_HINT_1: "If the ball won't shrink...",
    LEVEL_016_HINT_2: 'Maybe the problem is the box.',
    LEVEL_016_HINT_3: 'Use two fingers (or the mouse wheel) to grow the box. Then drag the ball.',

    LEVEL_020_TITLE: 'WAIT.',
    LEVEL_020_HINT_1: 'Patience is a rule too.',
    LEVEL_020_HINT_2: 'Every touch restarts the count.',
    LEVEL_020_HINT_3: "Close this hint and don't touch anything for 5 seconds.",
    FB_PRESSED: 'YOU PRESSED IT!',
    FB_DONT_MOVE: 'DON\'T MOVE RULI!',
    FB_BIGGER: 'THERE\'S A BIGGER ONE...',
    FB_SAME: 'THAT ONE IS THE SAME...',
    FB_NOT_BLUE: 'THAT\'S NOT BLUE',
    FB_SERIOUS: 'RULI IS STILL SERIOUS',
    FB_OLDEST: 'THE OLDEST ONE WENT OUT',
    FB_NOT_UP: 'IT WON\'T GO UP...',

    LEVEL_004_TITLE: 'TURN ON THE LIGHT',
    LEVEL_004_HINT_1: 'Every bulb has a way to turn on.',
    LEVEL_004_HINT_2: 'The bulb won\'t turn on by itself.',
    LEVEL_004_HINT_3: 'Tap the switch.',

    LEVEL_006_TITLE: 'FIND THE STAR',
    LEVEL_006_HINT_1: 'Not everything is in plain sight.',
    LEVEL_006_HINT_2: 'One of the circles isn\'t stuck.',
    LEVEL_006_HINT_3: 'Drag the red circle and tap the star.',

    LEVEL_007_TITLE: 'MAKE THEM MEET',
    LEVEL_007_HINT_1: 'It takes two to meet.',
    LEVEL_007_HINT_2: 'Neither can go all the way alone.',
    LEVEL_007_HINT_3: 'Bring each one to the middle.',

    LEVEL_008_TITLE: 'FILL THE GLASS',
    LEVEL_008_HINT_1: 'Water won\'t jump out of the jug.',
    LEVEL_008_HINT_2: 'Jugs need to tilt.',
    LEVEL_008_HINT_3: 'Hold the jug just above the glass until it fills.',

    LEVEL_013_TITLE: 'L[[w_o|O]]OK FOR THE BIGGEST CIRCLE',
    LEVEL_013_HINT_1: 'The biggest one may not be among the things.',
    LEVEL_013_HINT_2: 'A letter is round too.',
    LEVEL_013_HINT_3: 'Tap the big O in the instruction.',

    LEVEL_014_TITLE: 'MAKE THE SUN APPEAR',
    LEVEL_014_HINT_1: 'The sun never left.',
    LEVEL_014_HINT_2: 'Something is in front of it.',
    LEVEL_014_HINT_3: 'Drag the cloud away from the sun.',

    LEVEL_015_TITLE: 'DON\'T PRESS THE BUTTON',
    LEVEL_015_HINT_1: 'You can move a button without pressing it.',
    LEVEL_015_HINT_2: 'What could be under it?',
    LEVEL_015_HINT_3: 'Drag the button aside and tap what shows up.',

    LEVEL_017_TITLE: 'FIND THE ODD ONE',
    LEVEL_017_HINT_1: 'Watch calmly.',
    LEVEL_017_HINT_2: 'They all move together... almost all.',
    LEVEL_017_HINT_3: 'One grows when the others shrink. Tap it.',

    LEVEL_018_TITLE: 'TURN ON ALL THE LIGHTS',
    LEVEL_018_HINT_1: 'Only two can stay on. The oldest one always goes out.',
    LEVEL_018_HINT_2: 'What if two were turned on at exactly the same time? The switches can move, too.',
    LEVEL_018_HINT_3: 'Drag one switch on top of another and tap the stack: both turn on together. Then turn on the third. (With two fingers you can also tap two at once.)',

    LEVEL_019_TITLE: 'DON\'T LET THE BALL FALL',
    LEVEL_019_HINT_1: 'The ball won\'t float forever.',
    LEVEL_019_HINT_2: 'It needs something under it.',
    LEVEL_019_HINT_3: 'Drag the platform under the ball before it falls.',

    LEVEL_021_TITLE: 'FIND THE EXIT',
    LEVEL_021_HINT_1: 'Walls are things too.',
    LEVEL_021_HINT_2: 'A wall can hide what is behind it.',
    LEVEL_021_HINT_3: 'Drag the wall and tap the door.',

    LEVEL_022_TITLE: 'MAKE 2 + 2 = 5',
    LEVEL_022_HINT_1: 'Math doesn\'t change. Numbers do.',
    LEVEL_022_HINT_2: 'One stick looks a bit loose.',
    LEVEL_022_HINT_3: 'Move the crooked stick of the second 2 to the right: the 2 becomes a 3.',

    LEVEL_023_TITLE: 'PUT THE FISH IN THE WATER',
    LEVEL_023_HINT_1: 'This glass is too small for a fish.',
    LEVEL_023_HINT_2: 'Remember the box and the ball?',
    LEVEL_023_HINT_3: 'Grow the glass with two fingers (or the mouse wheel), then put the fish in.',

    LEVEL_024_TITLE: 'FIND THE [[w_blue|BLUE]]',
    LEVEL_024_HINT_1: 'Look everywhere, even outside the scene.',
    LEVEL_024_HINT_2: 'No object is blue.',
    LEVEL_024_HINT_3: 'Tap the word BLUE.',

    LEVEL_025_TITLE: 'MAKE RULI SMILE',
    LEVEL_025_HINT_1: 'Ruli is serious, but has a weak spot.',
    LEVEL_025_HINT_2: 'Tickles!',
    LEVEL_025_HINT_3: 'Rub Ruli fast, side to side (with your finger or the feather).',

    LEVEL_026_TITLE: 'SORT FROM [[w_min|SMALLEST]] TO [[w_max|BIGGEST]]',
    LEVEL_026_HINT_1: 'Count the spots.',
    LEVEL_026_HINT_2: 'Five spots, three circles. What is missing?',
    LEVEL_026_HINT_3: 'Put SMALLEST in the first spot, the circles in order, and BIGGEST in the last.',

    LEVEL_027_TITLE: '[[w_open|OPEN]] THE BOX',
    LEVEL_027_HINT_1: 'This box has no lid and no lock.',
    LEVEL_027_HINT_2: 'You need a tool. It\'s written down.',
    LEVEL_027_HINT_3: 'Drag the word OPEN onto the box.',

    LEVEL_028_TITLE: 'TAKE THE STAR [[w_up|UP]]',
    LEVEL_028_HINT_1: 'The star is too heavy.',
    LEVEL_028_HINT_2: 'If it won\'t go up...',
    LEVEL_028_HINT_3: 'Drag the word UP to the star.',

    LEVEL_029_TITLE: 'MAKE IT RAIN',
    LEVEL_029_HINT_1: 'Clouds need to gather water.',
    LEVEL_029_HINT_2: 'One tap is not enough.',
    LEVEL_029_HINT_3: 'Rub the cloud until it gets really dark.',

    LEVEL_030_TITLE: 'DON\'T MOVE RULI',
    LEVEL_030_HINT_1: 'If Ruli can\'t go to the door...',
    LEVEL_030_HINT_2: 'The ground is an object too.',
    LEVEL_030_HINT_3: 'Drag the ground to the left until the door reaches Ruli.'
  }
};
