// Español. [[id|PALABRA]] marca palabras que son objetos de la fase.
RULES.L10N['es-ES'] = {
  name: 'Español',
  strings: {
    UI_PLAY: 'JUGAR',
    UI_CONTINUE: 'CONTINUAR',
    UI_LEVELS: 'FASES',
    UI_SETTINGS: 'AJUSTES',
    UI_BACK: 'Volver',
    UI_MENU: 'Menú',
    UI_LEVEL: 'FASE {n}',
    UI_HINT: 'PISTA',
    UI_RESTART: 'REINICIAR',
    UI_HINTS_TITLE: 'PISTAS',
    UI_HINT_MORE: 'OTRA PISTA',
    UI_HINT_LAST: 'ÚLTIMA PISTA',
    UI_CLOSE: 'CERRAR',
    UI_ATTEMPTS: 'Intentos: {n}',
    UI_COMPLETED: 'COMPLETA',
    UI_LOCKED: 'Bloqueada',
    UI_MUSIC: 'Música',
    UI_SFX: 'Efectos de sonido',
    UI_VIBRATION: 'Vibración',
    UI_REDUCE_MOTION: 'Reducir animaciones',
    UI_LANGUAGE: 'Idioma',
    UI_RESET: 'Borrar progreso',
    UI_RESET_CONFIRM: 'Toca otra vez para borrar',
    UI_RESET_DONE: 'Progreso borrado',
    UI_TAGLINE: 'Lee. Piensa. Duda.',
    UI_BY: 'un juego de @xadrezcomz',
    UI_MORE_GAMES: 'Más juegos',
    UI_DEMO_END_TITLE: 'YA CONOCES LAS PRIMERAS REGLAS',
    UI_DEMO_END_TEXT: 'MÁS FASES MUY PRONTO',
    UI_SKIP: 'toca para continuar',

    CHAPTER_LABEL: 'CAPÍTULO {n}',
    CHAPTER_1: 'APRENDE LAS REGLAS',
    CHAPTER_2: 'NO CONFÍES EN LAS REGLAS',
    CHAPTER_3: 'TOCA TODO',
    CHAPTER_4: 'PIENSA DIFERENTE',
    CHAPTER_5: 'ROMPE LAS REGLAS',

    SUCCESS_1: '¡BIEN!',
    SUCCESS_2: '¡LO LOGRASTE!',
    SUCCESS_3: '¡ESO!',

    FB_ALMOST: '¡CASI!',
    FB_TRY_DIFFERENT: 'PRUEBA OTRA COSA',
    FB_HMM: 'MMM...',
    FB_NOT_THIS_TIME: 'ESTA VEZ NO',
    FB_NOFIT: 'NO CABE...',
    FB_TOO_BIG: 'DEMASIADO GRANDE...',
    FB_OOPS: '¡UY! ¡CASI!',
    FB_AGAIN: 'DESDE EL PRINCIPIO...',

    LEVEL_001_TITLE: 'TOCA EL CÍRCULO',
    LEVEL_001_HINT_1: 'A veces la respuesta es justo lo que parece.',
    LEVEL_001_HINT_2: 'El círculo está en el centro de la pantalla.',
    LEVEL_001_HINT_3: 'Toca el círculo una vez.',

    LEVEL_002_TITLE: 'LLEVA LA PELOTA A LA CAJA',
    LEVEL_002_HINT_1: 'Las cosas se pueden mover.',
    LEVEL_002_HINT_2: 'Pon el dedo sobre la pelota y no lo sueltes.',
    LEVEL_002_HINT_3: 'Arrastra la pelota y suéltala dentro de la caja.',

    LEVEL_003_TITLE: 'ABRE LA PUERTA',
    LEVEL_003_HINT_1: 'No todas las puertas se abren igual.',
    LEVEL_003_HINT_2: 'Llamar no sirve. Quizás se desliza...',
    LEVEL_003_HINT_3: 'Arrastra la puerta hacia un lado.',

    LEVEL_005_TITLE: 'PON EL CÍRCULO EN EL CUADRADO',
    LEVEL_005_HINT_1: 'El tamaño de las cosas puede cambiar.',
    LEVEL_005_HINT_2: 'El círculo tiene que ser más pequeño que el cuadrado.',
    LEVEL_005_HINT_3: 'Usa dos dedos (o la rueda del ratón) para achicar el círculo. Después arrástralo.',

    LEVEL_009_TITLE: 'PON [[w_all|TODO]] EN LA CAJA',
    LEVEL_009_HINT_1: 'Todo es todo.',
    LEVEL_009_HINT_2: 'Vuelve a mirar la instrucción.',
    LEVEL_009_HINT_3: 'Arrastra la palabra TODO dentro de la caja.',

    LEVEL_010_TITLE: 'NO TOQUES NADA',
    LEVEL_010_HINT_1: 'A veces la mejor jugada es no jugar.',
    LEVEL_010_HINT_2: 'Lee la instrucción al pie de la letra.',
    LEVEL_010_HINT_3: 'Cierra esta pista y no toques la pantalla durante 3 segundos.',

    LEVEL_011_TITLE: 'TOMA LA LLAVE',
    LEVEL_011_HINT_1: 'Si no puedes ir hacia ella...',
    LEVEL_011_HINT_2: 'La llave solo huye de Ruli.',
    LEVEL_011_HINT_3: 'Arrastra la llave hasta Ruli.',

    LEVEL_012_TITLE: 'LLEGA A LA PUERTA',
    LEVEL_012_HINT_1: 'El camino no tiene por qué ser tuyo.',
    LEVEL_012_HINT_2: 'Ruli no salta. Pero otra cosa aquí se mueve.',
    LEVEL_012_HINT_3: 'Arrastra la puerta hasta Ruli.',

    LEVEL_016_TITLE: 'PON LA PELOTA EN LA CAJA',
    LEVEL_016_HINT_1: 'Si la pelota no se achica...',
    LEVEL_016_HINT_2: 'Quizás el problema es la caja.',
    LEVEL_016_HINT_3: 'Usa dos dedos (o la rueda del ratón) para agrandar la caja. Después arrastra la pelota.',

    LEVEL_020_TITLE: 'ESPERA.',
    LEVEL_020_HINT_1: 'La paciencia también es una regla.',
    LEVEL_020_HINT_2: 'Cada toque reinicia la cuenta.',
    LEVEL_020_HINT_3: 'Cierra esta pista y no toques nada durante 5 segundos.',
    FB_PRESSED: '¡LO APRETASTE!',
    FB_DONT_MOVE: '¡NO MUEVAS A RULI!',
    FB_BIGGER: 'HAY UNO MÁS GRANDE...',
    FB_SAME: 'ESE ES IGUAL...',
    FB_NOT_BLUE: 'ESO NO ES AZUL',
    FB_SERIOUS: 'RULI SIGUE SERIO',
    FB_NOT_UP: 'NO SUBE...',

    LEVEL_004_TITLE: 'ENCIENDE LA LUZ',
    LEVEL_004_HINT_1: 'Toda bombilla tiene una forma de encenderse.',
    LEVEL_004_HINT_2: 'La bombilla no se enciende sola.',
    LEVEL_004_HINT_3: 'Toca el interruptor.',

    LEVEL_006_TITLE: 'ENCUENTRA LA ESTRELLA',
    LEVEL_006_HINT_1: 'No todo está a la vista.',
    LEVEL_006_HINT_2: 'Uno de los círculos no está fijo.',
    LEVEL_006_HINT_3: 'Arrastra el círculo rojo y toca la estrella.',

    LEVEL_007_TITLE: 'HAZ QUE SE ENCUENTREN',
    LEVEL_007_HINT_1: 'Para encontrarse hacen falta dos.',
    LEVEL_007_HINT_2: 'Ninguno puede llegar hasta el final solo.',
    LEVEL_007_HINT_3: 'Lleva a cada uno hasta el medio.',

    LEVEL_008_TITLE: 'LLENA EL VASO',
    LEVEL_008_HINT_1: 'El agua no salta sola de la jarra.',
    LEVEL_008_HINT_2: 'Las jarras se inclinan.',
    LEVEL_008_HINT_3: 'Sostén la jarra justo encima del vaso hasta llenarlo.',

    LEVEL_013_TITLE: 'ENCUENTRA EL CÍRCUL[[w_o|O]] MÁS GRANDE',
    LEVEL_013_HINT_1: 'El más grande quizás no está entre las cosas.',
    LEVEL_013_HINT_2: 'Una letra también es redonda.',
    LEVEL_013_HINT_3: 'Toca la O grande de la instrucción.',

    LEVEL_014_TITLE: 'HAZ QUE APAREZCA EL SOL',
    LEVEL_014_HINT_1: 'El sol nunca se fue.',
    LEVEL_014_HINT_2: 'Algo está delante de él.',
    LEVEL_014_HINT_3: 'Arrastra la nube lejos del sol.',

    LEVEL_015_TITLE: 'NO APRIETES EL BOTÓN',
    LEVEL_015_HINT_1: 'Puedes mover un botón sin apretarlo.',
    LEVEL_015_HINT_2: '¿Qué habrá debajo?',
    LEVEL_015_HINT_3: 'Arrastra el botón a un lado y toca lo que aparezca.',

    LEVEL_017_TITLE: 'ENCUENTRA EL DIFERENTE',
    LEVEL_017_HINT_1: 'Observa con calma.',
    LEVEL_017_HINT_2: 'Todos se mueven juntos... casi todos.',
    LEVEL_017_HINT_3: 'Uno crece cuando los demás se achican. Tócalo.',

    LEVEL_018_TITLE: 'ENCIENDE TODAS LAS LUCES',
    LEVEL_018_HINT_1: 'Solo dos aguantan encendidas. La más antigua siempre se apaga.',
    LEVEL_018_HINT_2: '¿Y si ninguna fuera la más antigua?',
    LEVEL_018_HINT_3: 'Enciende dos interruptores a la vez (en el PC, haz clic muy rápido en los dos) y después el tercero.',

    LEVEL_019_TITLE: 'NO DEJES CAER LA PELOTA',
    LEVEL_019_HINT_1: 'La pelota no va a flotar para siempre.',
    LEVEL_019_HINT_2: 'Necesita algo debajo.',
    LEVEL_019_HINT_3: 'Arrastra la plataforma debajo de la pelota antes de que caiga.',

    LEVEL_021_TITLE: 'ENCUENTRA LA SALIDA',
    LEVEL_021_HINT_1: 'Las paredes también son cosas.',
    LEVEL_021_HINT_2: 'Una pared puede esconder lo que hay detrás.',
    LEVEL_021_HINT_3: 'Arrastra la pared y toca la puerta.',

    LEVEL_022_TITLE: 'HAZ QUE 2 + 2 = 5',
    LEVEL_022_HINT_1: 'Las matemáticas no cambian. Los números, sí.',
    LEVEL_022_HINT_2: 'Un palito parece un poco suelto.',
    LEVEL_022_HINT_3: 'Mueve el palito torcido del segundo 2 a la derecha: el 2 se vuelve 3.',

    LEVEL_023_TITLE: 'PON EL PEZ EN EL AGUA',
    LEVEL_023_HINT_1: 'Este vaso es pequeño para un pez.',
    LEVEL_023_HINT_2: '¿Recuerdas la caja de la pelota?',
    LEVEL_023_HINT_3: 'Agranda el vaso con dos dedos (o la rueda del ratón) y después pon el pez.',

    LEVEL_024_TITLE: 'ENCUENTRA EL [[w_blue|AZUL]]',
    LEVEL_024_HINT_1: 'Busca en todas partes, incluso fuera de la escena.',
    LEVEL_024_HINT_2: 'Ningún objeto es azul.',
    LEVEL_024_HINT_3: 'Toca la palabra AZUL.',

    LEVEL_025_TITLE: 'HAZ SONREÍR A RULI',
    LEVEL_025_HINT_1: 'Ruli es serio, pero tiene un punto débil.',
    LEVEL_025_HINT_2: '¡Cosquillas!',
    LEVEL_025_HINT_3: 'Frota a Ruli rápido, de lado a lado (con el dedo o con la pluma).',

    LEVEL_026_TITLE: 'ORDENA DEL [[w_min|MENOR]] AL [[w_max|MAYOR]]',
    LEVEL_026_HINT_1: 'Cuenta los lugares.',
    LEVEL_026_HINT_2: 'Cinco lugares, tres círculos. ¿Qué falta?',
    LEVEL_026_HINT_3: 'Pon MENOR en el primer lugar, los círculos en orden y MAYOR en el último.',

    LEVEL_027_TITLE: '[[w_open|ABRE]] LA CAJA',
    LEVEL_027_HINT_1: 'Esta caja no tiene tapa ni cerradura.',
    LEVEL_027_HINT_2: 'Necesitas una herramienta. Está escrita.',
    LEVEL_027_HINT_3: 'Arrastra la palabra ABRE hasta la caja.',

    LEVEL_028_TITLE: 'LLEVA LA ESTRELLA [[w_up|ARRIBA]]',
    LEVEL_028_HINT_1: 'La estrella pesa demasiado.',
    LEVEL_028_HINT_2: 'Si ella no va arriba...',
    LEVEL_028_HINT_3: 'Arrastra la palabra ARRIBA hasta la estrella.',

    LEVEL_029_TITLE: 'HAZ QUE LLUEVA',
    LEVEL_029_HINT_1: 'Las nubes tienen que juntar agua.',
    LEVEL_029_HINT_2: 'Tocar una vez no basta.',
    LEVEL_029_HINT_3: 'Frota la nube hasta que esté bien oscura.',

    LEVEL_030_TITLE: 'NO MUEVAS A RULI',
    LEVEL_030_HINT_1: 'Si Ruli no va hasta la puerta...',
    LEVEL_030_HINT_2: 'El suelo también es un objeto.',
    LEVEL_030_HINT_3: 'Arrastra el suelo a la izquierda hasta que la puerta llegue a Ruli.'
  }
};
