// Español. [[id|PALABRA]] marca palabras que son objetos de la fase.
RULES.L10N['es-ES'] = {
  name: 'Español',
  strings: {
    UI_PLAY: 'JUGAR',
    UI_CONTINUE: 'CONTINUAR',
    UI_LEVELS: 'FASES',
    UI_SETTINGS: 'AJUSTES',
    UI_BACK: 'Volver',
    UI_MENU: 'Menú',
    UI_LEVEL: 'FASE {n}',
    UI_HINT: 'PISTA',
    UI_RESTART: 'REINICIAR',
    UI_HINTS_TITLE: 'PISTAS',
    UI_HINT_MORE: 'OTRA PISTA',
    UI_HINT_LAST: 'ÚLTIMA PISTA',
    UI_CLOSE: 'CERRAR',
    UI_ATTEMPTS: 'Intentos: {n}',
    UI_COMPLETED: 'COMPLETA',
    UI_LOCKED: 'Bloqueada',
    UI_MUSIC: 'Música',
    UI_SFX: 'Efectos de sonido',
    UI_VIBRATION: 'Vibración',
    UI_REDUCE_MOTION: 'Reducir animaciones',
    UI_LANGUAGE: 'Idioma',
    UI_RESET: 'Borrar progreso',
    UI_RESET_CONFIRM: 'Toca otra vez para borrar',
    UI_RESET_DONE: 'Progreso borrado',
    UI_TAGLINE: 'Lee. Piensa. Duda.',
    UI_BY: 'un juego de @xadrezcomz',
    UI_MORE_GAMES: 'Más juegos',
    UI_DEMO_END_TITLE: 'YA CONOCES LAS PRIMERAS REGLAS',
    UI_DEMO_END_TEXT: 'MÁS FASES MUY PRONTO',
    UI_SKIP: 'toca para continuar',

    CHAPTER_LABEL: 'CAPÍTULO {n}',
    CHAPTER_1: 'APRENDE LAS REGLAS',
    CHAPTER_2: 'NO CONFÍES EN LAS REGLAS',
    CHAPTER_3: 'TOCA TODO',
    CHAPTER_4: 'PIENSA DIFERENTE',
    CHAPTER_5: 'ROMPE LAS REGLAS',

    SUCCESS_1: '¡BIEN!',
    SUCCESS_2: '¡LO LOGRASTE!',
    SUCCESS_3: '¡ESO!',

    FB_ALMOST: '¡CASI!',
    FB_TRY_DIFFERENT: 'PRUEBA OTRA COSA',
    FB_HMM: 'MMM...',
    FB_NOT_THIS_TIME: 'ESTA VEZ NO',
    FB_NOFIT: 'NO CABE...',
    FB_TOO_BIG: 'DEMASIADO GRANDE...',
    FB_OOPS: '¡UY! ¡CASI!',
    FB_AGAIN: 'DESDE EL PRINCIPIO...',

    LEVEL_001_TITLE: 'TOCA EL CÍRCULO',
    LEVEL_001_HINT_1: 'A veces la respuesta es justo lo que parece.',
    LEVEL_001_HINT_2: 'El círculo está en el centro de la pantalla.',
    LEVEL_001_HINT_3: 'Toca el círculo una vez.',

    LEVEL_002_TITLE: 'LLEVA LA PELOTA A LA CAJA',
    LEVEL_002_HINT_1: 'Las cosas se pueden mover.',
    LEVEL_002_HINT_2: 'Pon el dedo sobre la pelota y no lo sueltes.',
    LEVEL_002_HINT_3: 'Arrastra la pelota y suéltala dentro de la caja.',

    LEVEL_003_TITLE: 'ABRE LA PUERTA',
    LEVEL_003_HINT_1: 'No todas las puertas se abren igual.',
    LEVEL_003_HINT_2: 'Llamar no sirve. Quizás se desliza...',
    LEVEL_003_HINT_3: 'Arrastra la puerta hacia un lado.',

    LEVEL_005_TITLE: 'PON EL CÍRCULO EN EL CUADRADO',
    LEVEL_005_HINT_1: 'El tamaño de las cosas puede cambiar.',
    LEVEL_005_HINT_2: 'El círculo tiene que ser más pequeño que el cuadrado.',
    LEVEL_005_HINT_3: 'Usa dos dedos (o la rueda del ratón) para achicar el círculo. Después arrástralo.',

    LEVEL_009_TITLE: 'PON [[w_all|TODO]] EN LA CAJA',
    LEVEL_009_HINT_1: 'Todo es todo.',
    LEVEL_009_HINT_2: 'Vuelve a mirar la instrucción.',
    LEVEL_009_HINT_3: 'Arrastra la palabra TODO dentro de la caja.',

    LEVEL_010_TITLE: 'NO TOQUES NADA',
    LEVEL_010_HINT_1: 'A veces la mejor jugada es no jugar.',
    LEVEL_010_HINT_2: 'Lee la instrucción al pie de la letra.',
    LEVEL_010_HINT_3: 'Cierra esta pista y no toques la pantalla durante 3 segundos.',

    LEVEL_011_TITLE: 'TOMA LA LLAVE',
    LEVEL_011_HINT_1: 'Si no puedes ir hacia ella...',
    LEVEL_011_HINT_2: 'La llave solo huye de Ruli.',
    LEVEL_011_HINT_3: 'Arrastra la llave hasta Ruli.',

    LEVEL_012_TITLE: 'LLEGA A LA PUERTA',
    LEVEL_012_HINT_1: 'El camino no tiene por qué ser tuyo.',
    LEVEL_012_HINT_2: 'Ruli no salta. Pero otra cosa aquí se mueve.',
    LEVEL_012_HINT_3: 'Arrastra la puerta hasta Ruli.',

    LEVEL_016_TITLE: 'PON LA PELOTA EN LA CAJA',
    LEVEL_016_HINT_1: 'Si la pelota no se achica...',
    LEVEL_016_HINT_2: 'Quizás el problema es la caja.',
    LEVEL_016_HINT_3: 'Usa dos dedos (o la rueda del ratón) para agrandar la caja. Después arrastra la pelota.',

    LEVEL_020_TITLE: 'ESPERA.',
    LEVEL_020_HINT_1: 'La paciencia también es una regla.',
    LEVEL_020_HINT_2: 'Cada toque reinicia la cuenta.',
    LEVEL_020_HINT_3: 'Cierra esta pista y no toques nada durante 5 segundos.'
  }
};
