// Español. [[id|PALABRA]] marca palabras que son objetos de la fase.
RULES.L10N['es-ES'] = {
  name: 'Español',
  strings: {
    UI_PLAY: 'JUGAR',
    UI_CONTINUE: 'CONTINUAR',
    UI_LEVELS: 'FASES',
    UI_SETTINGS: 'AJUSTES',
    UI_BACK: 'Volver',
    UI_MENU: 'Menú',
    UI_LEVEL: 'FASE {n}',
    UI_HINT: 'PISTA',
    UI_RESTART: 'REINICIAR',
    UI_HINTS_TITLE: 'PISTAS',
    UI_HINT_MORE: 'OTRA PISTA',
    UI_HINT_LAST: 'ÚLTIMA PISTA',
    UI_CLOSE: 'CERRAR',
    UI_ATTEMPTS: 'Intentos: {n}',
    UI_COMPLETED: 'COMPLETA',
    UI_LOCKED: 'Bloqueada',
    UI_MUSIC: 'Música',
    UI_SFX: 'Efectos de sonido',
    UI_VIBRATION: 'Vibración',
    UI_REDUCE_MOTION: 'Reducir animaciones',
    UI_LANGUAGE: 'Idioma',
    UI_RESET: 'Borrar progreso',
    UI_RESET_CONFIRM: 'Toca otra vez para borrar',
    UI_RESET_DONE: 'Progreso borrado',
    UI_TAGLINE: 'Lee. Piensa. Duda.',
    UI_BY: 'un juego de @xadrezcomz',
    UI_MORE_GAMES: 'Más juegos',
    UI_SKIP: 'toca para continuar',

    CHAPTER_LABEL: 'CAPÍTULO {n}',
    CHAPTER_1: 'APRENDE LAS REGLAS',
    CHAPTER_2: 'NO CONFÍES EN LAS REGLAS',
    CHAPTER_3: 'TOCA TODO',
    CHAPTER_4: 'PIENSA DIFERENTE',
    CHAPTER_5: 'ROMPE LAS REGLAS',

    SUCCESS_1: '¡BIEN!',
    SUCCESS_2: '¡LO LOGRASTE!',
    SUCCESS_3: '¡ESO!',

    FB_ALMOST: '¡CASI!',
    FB_TRY_DIFFERENT: 'PRUEBA OTRA COSA',
    FB_HMM: 'MMM...',
    FB_NOT_THIS_TIME: 'ESTA VEZ NO',
    FB_NOFIT: 'NO CABE...',
    FB_TOO_BIG: 'DEMASIADO GRANDE...',
    FB_OOPS: '¡UY! ¡CASI!',
    FB_AGAIN: 'DESDE EL PRINCIPIO...',

    LEVEL_001_TITLE: 'TOCA EL CÍRCULO',
    LEVEL_001_HINT_1: 'A veces la respuesta es justo lo que parece.',
    LEVEL_001_HINT_2: 'El círculo está en el centro de la pantalla.',
    LEVEL_001_HINT_3: 'Toca el círculo una vez.',

    LEVEL_002_TITLE: 'LLEVA LA PELOTA A LA CAJA',
    LEVEL_002_HINT_1: 'Las cosas se pueden mover.',
    LEVEL_002_HINT_2: 'Pon el dedo sobre la pelota y no lo sueltes.',
    LEVEL_002_HINT_3: 'Arrastra la pelota y suéltala dentro de la caja.',

    LEVEL_003_TITLE: 'ABRE LA PUERTA',
    LEVEL_003_HINT_1: 'No todas las puertas se abren igual.',
    LEVEL_003_HINT_2: 'Llamar no sirve. Quizás se desliza...',
    LEVEL_003_HINT_3: 'Arrastra la puerta hacia un lado.',

    LEVEL_005_TITLE: 'PON EL CÍRCULO EN EL CUADRADO',
    LEVEL_005_HINT_1: 'El tamaño de las cosas puede cambiar.',
    LEVEL_005_HINT_2: 'El círculo tiene que ser más pequeño que el cuadrado.',
    LEVEL_005_HINT_3: 'Usa dos dedos (o la rueda del ratón) para achicar el círculo. Después arrástralo.',

    LEVEL_009_TITLE: 'PON [[w_all|TODO]] EN LA CAJA',
    LEVEL_009_HINT_1: 'Todo es todo.',
    LEVEL_009_HINT_2: 'Vuelve a mirar la instrucción.',
    LEVEL_009_HINT_3: 'Arrastra la palabra TODO dentro de la caja.',

    LEVEL_010_TITLE: 'NO TOQUES NADA',
    LEVEL_010_HINT_1: 'A veces la mejor jugada es no jugar.',
    LEVEL_010_HINT_2: 'Lee la instrucción al pie de la letra.',
    LEVEL_010_HINT_3: 'Cierra esta pista y no toques la pantalla durante 3 segundos.',

    LEVEL_011_TITLE: 'TOMA LA LLAVE',
    LEVEL_011_HINT_1: 'Si no puedes ir hacia ella...',
    LEVEL_011_HINT_2: 'La llave solo huye de Ruli.',
    LEVEL_011_HINT_3: 'Arrastra la llave hasta Ruli.',

    LEVEL_012_TITLE: 'LLEGA A LA PUERTA',
    LEVEL_012_HINT_1: 'El camino no tiene por qué ser tuyo.',
    LEVEL_012_HINT_2: 'Ruli no salta. Pero otra cosa aquí se mueve.',
    LEVEL_012_HINT_3: 'Arrastra la puerta hasta Ruli.',

    LEVEL_016_TITLE: 'PON LA PELOTA EN LA CAJA',
    LEVEL_016_HINT_1: 'Si la pelota no se achica...',
    LEVEL_016_HINT_2: 'Quizás el problema es la caja.',
    LEVEL_016_HINT_3: 'Usa dos dedos (o la rueda del ratón) para agrandar la caja. Después arrastra la pelota.',

    LEVEL_020_TITLE: 'ESPERA.',
    LEVEL_020_HINT_1: 'La paciencia también es una regla.',
    LEVEL_020_HINT_2: 'Cada toque reinicia la cuenta.',
    LEVEL_020_HINT_3: 'Cierra esta pista y no toques nada durante 5 segundos.',
    FB_PRESSED: '¡LO APRETASTE!',
    FB_DONT_MOVE: '¡NO MUEVAS A RULI!',
    FB_BIGGER: 'HAY UNO MÁS GRANDE...',
    FB_SAME: 'ESE ES IGUAL...',
    FB_NOT_BLUE: 'ESO NO ES AZUL',
    FB_SERIOUS: 'RULI SIGUE SERIO',
    FB_OLDEST: 'SE APAGÓ LA MÁS ANTIGUA',
    FB_NOT_UP: 'NO SUBE...',

    LEVEL_004_TITLE: 'ENCIENDE LA LUZ',
    LEVEL_004_HINT_1: 'Toda bombilla tiene una forma de encenderse.',
    LEVEL_004_HINT_2: 'La bombilla no se enciende sola.',
    LEVEL_004_HINT_3: 'Toca el interruptor.',

    LEVEL_006_TITLE: 'ENCUENTRA LA ESTRELLA',
    LEVEL_006_HINT_1: 'No todo está a la vista.',
    LEVEL_006_HINT_2: 'Uno de los círculos no está fijo.',
    LEVEL_006_HINT_3: 'Arrastra el círculo rojo y toca la estrella.',

    LEVEL_007_TITLE: 'HAZ QUE SE ENCUENTREN',
    LEVEL_007_HINT_1: 'Para encontrarse hacen falta dos.',
    LEVEL_007_HINT_2: 'Ninguno puede llegar hasta el final solo.',
    LEVEL_007_HINT_3: 'Lleva a cada uno hasta el medio.',

    LEVEL_008_TITLE: 'LLENA EL VASO',
    LEVEL_008_HINT_1: 'El agua no salta sola de la jarra.',
    LEVEL_008_HINT_2: 'Las jarras se inclinan.',
    LEVEL_008_HINT_3: 'Sostén la jarra justo encima del vaso hasta llenarlo.',

    LEVEL_013_TITLE: 'ENCUENTRA EL CÍRCUL[[w_o|O]] MÁS GRANDE',
    LEVEL_013_HINT_1: 'El más grande quizás no está entre las cosas.',
    LEVEL_013_HINT_2: 'Una letra también es redonda.',
    LEVEL_013_HINT_3: 'Toca la O grande de la instrucción.',

    LEVEL_014_TITLE: 'HAZ QUE APAREZCA EL SOL',
    LEVEL_014_HINT_1: 'El sol nunca se fue.',
    LEVEL_014_HINT_2: 'Algo está delante de él.',
    LEVEL_014_HINT_3: 'Arrastra la nube lejos del sol.',

    LEVEL_015_TITLE: 'NO APRIETES EL BOTÓN',
    LEVEL_015_HINT_1: 'Puedes mover un botón sin apretarlo.',
    LEVEL_015_HINT_2: '¿Qué habrá debajo?',
    LEVEL_015_HINT_3: 'Arrastra el botón a un lado y toca lo que aparezca.',

    LEVEL_017_TITLE: 'ENCUENTRA EL DIFERENTE',
    LEVEL_017_HINT_1: 'Observa con calma.',
    LEVEL_017_HINT_2: 'Todos se mueven juntos... casi todos.',
    LEVEL_017_HINT_3: 'Uno crece cuando los demás se achican. Tócalo.',

    LEVEL_018_TITLE: 'ENCIENDE TODAS LAS LUCES',
    LEVEL_018_HINT_1: 'Solo dos aguantan encendidas. La más antigua siempre se apaga.',
    LEVEL_018_HINT_2: '¿Y si dos se encendieran exactamente a la vez? Los interruptores también se mueven.',
    LEVEL_018_HINT_3: 'Arrastra un interruptor encima de otro y toca la pila: los dos se encienden juntos. Después enciende el tercero. (Con dos dedos también puedes tocar dos a la vez.)',

    LEVEL_019_TITLE: 'NO DEJES CAER LA PELOTA',
    LEVEL_019_HINT_1: 'La pelota no va a flotar para siempre.',
    LEVEL_019_HINT_2: 'Necesita algo debajo.',
    LEVEL_019_HINT_3: 'Arrastra la plataforma debajo de la pelota antes de que caiga.',

    LEVEL_021_TITLE: 'ENCUENTRA LA SALIDA',
    LEVEL_021_HINT_1: 'Las paredes también son cosas.',
    LEVEL_021_HINT_2: 'Una pared puede esconder lo que hay detrás.',
    LEVEL_021_HINT_3: 'Arrastra la pared y toca la puerta.',

    LEVEL_022_TITLE: 'HAZ QUE 2 + 2 = 5',
    LEVEL_022_HINT_1: 'Las matemáticas no cambian. Los números, sí.',
    LEVEL_022_HINT_2: 'Un palito parece un poco suelto.',
    LEVEL_022_HINT_3: 'Mueve el palito torcido del segundo 2 a la derecha: el 2 se vuelve 3.',

    LEVEL_023_TITLE: 'PON EL PEZ EN EL AGUA',
    LEVEL_023_HINT_1: 'Este vaso es pequeño para un pez.',
    LEVEL_023_HINT_2: '¿Recuerdas la caja de la pelota?',
    LEVEL_023_HINT_3: 'Agranda el vaso con dos dedos (o la rueda del ratón) y después pon el pez.',

    LEVEL_024_TITLE: 'ENCUENTRA EL [[w_blue|AZUL]]',
    LEVEL_024_HINT_1: 'Busca en todas partes, incluso fuera de la escena.',
    LEVEL_024_HINT_2: 'Ningún objeto es azul.',
    LEVEL_024_HINT_3: 'Toca la palabra AZUL.',

    LEVEL_025_TITLE: 'HAZ SONREÍR A RULI',
    LEVEL_025_HINT_1: 'Ruli es serio, pero tiene un punto débil.',
    LEVEL_025_HINT_2: '¡Cosquillas!',
    LEVEL_025_HINT_3: 'Frota a Ruli rápido, de lado a lado (con el dedo o con la pluma).',

    LEVEL_026_TITLE: 'ORDENA DEL [[w_min|MENOR]] AL [[w_max|MAYOR]]',
    LEVEL_026_HINT_1: 'Cuenta los lugares.',
    LEVEL_026_HINT_2: 'Cinco lugares, tres círculos. ¿Qué falta?',
    LEVEL_026_HINT_3: 'Pon MENOR en el primer lugar, los círculos en orden y MAYOR en el último.',

    LEVEL_027_TITLE: '[[w_open|ABRE]] LA CAJA',
    LEVEL_027_HINT_1: 'Esta caja no tiene tapa ni cerradura.',
    LEVEL_027_HINT_2: 'Necesitas una herramienta. Está escrita.',
    LEVEL_027_HINT_3: 'Arrastra la palabra ABRE hasta la caja.',

    LEVEL_028_TITLE: 'LLEVA LA ESTRELLA [[w_up|ARRIBA]]',
    LEVEL_028_HINT_1: 'La estrella pesa demasiado.',
    LEVEL_028_HINT_2: 'Si ella no va arriba...',
    LEVEL_028_HINT_3: 'Arrastra la palabra ARRIBA hasta la estrella.',

    LEVEL_029_TITLE: 'HAZ QUE LLUEVA',
    LEVEL_029_HINT_1: 'Las nubes tienen que juntar agua.',
    LEVEL_029_HINT_2: 'Tocar una vez no basta.',
    LEVEL_029_HINT_3: 'Frota la nube hasta que esté bien oscura.',

    LEVEL_030_TITLE: 'NO MUEVAS A RULI',
    LEVEL_030_HINT_1: 'Si Ruli no va hasta la puerta...',
    LEVEL_030_HINT_2: 'El suelo también es un objeto.',
    LEVEL_030_HINT_3: 'Arrastra el suelo a la izquierda hasta que la puerta llegue a Ruli.',
    FB_ONLY_TWO: 'SOLO DOS...',
    FB_THIRSTY: 'TIENE SED...',
    FB_GLUG: '¡GLUP GLUP!',
    FB_NOTHING: 'NADA AQUÍ...',
    FB_HEAVY: 'DEMASIADO PESADA...',
    FB_NOT_SAME: 'NO SON IGUALES...',
    FB_TICTAC: 'TIC... TAC...',
    FB_TIRED: 'RULI ESTÁ CANSADO',
    FB_GREEN: '¡ES VERDE!',
    FB_FIXED: 'ESOS NO SE MUEVEN',
    FB_WRONG: 'INCORRECTO...',
    FB_LOCKED: 'CERRADA',
    FB_UNLOCKED: '¡CLIC!',
    FB_ORDER: 'FUERA DE ORDEN',
    FB_AGAIN_WATCH: 'MIRA OTRA VEZ...',
    FINALE_1: 'AHORA CONOCES LAS',
    FINALE_WORD: 'REGLAS.',
    FINALE_2: '...O NO. 😉',
    CHAPTER_6: 'LA PANTALLA TAMBIÉN JUEGA',
    CHAPTER_7: 'PALABRAS QUE LO CAMBIAN TODO',
    CHAPTER_8: 'FÍSICA DE JUGUETE',
    CHAPTER_9: 'MIRA OTRA VEZ',
    CHAPTER_10: 'FUERA DE LA CAJA',
    LEVEL_046_WORD: 'NADA',
    LEVEL_048_Q: '2 + 3 = ?',
    LEVEL_049_SIGN: 'NO MUEVAS LA PUERTA',

    LEVEL_031_TITLE: 'ENCUENTRA 3 TRIÁNGULOS',
    LEVEL_031_HINT_1: 'Dos es fácil. ¿Y el tercero?',
    LEVEL_031_HINT_2: 'Dos mitades hacen un entero.',
    LEVEL_031_HINT_3: 'Junta las dos mitades moradas.',

    LEVEL_032_TITLE: 'CRUZA EL PUENTE',
    LEVEL_032_HINT_1: 'Este puente no llega al otro lado.',
    LEVEL_032_HINT_2: 'Los puentes también crecen... hacia un lado.',
    LEVEL_032_HINT_3: 'Estira el puente con dos dedos (o la rueda del ratón) y luego lleva a Ruli.',

    LEVEL_033_TITLE: 'PON 5 PELOTAS EN LA CAJA',
    LEVEL_033_HINT_1: 'Cuenta las pelotas.',
    LEVEL_033_HINT_2: 'Solo hay cuatro. ¿Una puede volverse dos?',
    LEVEL_033_HINT_3: 'Estira la pelota verde con dos dedos (o la rueda del ratón) hasta que se divida.',

    LEVEL_034_TITLE: 'HAZ [[w_all|TODO]] PEQUEÑO',
    LEVEL_034_HINT_1: 'Todo, de verdad.',
    LEVEL_034_HINT_2: 'Todavía hay algo grande en la pantalla.',
    LEVEL_034_HINT_3: 'Achica también la palabra TODO con dos dedos (o la rueda del ratón).',

    LEVEL_035_TITLE: 'HAZ CRECER LA PLANTA',
    LEVEL_035_HINT_1: 'Las plantas necesitan dos cosas.',
    LEVEL_035_HINT_2: 'El orden importa.',
    LEVEL_035_HINT_3: 'Lleva primero la regadera a la planta. Después el sol.',

    LEVEL_036_TITLE: '[[w_all|ENCUENTRA LO QUE ESTÁ ESCONDIDO]]',
    LEVEL_036_HINT_1: 'No está detrás de las cajas.',
    LEVEL_036_HINT_2: 'Algo está delante de todo.',
    LEVEL_036_HINT_3: 'Arrastra la propia instrucción y toca lo que aparezca.',

    LEVEL_037_TITLE: 'PON LA LUNA EN EL CIELO',
    LEVEL_037_HINT_1: 'La luna no sube.',
    LEVEL_037_HINT_2: 'Si ella no llega al cielo...',
    LEVEL_037_HINT_3: 'Arrastra el cielo hacia abajo hasta que la luna quede dentro.',

    LEVEL_038_TITLE: 'JUNTA LOS IGUALES',
    LEVEL_038_HINT_1: 'Son iguales en todo, menos en una cosa.',
    LEVEL_038_HINT_2: 'Iguales tienen el mismo tamaño.',
    LEVEL_038_HINT_3: 'Deja los dos círculos del mismo tamaño (dos dedos o rueda) y júntalos.',

    LEVEL_039_TITLE: 'HAZ QUE EL RELOJ VAYA MÁS RÁPIDO',
    LEVEL_039_HINT_1: 'Los relojes no tienen prisa.',
    LEVEL_039_HINT_2: 'Pero las agujas aceptan un empujón.',
    LEVEL_039_HINT_3: 'Gira la aguja larga con el dedo, dos vueltas.',

    LEVEL_040_TITLE: 'LLEGA AL [[w_final|FINAL]]',
    LEVEL_040_HINT_1: 'El camino es demasiado largo para Ruli.',
    LEVEL_040_HINT_2: 'Quizás el final puede venir a él.',
    LEVEL_040_HINT_3: 'Arrastra la palabra FINAL hasta Ruli.',

    LEVEL_041_TITLE: 'NO TOQUES EL VERDE',
    LEVEL_041_HINT_1: 'El verde es el problema.',
    LEVEL_041_HINT_2: '¿Y si ya no fuera verde?',
    LEVEL_041_HINT_3: 'Lleva la pintura azul al círculo verde y luego tócalo.',

    LEVEL_042_TITLE: 'PON LA ESTRELLA FUERA DE LA CAJA',
    LEVEL_042_HINT_1: 'La caja no se abre.',
    LEVEL_042_HINT_2: 'Dentro y fuera dependen del tamaño.',
    LEVEL_042_HINT_3: 'Agranda la estrella (dos dedos o rueda) hasta que la caja quede dentro.',

    LEVEL_043_TITLE: 'HAZ QUE LOS DOS LADOS SEAN IGUALES',
    LEVEL_043_HINT_1: 'Los círculos no se mueven.',
    LEVEL_043_HINT_2: '¿Qué decide los lados?',
    LEVEL_043_HINT_3: 'Arrastra la línea hasta que haya tres círculos de cada lado.',

    LEVEL_044_TITLE: 'ENCUENTRA LA PUERTA',
    LEVEL_044_HINT_1: 'No hay puerta. Todavía.',
    LEVEL_044_HINT_2: 'Las formas pueden construir cosas.',
    LEVEL_044_HINT_3: 'Lleva el rectángulo morado al contorno y el punto amarillo al pomo.',

    LEVEL_045_TITLE: 'HAZ QUE RULI LLEGUE MÁS ALTO',
    LEVEL_045_HINT_1: 'La escalera es muy pequeña.',
    LEVEL_045_HINT_2: 'Las cajas pueden ser escalones.',
    LEVEL_045_HINT_3: 'Apila las tres cajas debajo de la estrella y pon a Ruli encima.',

    LEVEL_046_TITLE: 'NO DEJES NADA EN EL SUELO',
    LEVEL_046_HINT_1: 'Mira bien el suelo.',
    LEVEL_046_HINT_2: 'Hay una palabra escondida ahí abajo.',
    LEVEL_046_HINT_3: 'Sube también la palabrita NADA.',

    LEVEL_047_TITLE: 'HAZ QUE EL DÍA SE VUELVA NOCHE',
    LEVEL_047_HINT_1: '¿Cuándo llega la noche?',
    LEVEL_047_HINT_2: 'El sol tiene que irse.',
    LEVEL_047_HINT_3: 'Arrastra el sol por debajo del horizonte.',

    LEVEL_048_TITLE: 'ENCUENTRA LA [[w_ans|RESPUESTA]]',
    LEVEL_048_HINT_1: 'Ninguno de estos números sirve.',
    LEVEL_048_HINT_2: 'La respuesta está escrita.',
    LEVEL_048_HINT_3: 'Arrastra la palabra RESPUESTA al espacio vacío.',

    LEVEL_049_TITLE: 'ROMPE LA REGLA',
    LEVEL_049_HINT_1: 'Lee el cartel.',
    LEVEL_049_HINT_2: 'La instrucción dice que la rompas.',
    LEVEL_049_HINT_3: 'Mueve la puerta.',

    LEVEL_050_TITLE: 'YA SABES QUÉ HACER',
    LEVEL_050_HINT_1: 'Todo lo que aprendiste vale aquí.',
    LEVEL_050_HINT_2: 'La puerta está cerrada. ¿Qué abre puertas?',
    LEVEL_050_HINT_3: 'Quita la caja, lleva la llave a la puerta y luego lleva a Ruli hasta ella.',
    FB_HELP: '¿NECESITAS AYUDA?',
    FB_READING: 'ESTOY LEYENDO...',
    FB_SEEN: 'TODAVÍA SE VE A RULI',
    FB_NOT_ALLOWED: '¡NO SE PUEDE!',
    FB_NOT_SEVEN: 'ESE NO ES 7',
    FB_PAINTING: 'ES SOLO UN CUADRO',
    FB_SPLASH: '¡PLAF!',
    FB_ALREADY_DAY: 'YA ES DE DÍA...',
    FB_ROUND: 'ESO ES REDONDO',
    FB_BACKWARDS: 'AQUÍ LA PUERTA ABRE LA LLAVE...',
    FB_MAKES_SENSE: '¡AHORA TIENE SENTIDO!',
    LEVEL_054_LABEL: '[[w_fase|FASE]] 54',
    LEVEL_057_LABEL: 'FASE 5[[w_seven|7]]',
    LEVEL_059_LABEL: 'FASE [[w_five|5]]9',
    LEVEL_061_L1: 'G',
    LEVEL_061_L2: 'A',
    LEVEL_061_L3: 'T',
    LEVEL_061_L4: 'O',
    LEVEL_061_NEW: 'P',
    LEVEL_061_DECOY: 'R',
    LEVEL_066_A: 'S',
    LEVEL_066_B: 'O',
    LEVEL_066_C: 'L',
    LEVEL_066_X1: 'A',
    LEVEL_066_X2: 'R',

    LEVEL_051_TITLE: 'PIDE AYUDA',
    LEVEL_051_HINT_1: 'Eso. Pediste ayuda. Cierra esta ventana.',
    LEVEL_051_HINT_2: 'Era solo eso.',
    LEVEL_051_HINT_3: 'Pedir ayuda también es una jugada.',

    LEVEL_052_TITLE: 'INTÉNTALO OTRA VEZ',
    LEVEL_052_HINT_1: 'A veces no sale a la primera.',
    LEVEL_052_HINT_2: 'La instrucción dice exactamente qué hacer.',
    LEVEL_052_HINT_3: 'Toca REINICIAR.',

    LEVEL_053_TITLE: 'NO LEAS ESTO',
    LEVEL_053_HINT_1: 'Difícil no leer, ¿verdad?',
    LEVEL_053_HINT_2: '¿Y si la frase desapareciera de tu vista?',
    LEVEL_053_HINT_3: 'Arrastra el papel encima de la instrucción.',

    LEVEL_054_TITLE: 'PON LA FASE EN LA CAJA',
    LEVEL_054_HINT_1: 'La estrella no es la fase.',
    LEVEL_054_HINT_2: 'Mira arriba de la pantalla.',
    LEVEL_054_HINT_3: 'Arrastra la palabra FASE, allá arriba, hasta la caja.',

    LEVEL_055_TITLE: 'ESCONDE A RULI',
    LEVEL_055_HINT_1: 'Detrás del árbol todavía se ve.',
    LEVEL_055_HINT_2: 'Hay algo grande en la pantalla que no es del escenario.',
    LEVEL_055_HINT_3: 'Arrastra a Ruli detrás de la instrucción.',

    LEVEL_056_TITLE: '[[w_not|NO]] TOQUES LA ESTRELLA',
    LEVEL_056_HINT_1: 'La frase dice que no toques.',
    LEVEL_056_HINT_2: '¿Y si la frase cambiara?',
    LEVEL_056_HINT_3: 'Saca la palabra NO de la frase y luego toca la estrella.',

    LEVEL_057_TITLE: 'ENCUENTRA EL 7',
    LEVEL_057_HINT_1: 'Cuenta las cartas.',
    LEVEL_057_HINT_2: 'Ninguna carta es 7. Pero hay un 7 en la pantalla.',
    LEVEL_057_HINT_3: 'Toca el 7 de "FASE 57", arriba.',

    LEVEL_058_TITLE: 'PON AL [[w_g|GIGANTE]] EN LA CAJA',
    LEVEL_058_HINT_1: 'La pelota no es el gigante.',
    LEVEL_058_HINT_2: 'El gigante es demasiado grande para la caja.',
    LEVEL_058_HINT_3: 'Achica la palabra GIGANTE (dos dedos o rueda) y arrástrala a la caja.',

    LEVEL_059_TITLE: 'TOCA DEL 1 AL 5',
    LEVEL_059_HINT_1: 'Busca el 5.',
    LEVEL_059_HINT_2: 'No está entre las cartas.',
    LEVEL_059_HINT_3: 'Toca 1, 2, 3, 4 y después el 5 de "FASE 59".',

    LEVEL_060_TITLE: 'LLEVA A [[w_ruli|RULI]] A LA PUERTA',
    LEVEL_060_HINT_1: 'Este Ruli no se mueve.',
    LEVEL_060_HINT_2: 'Es solo un cuadro en la pared.',
    LEVEL_060_HINT_3: 'Arrastra la palabra RULI hasta la puerta.',

    LEVEL_061_TITLE: 'CONVIERTE EL GATO EN PATO',
    LEVEL_061_HINT_1: 'Una letra lo cambia todo.',
    LEVEL_061_HINT_2: 'GATO y PATO solo cambian al principio.',
    LEVEL_061_HINT_3: 'Suelta la letra P encima de la G.',

    LEVEL_062_TITLE: 'USA EL [[w_bridge|PUENTE]]',
    LEVEL_062_HINT_1: 'No hay ningún puente.',
    LEVEL_062_HINT_2: 'El puente está escrito.',
    LEVEL_062_HINT_3: 'Arrastra la palabra PUENTE al río y luego lleva a Ruli.',

    LEVEL_063_TITLE: 'PINTA EL CIELO DE [[w_blue|AZUL]]',
    LEVEL_063_HINT_1: 'Rojo y amarillo no hacen azul aquí.',
    LEVEL_063_HINT_2: '¿Dónde más hay azul?',
    LEVEL_063_HINT_3: 'Arrastra la palabra AZUL hasta el cielo.',

    LEVEL_064_TITLE: 'HAZ QUE EL [[w_small|PEQUEÑO]] SEA GRANDE',
    LEVEL_064_HINT_1: 'La pelota no crece.',
    LEVEL_064_HINT_2: '¿Pequeño quién?',
    LEVEL_064_HINT_3: 'Agranda la palabra PEQUEÑO con dos dedos (o la rueda del ratón).',

    LEVEL_065_TITLE: 'HAZ QUE 1 + 1 = 1',
    LEVEL_065_HINT_1: 'Uno más uno no siempre da dos.',
    LEVEL_065_HINT_2: 'A las gotas de agua les gusta juntarse.',
    LEVEL_065_HINT_3: 'Junta una gota con la otra.',

    LEVEL_066_TITLE: 'ESCRIBE EL NOMBRE DE ESTO',
    LEVEL_066_HINT_1: 'Mira el dibujo.',
    LEVEL_066_HINT_2: 'Bastan tres letras.',
    LEVEL_066_HINT_3: 'Forma la palabra SOL en los tres espacios.',

    LEVEL_067_TITLE: 'BORRA LA [[w_x|X]]',
    LEVEL_067_HINT_1: 'Las gomas borran frotando.',
    LEVEL_067_HINT_2: 'Hay más de una X en la pantalla.',
    LEVEL_067_HINT_3: 'Frota la X grande y también la X de la instrucción.',

    LEVEL_068_TITLE: 'CAMBIA EL [[w_day|DÍA]] POR LA [[w_night|NOCHE]]',
    LEVEL_068_HINT_1: 'El día ya está aquí.',
    LEVEL_068_HINT_2: 'La noche está escrita.',
    LEVEL_068_HINT_3: 'Lleva la palabra NOCHE hasta el sol.',

    LEVEL_069_TITLE: '[[w_all|TOCA LO QUE NO ES REDONDO]]',
    LEVEL_069_HINT_1: 'Todo en el escenario es redondo.',
    LEVEL_069_HINT_2: 'Pero no todo en la pantalla.',
    LEVEL_069_HINT_3: 'Toca la propia instrucción.',

    LEVEL_070_TITLE: 'LA [[w_a|PUERTA]] ABRE LA [[w_b|LLAVE]]',
    LEVEL_070_HINT_1: 'Esa frase es rara.',
    LEVEL_070_HINT_2: '¿Y si las palabras cambiaran de lugar?',
    LEVEL_070_HINT_3: 'Suelta PUERTA encima de LLAVE. Luego lleva la llave a la puerta.',
    FB_FLEW: '¡EL GLOBO SE ESCAPÓ!',
    FB_TOO_DEEP: 'DEMASIADO HONDO...',
    FB_TOO_HIGH: 'LA CANASTA ESTÁ DEMASIADO ALTA',
    FB_GLASS: 'AQUÍ HAY UN VIDRIO',
    FB_GLUED: 'ESTÁN PEGADOS',
    FB_NEEDS_SLOPE: 'NECESITA UNA BAJADA',
    FB_NEEDS_HEAT: 'NECESITA CALOR',
    FB_MELTED: '¡SE DERRITIÓ!',
    FB_HOT: 'QUÉ CALOR...',
    FB_WHICH: '¿CUÁL SERÁ?',
    FB_SAME_AS_BEFORE: 'ESE NO CAMBIÓ',
    FB_WAIT_WATCH: 'ESPERA Y OBSERVA...',
    FB_COUNT_AGAIN: 'CUENTA OTRA VEZ',
    FB_NOT_MATCH: 'NO ES ESA SOMBRA',
    FB_NOT_GREEN: 'TODAVÍA NO ESTÁ VERDE',
    FB_LIGHT: 'ESA ES LIVIANA',
    FB_NOT_HERE: 'NO ESTÁ AQUÍ',
    FB_SPIN_IT: 'GIRA EL DISCO',
    FB_AWAKE: '¡ASÍ SE DESPIERTA!',
    FB_CRASH: '¡CRAC!',
    FB_NOT_GREEN_YET: 'ESO NO ES VERDE',
    FB_BYE: '¿ADIÓS?',
    FB_THE_END: 'ES EL FIN...',
    LEVEL_099_S1: 'NO TOQUES LA ESTRELLA',
    LEVEL_099_S2: 'NO MUEVAS LA CAJA',
    LEVEL_099_S3: 'NO ESPERES',
    LEVEL_100_SIGN: 'FIN',

    LEVEL_071_TITLE: 'NO DEJES QUE EL GLOBO SE ESCAPE',
    LEVEL_071_HINT_1: 'Sostenerlo cansa.',
    LEVEL_071_HINT_2: 'Los globos suelen atarse a algo pesado.',
    LEVEL_071_HINT_3: 'Arrastra el globo hasta la piedra.',

    LEVEL_072_TITLE: 'EQUILIBRA LA BALANZA',
    LEVEL_072_HINT_1: 'Las pelotas no pesan lo suficiente.',
    LEVEL_072_HINT_2: 'Equilibrar no es solo poner cosas.',
    LEVEL_072_HINT_3: 'Saca la piedra del plato.',

    LEVEL_073_TITLE: 'TOMA LA LLAVE',
    LEVEL_073_HINT_1: 'La llave está demasiado al fondo.',
    LEVEL_073_HINT_2: '¿Qué hace subir el agua?',
    LEVEL_073_HINT_3: 'Echa las piedras en el vaso hasta que la llave suba y tómala.',

    LEVEL_074_TITLE: 'PON LA PELOTA EN LA CANASTA',
    LEVEL_074_HINT_1: 'La canasta está demasiado alta para llevar la pelota.',
    LEVEL_074_HINT_2: '¿Conoces los balancines?',
    LEVEL_074_HINT_3: 'Suelta la piedra en la punta derecha del balancín.',

    LEVEL_075_TITLE: 'TOMA EL CLIP',
    LEVEL_075_HINT_1: 'El vidrio no se abre.',
    LEVEL_075_HINT_2: 'Algunas cosas atraen el metal desde lejos.',
    LEVEL_075_HINT_3: 'Acerca el imán al vidrio.',

    LEVEL_076_TITLE: 'DERRIBA LA TORRE',
    LEVEL_076_HINT_1: 'Los bloques están pegados.',
    LEVEL_076_HINT_2: '¿Y si el suelo temblara?',
    LEVEL_076_HINT_3: 'Frota el suelo rápido, de lado a lado.',

    LEVEL_077_TITLE: 'HAZ RODAR LA PELOTA HASTA EL HOYO',
    LEVEL_077_HINT_1: 'La pelota no rueda cuesta arriba.',
    LEVEL_077_HINT_2: 'La rampa puede cambiar de inclinación.',
    LEVEL_077_HINT_3: 'Gira la rampa hasta que baje hacia la derecha.',

    LEVEL_078_TITLE: 'ENCIENDE LA FOGATA',
    LEVEL_078_HINT_1: 'El fuego necesita calor.',
    LEVEL_078_HINT_2: 'La fricción calienta.',
    LEVEL_078_HINT_3: 'Frota la ramita contra la leña (o frota la leña con el dedo).',

    LEVEL_079_TITLE: 'QUE NO SE DERRITA EL HELADO',
    LEVEL_079_HINT_1: 'El problema es el sol.',
    LEVEL_079_HINT_2: 'La sombra lo resuelve.',
    LEVEL_079_HINT_3: 'Pon la nube delante del sol o el paraguas sobre el helado y espera.',

    LEVEL_080_TITLE: 'LLEVA A RULI HASTA LA ESTRELLA',
    LEVEL_080_HINT_1: 'Saltar no sirve.',
    LEVEL_080_HINT_2: 'Algo aquí sube solo.',
    LEVEL_080_HINT_3: 'Lleva el globo hasta Ruli.',

    LEVEL_081_TITLE: 'ENCUENTRA LA PELOTA',
    LEVEL_081_HINT_1: 'No hace falta seguir los vasos.',
    LEVEL_081_HINT_2: 'Los vasos se pueden levantar.',
    LEVEL_081_HINT_3: 'Arrastra los vasos a un lado y toca la pelota.',

    LEVEL_082_TITLE: '¿QUÉ CAMBIÓ?',
    LEVEL_082_HINT_1: 'Espera un poco.',
    LEVEL_082_HINT_2: 'Después del parpadeo, cambia un color.',
    LEVEL_082_HINT_3: 'Toca el círculo del medio después de que la luz parpadee.',

    LEVEL_083_TITLE: 'ENCUENTRA LA LLAVE EN LA OSCURIDAD',
    LEVEL_083_HINT_1: 'Está demasiado oscuro.',
    LEVEL_083_HINT_2: 'Tienes una linterna.',
    LEVEL_083_HINT_3: 'Arrastra la linterna por la pantalla y toca la llave.',

    LEVEL_084_TITLE: '¿CUÁNTAS ESTRELLAS? TOCA EL NÚMERO',
    LEVEL_084_HINT_1: 'Cuenta con calma.',
    LEVEL_084_HINT_2: 'Una está escondida.',
    LEVEL_084_HINT_3: 'Mueve la nube: son 5.',

    LEVEL_085_TITLE: 'PON A RULI EN SU SOMBRA',
    LEVEL_085_HINT_1: 'Las sombras no son iguales.',
    LEVEL_085_HINT_2: 'Mira el brote y los brazos.',
    LEVEL_085_HINT_3: 'La sombra correcta es la de la derecha.',

    LEVEL_086_TITLE: 'TOCA CUANDO SE PONGA VERDE',
    LEVEL_086_HINT_1: 'El verde dura poco.',
    LEVEL_086_HINT_2: 'Observa el ritmo antes de tocar.',
    LEVEL_086_HINT_3: 'Toca el semáforo mientras la luz verde esté encendida.',

    LEVEL_087_TITLE: 'HAZ QUE EL REFLEJO TOME LA ESTRELLA',
    LEVEL_087_HINT_1: 'Ruli no atraviesa el espejo.',
    LEVEL_087_HINT_2: 'El reflejo copia todo... al revés.',
    LEVEL_087_HINT_3: 'Lleva a Ruli arriba a la izquierda: el reflejo irá arriba a la derecha.',

    LEVEL_088_TITLE: 'REPITE LA SECUENCIA',
    LEVEL_088_HINT_1: 'Presta atención a las luces.',
    LEVEL_088_HINT_2: 'Son cuatro parpadeos.',
    LEVEL_088_HINT_3: 'Toca: medio, izquierda, derecha, medio.',

    LEVEL_089_TITLE: 'TOCA LA CAJA MÁS PESADA',
    LEVEL_089_HINT_1: 'Por fuera son todas iguales.',
    LEVEL_089_HINT_2: 'La balanza lo sabe.',
    LEVEL_089_HINT_3: 'Pon las cajas en los platos y compara.',

    LEVEL_090_TITLE: 'ENCUENTRA AL AMIGO DE RULI',
    LEVEL_090_HINT_1: 'No está detrás de las cosas.',
    LEVEL_090_HINT_2: 'Mira los bordes de la pantalla.',
    LEVEL_090_HINT_3: 'Toca al amigo rosa que se asoma a la derecha.',

    LEVEL_091_TITLE: 'DIBUJA UN PUENTE',
    LEVEL_091_HINT_1: 'No hay puente todavía.',
    LEVEL_091_HINT_2: 'Puedes dibujar con el dedo.',
    LEVEL_091_HINT_3: 'Traza una línea de un borde del hoyo al otro.',

    LEVEL_092_TITLE: 'UNE LOS PUNTOS',
    LEVEL_092_HINT_1: 'Los números muestran el orden.',
    LEVEL_092_HINT_2: 'Una sola línea, sin levantar el dedo.',
    LEVEL_092_HINT_3: 'Traza pasando por 1, 2, 3, 4 y 5.',

    LEVEL_093_TITLE: 'LLEVA EL AGUA HASTA LA PLANTA',
    LEVEL_093_HINT_1: 'Los tubos están girados.',
    LEVEL_093_HINT_2: 'Los tubos giran.',
    LEVEL_093_HINT_3: 'Gira los tubos hasta formar un camino del grifo a la planta.',

    LEVEL_094_TITLE: 'ABRE LA CAJA FUERTE',
    LEVEL_094_HINT_1: 'La clave siempre está a la vista.',
    LEVEL_094_HINT_2: '¿Qué número está escrito arriba?',
    LEVEL_094_HINT_3: 'Gira los discos hasta que el 9 y el 4 queden bajo las flechas.',

    LEVEL_095_TITLE: 'HAZ DORMIR A RULI',
    LEVEL_095_HINT_1: 'La luz y el ruido molestan.',
    LEVEL_095_HINT_2: 'Y después... silencio.',
    LEVEL_095_HINT_3: 'Apaga la luz, guarda la radio en la caja y no toques nada durante 3 segundos.',

    LEVEL_096_TITLE: 'NO TOQUES NADA',
    LEVEL_096_HINT_1: 'El jarrón va a caer.',
    LEVEL_096_HINT_2: '¿De verdad te necesita?',
    LEVEL_096_HINT_3: 'No toques nada. El cojín ya está ahí.',

    LEVEL_097_TITLE: 'HAZ QUE TODOS SEAN IGUALES',
    LEVEL_097_HINT_1: 'Iguales en todo.',
    LEVEL_097_HINT_2: 'Color y tamaño.',
    LEVEL_097_HINT_3: 'Pinta los tres del mismo color y déjalos del mismo tamaño.',

    LEVEL_098_TITLE: 'PINTA LA HOJA DE VERDE',
    LEVEL_098_HINT_1: 'No hay pintura verde.',
    LEVEL_098_HINT_2: 'Dos colores juntos hacen un tercero.',
    LEVEL_098_HINT_3: 'Junta la gota azul con la amarilla y lleva la verde a la hoja.',

    LEVEL_099_TITLE: 'ROMPE TODAS LAS REGLAS',
    LEVEL_099_HINT_1: 'Lee los carteles.',
    LEVEL_099_HINT_2: 'Haz lo contrario de cada uno.',
    LEVEL_099_HINT_3: 'Toca la estrella, mueve la caja y después espera.',

    LEVEL_100_TITLE: 'ESTA ES LA [[w_last|ÚLTIMA]] FASE',
    LEVEL_100_HINT_1: '¿Quién dijo que es la última?',
    LEVEL_100_HINT_2: 'La frase puede cambiar.',
    LEVEL_100_HINT_3: 'Saca la palabra ÚLTIMA de la frase.',
    UI_DEMO_END_TITLE: '¡COMPLETASTE LAS 100 FASES!',
    UI_DEMO_END_TEXT: 'MÁS FASES MUY PRONTO'
  }
};
