// Português (Brasil). [[id|PALAVRA]] marca palavras que são objetos da fase.
RULES.L10N['pt-BR'] = {
  name: 'Português',
  strings: {
    UI_PLAY: 'JOGAR',
    UI_CONTINUE: 'CONTINUAR',
    UI_LEVELS: 'FASES',
    UI_SETTINGS: 'AJUSTES',
    UI_BACK: 'Voltar',
    UI_MENU: 'Menu',
    UI_LEVEL: 'FASE {n}',
    UI_HINT: 'DICA',
    UI_RESTART: 'REINICIAR',
    UI_HINTS_TITLE: 'DICAS',
    UI_HINT_MORE: 'MAIS UMA DICA',
    UI_HINT_LAST: 'ÚLTIMA DICA',
    UI_CLOSE: 'FECHAR',
    UI_ATTEMPTS: 'Tentativas: {n}',
    UI_COMPLETED: 'COMPLETA',
    UI_LOCKED: 'Bloqueada',
    UI_MUSIC: 'Música',
    UI_SFX: 'Efeitos sonoros',
    UI_VIBRATION: 'Vibração',
    UI_REDUCE_MOTION: 'Reduzir animações',
    UI_LANGUAGE: 'Idioma',
    UI_RESET: 'Apagar progresso',
    UI_RESET_CONFIRM: 'Toque de novo para apagar',
    UI_RESET_DONE: 'Progresso apagado',
    UI_TAGLINE: 'Leia. Pense. Duvide.',
    UI_BY: 'um jogo de @xadrezcomz',
    UI_MORE_GAMES: 'Mais jogos',
    UI_DEMO_END_TITLE: 'VOCÊ JÁ CONHECE AS PRIMEIRAS REGRAS',
    UI_DEMO_END_TEXT: 'MAIS FASES EM BREVE',
    UI_SKIP: 'toque para continuar',

    CHAPTER_LABEL: 'CAPÍTULO {n}',
    CHAPTER_1: 'APRENDA AS REGRAS',
    CHAPTER_2: 'NÃO CONFIE NAS REGRAS',
    CHAPTER_3: 'MEXA EM TUDO',
    CHAPTER_4: 'PENSE DIFERENTE',
    CHAPTER_5: 'QUEBRE AS REGRAS',

    SUCCESS_1: 'BOA!',
    SUCCESS_2: 'CONSEGUIU!',
    SUCCESS_3: 'ISSO!',

    FB_ALMOST: 'QUASE!',
    FB_TRY_DIFFERENT: 'TENTE DIFERENTE',
    FB_HMM: 'HMMM...',
    FB_NOT_THIS_TIME: 'NÃO FOI DESSA VEZ',
    FB_NOFIT: 'NÃO CABE...',
    FB_TOO_BIG: 'GRANDE DEMAIS...',
    FB_OOPS: 'OPA! QUASE!',
    FB_AGAIN: 'DO COMEÇO...',

    LEVEL_001_TITLE: 'TOQUE NO CÍRCULO',
    LEVEL_001_HINT_1: 'Às vezes a resposta é exatamente o que parece.',
    LEVEL_001_HINT_2: 'O círculo está bem no meio da tela.',
    LEVEL_001_HINT_3: 'Toque uma vez no círculo.',

    LEVEL_002_TITLE: 'LEVE A BOLA ATÉ A CAIXA',
    LEVEL_002_HINT_1: 'As coisas podem sair do lugar.',
    LEVEL_002_HINT_2: 'Encoste o dedo na bola e não solte.',
    LEVEL_002_HINT_3: 'Arraste a bola e solte dentro da caixa.',

    LEVEL_003_TITLE: 'ABRA A PORTA',
    LEVEL_003_HINT_1: 'Nem toda porta abre do mesmo jeito.',
    LEVEL_003_HINT_2: 'Bater não adianta. Talvez ela deslize...',
    LEVEL_003_HINT_3: 'Arraste a porta para o lado.',

    LEVEL_005_TITLE: 'COLOQUE O CÍRCULO NO QUADRADO',
    LEVEL_005_HINT_1: 'O tamanho das coisas pode mudar.',
    LEVEL_005_HINT_2: 'O círculo precisa ficar menor que o quadrado.',
    LEVEL_005_HINT_3: 'Use dois dedos (ou a rodinha do mouse) para diminuir o círculo. Depois arraste.',

    LEVEL_009_TITLE: 'COLOQUE [[w_all|TUDO]] NA CAIXA',
    LEVEL_009_HINT_1: 'Tudo é tudo mesmo.',
    LEVEL_009_HINT_2: 'Olhe de novo para a instrução.',
    LEVEL_009_HINT_3: 'Arraste a palavra TUDO para dentro da caixa.',

    LEVEL_010_TITLE: 'NÃO TOQUE EM NADA',
    LEVEL_010_HINT_1: 'Às vezes, a melhor jogada é não jogar.',
    LEVEL_010_HINT_2: 'Leia a instrução ao pé da letra.',
    LEVEL_010_HINT_3: 'Feche esta dica e não toque na tela por 3 segundos.',

    LEVEL_011_TITLE: 'PEGUE A CHAVE',
    LEVEL_011_HINT_1: 'Se você não pode ir até ela...',
    LEVEL_011_HINT_2: 'A chave só foge do Ruli.',
    LEVEL_011_HINT_3: 'Arraste a chave até o Ruli.',

    LEVEL_012_TITLE: 'CHEGUE À PORTA',
    LEVEL_012_HINT_1: 'O caminho não precisa ser seu.',
    LEVEL_012_HINT_2: 'Ruli não pula. Mas outra coisa aqui se mexe.',
    LEVEL_012_HINT_3: 'Arraste a porta até o Ruli.',

    LEVEL_016_TITLE: 'COLOQUE A BOLA NA CAIXA',
    LEVEL_016_HINT_1: 'Se a bola não diminui...',
    LEVEL_016_HINT_2: 'Talvez o problema seja a caixa.',
    LEVEL_016_HINT_3: 'Use dois dedos (ou a rodinha do mouse) para aumentar a caixa. Depois arraste a bola.',

    LEVEL_020_TITLE: 'ESPERE.',
    LEVEL_020_HINT_1: 'Paciência também é uma regra.',
    LEVEL_020_HINT_2: 'Cada toque recomeça a contagem.',
    LEVEL_020_HINT_3: 'Feche esta dica e não toque em nada por 5 segundos.'
  }
};
