// Português (Brasil). [[id|PALAVRA]] marca palavras que são objetos da fase.
RULES.L10N['pt-BR'] = {
  name: 'Português',
  strings: {
    UI_PLAY: 'JOGAR',
    UI_CONTINUE: 'CONTINUAR',
    UI_LEVELS: 'FASES',
    UI_SETTINGS: 'AJUSTES',
    UI_BACK: 'Voltar',
    UI_MENU: 'Menu',
    UI_LEVEL: 'FASE {n}',
    UI_HINT: 'DICA',
    UI_RESTART: 'REINICIAR',
    UI_HINTS_TITLE: 'DICAS',
    UI_HINT_MORE: 'MAIS UMA DICA',
    UI_HINT_LAST: 'ÚLTIMA DICA',
    UI_CLOSE: 'FECHAR',
    UI_ATTEMPTS: 'Tentativas: {n}',
    UI_COMPLETED: 'COMPLETA',
    UI_LOCKED: 'Bloqueada',
    UI_MUSIC: 'Música',
    UI_SFX: 'Efeitos sonoros',
    UI_VIBRATION: 'Vibração',
    UI_REDUCE_MOTION: 'Reduzir animações',
    UI_LANGUAGE: 'Idioma',
    UI_RESET: 'Apagar progresso',
    UI_RESET_CONFIRM: 'Toque de novo para apagar',
    UI_RESET_DONE: 'Progresso apagado',
    UI_TAGLINE: 'Leia. Pense. Duvide.',
    UI_BY: 'um jogo de @xadrezcomz',
    UI_MORE_GAMES: 'Mais jogos',
    UI_SKIP: 'toque para continuar',

    CHAPTER_LABEL: 'CAPÍTULO {n}',
    CHAPTER_1: 'APRENDA AS REGRAS',
    CHAPTER_2: 'NÃO CONFIE NAS REGRAS',
    CHAPTER_3: 'MEXA EM TUDO',
    CHAPTER_4: 'PENSE DIFERENTE',
    CHAPTER_5: 'QUEBRE AS REGRAS',

    SUCCESS_1: 'BOA!',
    SUCCESS_2: 'CONSEGUIU!',
    SUCCESS_3: 'ISSO!',

    FB_ALMOST: 'QUASE!',
    FB_TRY_DIFFERENT: 'TENTE DIFERENTE',
    FB_HMM: 'HMMM...',
    FB_NOT_THIS_TIME: 'NÃO FOI DESSA VEZ',
    FB_NOFIT: 'NÃO CABE...',
    FB_TOO_BIG: 'GRANDE DEMAIS...',
    FB_OOPS: 'OPA! QUASE!',
    FB_AGAIN: 'DO COMEÇO...',

    LEVEL_001_TITLE: 'TOQUE NO CÍRCULO',
    LEVEL_001_HINT_1: 'Às vezes a resposta é exatamente o que parece.',
    LEVEL_001_HINT_2: 'O círculo está bem no meio da tela.',
    LEVEL_001_HINT_3: 'Toque uma vez no círculo.',

    LEVEL_002_TITLE: 'LEVE A BOLA ATÉ A CAIXA',
    LEVEL_002_HINT_1: 'As coisas podem sair do lugar.',
    LEVEL_002_HINT_2: 'Encoste o dedo na bola e não solte.',
    LEVEL_002_HINT_3: 'Arraste a bola e solte dentro da caixa.',

    LEVEL_003_TITLE: 'ABRA A PORTA',
    LEVEL_003_HINT_1: 'Nem toda porta abre do mesmo jeito.',
    LEVEL_003_HINT_2: 'Bater não adianta. Talvez ela deslize...',
    LEVEL_003_HINT_3: 'Arraste a porta para o lado.',

    LEVEL_005_TITLE: 'COLOQUE O CÍRCULO NO QUADRADO',
    LEVEL_005_HINT_1: 'O tamanho das coisas pode mudar.',
    LEVEL_005_HINT_2: 'O círculo precisa ficar menor que o quadrado.',
    LEVEL_005_HINT_3: 'Use dois dedos (ou a rodinha do mouse) para diminuir o círculo. Depois arraste.',

    LEVEL_009_TITLE: 'COLOQUE [[w_all|TUDO]] NA CAIXA',
    LEVEL_009_HINT_1: 'Tudo é tudo mesmo.',
    LEVEL_009_HINT_2: 'Olhe de novo para a instrução.',
    LEVEL_009_HINT_3: 'Arraste a palavra TUDO para dentro da caixa.',

    LEVEL_010_TITLE: 'NÃO TOQUE EM NADA',
    LEVEL_010_HINT_1: 'Às vezes, a melhor jogada é não jogar.',
    LEVEL_010_HINT_2: 'Leia a instrução ao pé da letra.',
    LEVEL_010_HINT_3: 'Feche esta dica e não toque na tela por 3 segundos.',

    LEVEL_011_TITLE: 'PEGUE A CHAVE',
    LEVEL_011_HINT_1: 'Se você não pode ir até ela...',
    LEVEL_011_HINT_2: 'A chave só foge do Ruli.',
    LEVEL_011_HINT_3: 'Arraste a chave até o Ruli.',

    LEVEL_012_TITLE: 'CHEGUE À PORTA',
    LEVEL_012_HINT_1: 'O caminho não precisa ser seu.',
    LEVEL_012_HINT_2: 'Ruli não pula. Mas outra coisa aqui se mexe.',
    LEVEL_012_HINT_3: 'Arraste a porta até o Ruli.',

    LEVEL_016_TITLE: 'COLOQUE A BOLA NA CAIXA',
    LEVEL_016_HINT_1: 'Se a bola não diminui...',
    LEVEL_016_HINT_2: 'Talvez o problema seja a caixa.',
    LEVEL_016_HINT_3: 'Use dois dedos (ou a rodinha do mouse) para aumentar a caixa. Depois arraste a bola.',

    LEVEL_020_TITLE: 'ESPERE.',
    LEVEL_020_HINT_1: 'Paciência também é uma regra.',
    LEVEL_020_HINT_2: 'Cada toque recomeça a contagem.',
    LEVEL_020_HINT_3: 'Feche esta dica e não toque em nada por 5 segundos.',
    FB_PRESSED: 'VOCÊ APERTOU!',
    FB_DONT_MOVE: 'NÃO É PARA MOVER O RULI!',
    FB_BIGGER: 'TEM UM MAIOR...',
    FB_SAME: 'ESSE É IGUAL...',
    FB_NOT_BLUE: 'ISSO NÃO É AZUL',
    FB_SERIOUS: 'RULI CONTINUA SÉRIO',
    FB_OLDEST: 'A MAIS ANTIGA APAGOU',
    FB_NOT_UP: 'ELA NÃO SOBE...',

    LEVEL_004_TITLE: 'ACENDA A LUZ',
    LEVEL_004_HINT_1: 'Toda lâmpada tem um jeito de acender.',
    LEVEL_004_HINT_2: 'A lâmpada não liga sozinha.',
    LEVEL_004_HINT_3: 'Toque no interruptor.',

    LEVEL_006_TITLE: 'ENCONTRE A ESTRELA',
    LEVEL_006_HINT_1: 'Nem tudo está à vista.',
    LEVEL_006_HINT_2: 'Um dos círculos não está preso.',
    LEVEL_006_HINT_3: 'Arraste o círculo vermelho e toque na estrela.',

    LEVEL_007_TITLE: 'FAÇA OS DOIS SE ENCONTRAREM',
    LEVEL_007_HINT_1: 'Encontro é coisa de dois.',
    LEVEL_007_HINT_2: 'Nenhum deles consegue ir até o fim sozinho.',
    LEVEL_007_HINT_3: 'Leve cada um até o meio.',

    LEVEL_008_TITLE: 'ENCHA O COPO',
    LEVEL_008_HINT_1: 'Água não pula da jarra sozinha.',
    LEVEL_008_HINT_2: 'Jarras precisam inclinar.',
    LEVEL_008_HINT_3: 'Segure a jarra logo acima do copo até encher.',

    LEVEL_013_TITLE: 'ENCONTRE O MAIOR CÍRCUL[[w_o|O]]',
    LEVEL_013_HINT_1: 'O maior pode não estar no meio das coisas.',
    LEVEL_013_HINT_2: 'Uma letra também é redonda.',
    LEVEL_013_HINT_3: 'Toque no último O da instrução.',

    LEVEL_014_TITLE: 'FAÇA O SOL APARECER',
    LEVEL_014_HINT_1: 'O sol nunca foi embora.',
    LEVEL_014_HINT_2: 'Alguma coisa está na frente dele.',
    LEVEL_014_HINT_3: 'Arraste a nuvem para longe do sol.',

    LEVEL_015_TITLE: 'NÃO APERTE O BOTÃO',
    LEVEL_015_HINT_1: 'Dá para mexer num botão sem apertar.',
    LEVEL_015_HINT_2: 'O que será que tem embaixo dele?',
    LEVEL_015_HINT_3: 'Arraste o botão para o lado e toque no que aparecer.',

    LEVEL_017_TITLE: 'ENCONTRE O DIFERENTE',
    LEVEL_017_HINT_1: 'Observe com calma.',
    LEVEL_017_HINT_2: 'Todos se mexem juntos... quase todos.',
    LEVEL_017_HINT_3: 'Um deles fica grande quando os outros ficam pequenos. Toque nele.',

    LEVEL_018_TITLE: 'ACENDA TODAS AS LUZES',
    LEVEL_018_HINT_1: 'Só duas aguentam ficar acesas. A mais antiga sempre apaga.',
    LEVEL_018_HINT_2: 'E se duas fossem ligadas exatamente ao mesmo tempo? Os interruptores também saem do lugar.',
    LEVEL_018_HINT_3: 'Arraste um interruptor para cima de outro e toque na pilha: os dois ligam juntos. Depois ligue o terceiro. (Com dois dedos, também dá para tocar em dois ao mesmo tempo.)',

    LEVEL_019_TITLE: 'NÃO DEIXE A BOLA CAIR',
    LEVEL_019_HINT_1: 'A bola não vai ficar parada para sempre.',
    LEVEL_019_HINT_2: 'Ela precisa de algo embaixo.',
    LEVEL_019_HINT_3: 'Arraste a plataforma para baixo da bola antes que ela caia.',

    LEVEL_021_TITLE: 'ENCONTRE A SAÍDA',
    LEVEL_021_HINT_1: 'Paredes também são coisas.',
    LEVEL_021_HINT_2: 'Uma parede pode esconder o que está atrás.',
    LEVEL_021_HINT_3: 'Arraste a parede e toque na porta.',

    LEVEL_022_TITLE: 'FAÇA 2 + 2 = 5',
    LEVEL_022_HINT_1: 'A matemática não muda. Os números, sim.',
    LEVEL_022_HINT_2: 'Um traço está meio torto, quase solto.',
    LEVEL_022_HINT_3: 'Mova o traço torto do segundo 2 para a direita: o 2 vira 3.',

    LEVEL_023_TITLE: 'COLOQUE O PEIXE NA ÁGUA',
    LEVEL_023_HINT_1: 'Esse copo é pequeno para um peixe.',
    LEVEL_023_HINT_2: 'Lembra da caixa da bola?',
    LEVEL_023_HINT_3: 'Aumente o copo com dois dedos (ou a rodinha do mouse) e depois coloque o peixe.',

    LEVEL_024_TITLE: 'ENCONTRE O [[w_blue|AZUL]]',
    LEVEL_024_HINT_1: 'Procure em todo lugar, até fora do cenário.',
    LEVEL_024_HINT_2: 'Nenhum objeto é azul.',
    LEVEL_024_HINT_3: 'Toque na palavra AZUL.',

    LEVEL_025_TITLE: 'FAÇA RULI SORRIR',
    LEVEL_025_HINT_1: 'Ruli é sério, mas tem um ponto fraco.',
    LEVEL_025_HINT_2: 'Cócegas!',
    LEVEL_025_HINT_3: 'Esfregue o Ruli rápido, de um lado para o outro (com o dedo ou com a pena).',

    LEVEL_026_TITLE: 'ORGANIZE DO [[w_min|MENOR]] PARA O [[w_max|MAIOR]]',
    LEVEL_026_HINT_1: 'Conte os lugares.',
    LEVEL_026_HINT_2: 'Cinco lugares, três círculos. O que falta?',
    LEVEL_026_HINT_3: 'Coloque MENOR no primeiro lugar, os círculos em ordem e MAIOR no último.',

    LEVEL_027_TITLE: '[[w_open|ABRA]] A CAIXA',
    LEVEL_027_HINT_1: 'Essa caixa não tem tampa nem fechadura.',
    LEVEL_027_HINT_2: 'Você precisa de uma ferramenta. Ela está escrita.',
    LEVEL_027_HINT_3: 'Arraste a palavra ABRA até a caixa.',

    LEVEL_028_TITLE: 'LEVE A ESTRELA PARA [[w_up|CIMA]]',
    LEVEL_028_HINT_1: 'A estrela é pesada demais.',
    LEVEL_028_HINT_2: 'Se ela não vai para cima...',
    LEVEL_028_HINT_3: 'Arraste a palavra CIMA até a estrela.',

    LEVEL_029_TITLE: 'FAÇA CHOVER',
    LEVEL_029_HINT_1: 'Nuvens precisam juntar água.',
    LEVEL_029_HINT_2: 'Tocar só uma vez não basta.',
    LEVEL_029_HINT_3: 'Esfregue a nuvem até ela ficar bem escura.',

    LEVEL_030_TITLE: 'NÃO MOVA RULI',
    LEVEL_030_HINT_1: 'Se Ruli não vai até a porta...',
    LEVEL_030_HINT_2: 'O chão também é um objeto.',
    LEVEL_030_HINT_3: 'Arraste o chão para a esquerda até a porta chegar no Ruli.',
    FB_ONLY_TWO: 'SÓ DOIS...',
    FB_THIRSTY: 'ELA ESTÁ COM SEDE...',
    FB_GLUG: 'GLUB GLUB!',
    FB_NOTHING: 'NADA AQUI...',
    FB_HEAVY: 'PESADA DEMAIS...',
    FB_NOT_SAME: 'NÃO SÃO IGUAIS...',
    FB_TICTAC: 'TIC... TAC...',
    FB_TIRED: 'RULI ESTÁ CANSADO',
    FB_GREEN: 'É VERDE!',
    FB_FIXED: 'ESSES NÃO SE MEXEM',
    FB_WRONG: 'ERRADO...',
    FB_LOCKED: 'TRANCADA',
    FB_UNLOCKED: 'CLIQUE!',
    FB_ORDER: 'FORA DE ORDEM',
    FB_AGAIN_WATCH: 'OLHE DE NOVO...',
    FINALE_1: 'AGORA VOCÊ CONHECE AS',
    FINALE_WORD: 'REGRAS.',
    FINALE_2: '...OU NÃO. 😉',
    CHAPTER_6: 'A TELA TAMBÉM JOGA',
    CHAPTER_7: 'PALAVRAS QUE MUDAM TUDO',
    CHAPTER_8: 'FÍSICA DE BRINQUEDO',
    CHAPTER_9: 'OLHE DE NOVO',
    CHAPTER_10: 'FORA DA CAIXA',
    LEVEL_046_WORD: 'NADA',
    LEVEL_048_Q: '2 + 3 = ?',
    LEVEL_049_SIGN: 'NÃO MOVA A PORTA',

    LEVEL_031_TITLE: 'ENCONTRE 3 TRIÂNGULOS',
    LEVEL_031_HINT_1: 'Dois é fácil. E o terceiro?',
    LEVEL_031_HINT_2: 'Duas metades fazem um inteiro.',
    LEVEL_031_HINT_3: 'Junte as duas metades roxas.',

    LEVEL_032_TITLE: 'ATRAVESSE A PONTE',
    LEVEL_032_HINT_1: 'Essa ponte não chega do outro lado.',
    LEVEL_032_HINT_2: 'Pontes também podem crescer... para o lado.',
    LEVEL_032_HINT_3: 'Estique a ponte com dois dedos (ou a rodinha do mouse) e depois leve o Ruli.',

    LEVEL_033_TITLE: 'COLOQUE 5 BOLAS NA CAIXA',
    LEVEL_033_HINT_1: 'Conte as bolas.',
    LEVEL_033_HINT_2: 'Só tem quatro. Uma delas pode virar duas?',
    LEVEL_033_HINT_3: 'Estique a bola verde com dois dedos (ou a rodinha do mouse) até ela se dividir.',

    LEVEL_034_TITLE: 'DEIXE [[w_all|TUDO]] PEQUENO',
    LEVEL_034_HINT_1: 'Tudo mesmo.',
    LEVEL_034_HINT_2: 'Ainda tem algo grande na tela.',
    LEVEL_034_HINT_3: 'Diminua também a palavra TUDO com dois dedos (ou a rodinha do mouse).',

    LEVEL_035_TITLE: 'FAÇA A PLANTA CRESCER',
    LEVEL_035_HINT_1: 'Plantas precisam de duas coisas.',
    LEVEL_035_HINT_2: 'A ordem importa.',
    LEVEL_035_HINT_3: 'Leve primeiro o regador até a planta. Depois o sol.',

    LEVEL_036_TITLE: '[[w_all|ENCONTRE O QUE ESTÁ ESCONDIDO]]',
    LEVEL_036_HINT_1: 'Não está atrás das caixas.',
    LEVEL_036_HINT_2: 'Alguma coisa está na frente de tudo.',
    LEVEL_036_HINT_3: 'Arraste a própria instrução e toque no que aparecer.',

    LEVEL_037_TITLE: 'COLOQUE A LUA NO CÉU',
    LEVEL_037_HINT_1: 'A lua não sobe.',
    LEVEL_037_HINT_2: 'Se ela não vai até o céu...',
    LEVEL_037_HINT_3: 'Arraste o céu para baixo até a lua ficar dentro dele.',

    LEVEL_038_TITLE: 'JUNTE OS IGUAIS',
    LEVEL_038_HINT_1: 'Eles são iguais em tudo, menos em uma coisa.',
    LEVEL_038_HINT_2: 'Iguais precisam ter o mesmo tamanho.',
    LEVEL_038_HINT_3: 'Deixe os dois círculos do mesmo tamanho (dois dedos ou rodinha) e junte um no outro.',

    LEVEL_039_TITLE: 'FAÇA O RELÓGIO ANDAR MAIS RÁPIDO',
    LEVEL_039_HINT_1: 'Relógios não aceitam pressa.',
    LEVEL_039_HINT_2: 'Mas os ponteiros aceitam um empurrão.',
    LEVEL_039_HINT_3: 'Gire o ponteiro grande com o dedo, duas voltas.',

    LEVEL_040_TITLE: 'CHEGUE AO [[w_final|FINAL]]',
    LEVEL_040_HINT_1: 'O caminho é longo demais para o Ruli.',
    LEVEL_040_HINT_2: 'Talvez o final possa vir até ele.',
    LEVEL_040_HINT_3: 'Arraste a palavra FINAL até o Ruli.',

    LEVEL_041_TITLE: 'NÃO TOQUE NO VERDE',
    LEVEL_041_HINT_1: 'O verde é o problema.',
    LEVEL_041_HINT_2: 'E se ele não fosse mais verde?',
    LEVEL_041_HINT_3: 'Leve a tinta azul até o círculo verde e depois toque nele.',

    LEVEL_042_TITLE: 'COLOQUE A ESTRELA FORA DA CAIXA',
    LEVEL_042_HINT_1: 'A caixa não abre.',
    LEVEL_042_HINT_2: 'Dentro e fora dependem do tamanho.',
    LEVEL_042_HINT_3: 'Aumente a estrela (dois dedos ou rodinha) até a caixa ficar dentro dela.',

    LEVEL_043_TITLE: 'FAÇA OS DOIS LADOS FICAREM IGUAIS',
    LEVEL_043_HINT_1: 'Os círculos não saem do lugar.',
    LEVEL_043_HINT_2: 'O que define os lados?',
    LEVEL_043_HINT_3: 'Arraste a linha até ficarem três círculos de cada lado.',

    LEVEL_044_TITLE: 'ENCONTRE A PORTA',
    LEVEL_044_HINT_1: 'Não existe porta. Ainda.',
    LEVEL_044_HINT_2: 'Formas podem montar coisas.',
    LEVEL_044_HINT_3: 'Leve o retângulo roxo até o contorno e a bolinha amarela até a maçaneta.',

    LEVEL_045_TITLE: 'FAÇA RULI CHEGAR MAIS ALTO',
    LEVEL_045_HINT_1: 'A escada é pequena demais.',
    LEVEL_045_HINT_2: 'Caixas podem virar degraus.',
    LEVEL_045_HINT_3: 'Empilhe as três caixas embaixo da estrela e coloque o Ruli em cima.',

    LEVEL_046_TITLE: 'NÃO DEIXE NADA NO CHÃO',
    LEVEL_046_HINT_1: 'Olhe bem para o chão.',
    LEVEL_046_HINT_2: 'Tem uma palavra escondida lá embaixo.',
    LEVEL_046_HINT_3: 'Leve também a palavrinha NADA para cima.',

    LEVEL_047_TITLE: 'FAÇA O DIA VIRAR NOITE',
    LEVEL_047_HINT_1: 'Quando é que a noite chega?',
    LEVEL_047_HINT_2: 'O sol precisa ir embora.',
    LEVEL_047_HINT_3: 'Arraste o sol para baixo do horizonte.',

    LEVEL_048_TITLE: 'ENCONTRE A [[w_ans|RESPOSTA]]',
    LEVEL_048_HINT_1: 'Nenhum desses números serve.',
    LEVEL_048_HINT_2: 'A resposta está escrita.',
    LEVEL_048_HINT_3: 'Arraste a palavra RESPOSTA até o espaço vazio.',

    LEVEL_049_TITLE: 'QUEBRE A REGRA',
    LEVEL_049_HINT_1: 'Leia a placa.',
    LEVEL_049_HINT_2: 'A instrução manda quebrar.',
    LEVEL_049_HINT_3: 'Mova a porta.',

    LEVEL_050_TITLE: 'VOCÊ JÁ SABE O QUE FAZER',
    LEVEL_050_HINT_1: 'Tudo o que você aprendeu vale aqui.',
    LEVEL_050_HINT_2: 'A porta está trancada. O que abre portas?',
    LEVEL_050_HINT_3: 'Tire a caixa, leve a chave até a porta e depois leve o Ruli até ela.',
    FB_HELP: 'PRECISA DE AJUDA?',
    FB_READING: 'ESTOU LENDO...',
    FB_SEEN: 'AINDA DÁ PARA VER O RULI',
    FB_NOT_ALLOWED: 'NÃO PODE!',
    FB_NOT_SEVEN: 'ESSE NÃO É 7',
    FB_PAINTING: 'É SÓ UM QUADRO',
    FB_SPLASH: 'TCHIBUM!',
    FB_ALREADY_DAY: 'JÁ É DIA...',
    FB_ROUND: 'ISSO É REDONDO',
    FB_BACKWARDS: 'AQUI É A PORTA QUE ABRE A CHAVE...',
    FB_MAKES_SENSE: 'AGORA FAZ SENTIDO!',
    LEVEL_054_LABEL: '[[w_fase|FASE]] 54',
    LEVEL_057_LABEL: 'FASE 5[[w_seven|7]]',
    LEVEL_059_LABEL: 'FASE [[w_five|5]]9',
    LEVEL_061_L1: 'G',
    LEVEL_061_L2: 'A',
    LEVEL_061_L3: 'T',
    LEVEL_061_L4: 'O',
    LEVEL_061_NEW: 'P',
    LEVEL_061_DECOY: 'R',
    LEVEL_066_A: 'S',
    LEVEL_066_B: 'O',
    LEVEL_066_C: 'L',
    LEVEL_066_X1: 'A',
    LEVEL_066_X2: 'R',

    LEVEL_051_TITLE: 'PEÇA AJUDA',
    LEVEL_051_HINT_1: 'Isso. Você pediu ajuda. Feche esta janela.',
    LEVEL_051_HINT_2: 'Era só isso mesmo.',
    LEVEL_051_HINT_3: 'Pedir ajuda também é uma jogada.',

    LEVEL_052_TITLE: 'TENTE OUTRA VEZ',
    LEVEL_052_HINT_1: 'Às vezes, não dá na primeira.',
    LEVEL_052_HINT_2: 'A instrução diz exatamente o que fazer.',
    LEVEL_052_HINT_3: 'Toque em REINICIAR.',

    LEVEL_053_TITLE: 'NÃO LEIA ISTO',
    LEVEL_053_HINT_1: 'Difícil não ler, né?',
    LEVEL_053_HINT_2: 'E se a frase sumisse da sua frente?',
    LEVEL_053_HINT_3: 'Arraste o papel para cima da instrução.',

    LEVEL_054_TITLE: 'COLOQUE A FASE NA CAIXA',
    LEVEL_054_HINT_1: 'A estrela não é a fase.',
    LEVEL_054_HINT_2: 'Olhe para o topo da tela.',
    LEVEL_054_HINT_3: 'Arraste a palavra FASE, lá em cima, até a caixa.',

    LEVEL_055_TITLE: 'ESCONDA O RULI',
    LEVEL_055_HINT_1: 'Atrás da árvore ainda aparece.',
    LEVEL_055_HINT_2: 'Tem uma coisa bem grande na tela que não é do cenário.',
    LEVEL_055_HINT_3: 'Arraste o Ruli para trás da instrução.',

    LEVEL_056_TITLE: '[[w_not|NÃO]] TOQUE NA ESTRELA',
    LEVEL_056_HINT_1: 'A frase manda não tocar.',
    LEVEL_056_HINT_2: 'E se a frase mudasse?',
    LEVEL_056_HINT_3: 'Tire a palavra NÃO da frase e depois toque na estrela.',

    LEVEL_057_TITLE: 'ENCONTRE O 7',
    LEVEL_057_HINT_1: 'Conte as cartas.',
    LEVEL_057_HINT_2: 'Nenhuma carta é 7. Mas o 7 está na tela.',
    LEVEL_057_HINT_3: 'Toque no 7 de "FASE 57", lá em cima.',

    LEVEL_058_TITLE: 'COLOQUE O [[w_g|GIGANTE]] NA CAIXA',
    LEVEL_058_HINT_1: 'A bola não é o gigante.',
    LEVEL_058_HINT_2: 'O gigante é grande demais para a caixa.',
    LEVEL_058_HINT_3: 'Diminua a palavra GIGANTE (dois dedos ou rodinha) e arraste até a caixa.',

    LEVEL_059_TITLE: 'TOQUE DO 1 AO 5',
    LEVEL_059_HINT_1: 'Procure o 5.',
    LEVEL_059_HINT_2: 'Ele não está entre as cartas.',
    LEVEL_059_HINT_3: 'Toque 1, 2, 3, 4 e depois no 5 de "FASE 59".',

    LEVEL_060_TITLE: 'LEVE O [[w_ruli|RULI]] ATÉ A PORTA',
    LEVEL_060_HINT_1: 'Esse Ruli não se mexe.',
    LEVEL_060_HINT_2: 'Ele é só um quadro na parede.',
    LEVEL_060_HINT_3: 'Arraste a palavra RULI até a porta.',

    LEVEL_061_TITLE: 'FAÇA O GATO VIRAR PATO',
    LEVEL_061_HINT_1: 'Uma letra faz toda a diferença.',
    LEVEL_061_HINT_2: 'GATO e PATO só mudam no começo.',
    LEVEL_061_HINT_3: 'Solte a letra P em cima do G.',

    LEVEL_062_TITLE: 'USE A [[w_bridge|PONTE]]',
    LEVEL_062_HINT_1: 'Não tem ponte nenhuma.',
    LEVEL_062_HINT_2: 'A ponte está escrita.',
    LEVEL_062_HINT_3: 'Arraste a palavra PONTE até o rio e depois leve o Ruli.',

    LEVEL_063_TITLE: 'PINTE O CÉU DE [[w_blue|AZUL]]',
    LEVEL_063_HINT_1: 'Vermelho e amarelo não fazem azul aqui.',
    LEVEL_063_HINT_2: 'Onde mais tem azul?',
    LEVEL_063_HINT_3: 'Arraste a palavra AZUL até o céu.',

    LEVEL_064_TITLE: 'FAÇA O [[w_small|PEQUENO]] FICAR GRANDE',
    LEVEL_064_HINT_1: 'A bola não cresce.',
    LEVEL_064_HINT_2: 'Pequeno quem?',
    LEVEL_064_HINT_3: 'Aumente a palavra PEQUENO com dois dedos (ou a rodinha do mouse).',

    LEVEL_065_TITLE: 'FAÇA 1 + 1 = 1',
    LEVEL_065_HINT_1: 'Nem sempre um mais um dá dois.',
    LEVEL_065_HINT_2: 'Gotas d\'água gostam de se juntar.',
    LEVEL_065_HINT_3: 'Junte uma gota na outra.',

    LEVEL_066_TITLE: 'ESCREVA O NOME DISTO',
    LEVEL_066_HINT_1: 'Olhe para o desenho.',
    LEVEL_066_HINT_2: 'Três letras bastam.',
    LEVEL_066_HINT_3: 'Monte a palavra SOL nos três espaços.',

    LEVEL_067_TITLE: 'APAGUE O [[w_x|X]]',
    LEVEL_067_HINT_1: 'Borrachas apagam esfregando.',
    LEVEL_067_HINT_2: 'Tem mais de um X na tela.',
    LEVEL_067_HINT_3: 'Esfregue o X grande e também o X da instrução.',

    LEVEL_068_TITLE: 'TROQUE O [[w_day|DIA]] PELA [[w_night|NOITE]]',
    LEVEL_068_HINT_1: 'O dia já está aí.',
    LEVEL_068_HINT_2: 'A noite está escrita.',
    LEVEL_068_HINT_3: 'Leve a palavra NOITE até o sol.',

    LEVEL_069_TITLE: '[[w_all|TOQUE NO QUE NÃO É REDONDO]]',
    LEVEL_069_HINT_1: 'Tudo no cenário é redondo.',
    LEVEL_069_HINT_2: 'Mas nem tudo na tela.',
    LEVEL_069_HINT_3: 'Toque na própria instrução.',

    LEVEL_070_TITLE: 'A [[w_a|PORTA]] ABRE A [[w_b|CHAVE]]',
    LEVEL_070_HINT_1: 'Essa frase está estranha.',
    LEVEL_070_HINT_2: 'E se as palavras trocassem de lugar?',
    LEVEL_070_HINT_3: 'Solte PORTA em cima de CHAVE. Depois leve a chave até a porta.',
    FB_FLEW: 'O BALÃO FUGIU!',
    FB_TOO_DEEP: 'FUNDO DEMAIS...',
    FB_TOO_HIGH: 'A CESTA É ALTA DEMAIS',
    FB_GLASS: 'TEM UM VIDRO AQUI',
    FB_GLUED: 'ESTÃO COLADOS',
    FB_NEEDS_SLOPE: 'ELA PRECISA DE UMA DESCIDA',
    FB_NEEDS_HEAT: 'PRECISA DE CALOR',
    FB_MELTED: 'DERRETEU!',
    FB_HOT: 'QUE CALOR...',
    FB_WHICH: 'QUAL SERÁ?',
    FB_SAME_AS_BEFORE: 'ESSE NÃO MUDOU',
    FB_WAIT_WATCH: 'ESPERE E OBSERVE...',
    FB_COUNT_AGAIN: 'CONTE DE NOVO',
    FB_NOT_MATCH: 'NÃO É ESSA SOMBRA',
    FB_NOT_GREEN: 'AINDA NÃO ESTÁ VERDE',
    FB_LIGHT: 'ESSA É LEVE',
    FB_NOT_HERE: 'NÃO ESTÁ AQUI',
    FB_SPIN_IT: 'GIRE O DISCO',
    FB_AWAKE: 'ASSIM ELE ACORDA!',
    FB_CRASH: 'CRASH!',
    FB_NOT_GREEN_YET: 'ISSO NÃO É VERDE',
    FB_BYE: 'TCHAU?',
    FB_THE_END: 'É O FIM...',
    LEVEL_099_S1: 'NÃO TOQUE NA ESTRELA',
    LEVEL_099_S2: 'NÃO MOVA A CAIXA',
    LEVEL_099_S3: 'NÃO ESPERE',
    LEVEL_100_SIGN: 'FIM',

    LEVEL_071_TITLE: 'NÃO DEIXE O BALÃO FUGIR',
    LEVEL_071_HINT_1: 'Segurar cansa.',
    LEVEL_071_HINT_2: 'Balões costumam ficar amarrados em algo pesado.',
    LEVEL_071_HINT_3: 'Arraste o balão até a pedra.',

    LEVEL_072_TITLE: 'EQUILIBRE A BALANÇA',
    LEVEL_072_HINT_1: 'As bolas não pesam o suficiente.',
    LEVEL_072_HINT_2: 'Equilibrar não é só colocar coisas.',
    LEVEL_072_HINT_3: 'Tire a pedra do prato.',

    LEVEL_073_TITLE: 'PEGUE A CHAVE',
    LEVEL_073_HINT_1: 'A chave está no fundo demais.',
    LEVEL_073_HINT_2: 'O que faz a água subir?',
    LEVEL_073_HINT_3: 'Jogue as pedras no copo até a chave subir, depois pegue-a.',

    LEVEL_074_TITLE: 'COLOQUE A BOLA NA CESTA',
    LEVEL_074_HINT_1: 'A cesta é alta demais para levar a bola.',
    LEVEL_074_HINT_2: 'Você conhece gangorras?',
    LEVEL_074_HINT_3: 'Solte a pedra na ponta direita da gangorra.',

    LEVEL_075_TITLE: 'PEGUE O CLIPE',
    LEVEL_075_HINT_1: 'O vidro não abre.',
    LEVEL_075_HINT_2: 'Algumas coisas puxam metal de longe.',
    LEVEL_075_HINT_3: 'Leve o ímã para perto do vidro.',

    LEVEL_076_TITLE: 'DERRUBE A TORRE',
    LEVEL_076_HINT_1: 'Os blocos estão colados.',
    LEVEL_076_HINT_2: 'E se o chão tremesse?',
    LEVEL_076_HINT_3: 'Esfregue o chão rápido, de um lado para o outro.',

    LEVEL_077_TITLE: 'FAÇA A BOLA ROLAR ATÉ O BURACO',
    LEVEL_077_HINT_1: 'A bola não rola para cima.',
    LEVEL_077_HINT_2: 'A rampa pode mudar de inclinação.',
    LEVEL_077_HINT_3: 'Gire a rampa até ela descer para a direita.',

    LEVEL_078_TITLE: 'ACENDA A FOGUEIRA',
    LEVEL_078_HINT_1: 'Fogo precisa de calor.',
    LEVEL_078_HINT_2: 'Atrito esquenta.',
    LEVEL_078_HINT_3: 'Esfregue o graveto na lenha (ou esfregue a lenha com o dedo).',

    LEVEL_079_TITLE: 'NÃO DEIXE O SORVETE DERRETER',
    LEVEL_079_HINT_1: 'O problema é o sol.',
    LEVEL_079_HINT_2: 'Sombra resolve.',
    LEVEL_079_HINT_3: 'Coloque a nuvem na frente do sol ou o guarda-chuva sobre o sorvete e espere.',

    LEVEL_080_TITLE: 'LEVE RULI ATÉ A ESTRELA',
    LEVEL_080_HINT_1: 'Pular não dá.',
    LEVEL_080_HINT_2: 'Algo aqui sobe sozinho.',
    LEVEL_080_HINT_3: 'Leve o balão até o Ruli.',

    LEVEL_081_TITLE: 'ENCONTRE A BOLA',
    LEVEL_081_HINT_1: 'Não precisa seguir os copos.',
    LEVEL_081_HINT_2: 'Copos podem ser levantados.',
    LEVEL_081_HINT_3: 'Arraste os copos para o lado e toque na bola.',

    LEVEL_082_TITLE: 'O QUE MUDOU?',
    LEVEL_082_HINT_1: 'Espere um pouco.',
    LEVEL_082_HINT_2: 'Depois da piscada, uma cor muda.',
    LEVEL_082_HINT_3: 'Toque no círculo do meio depois que a luz piscar.',

    LEVEL_083_TITLE: 'ACHE A CHAVE NO ESCURO',
    LEVEL_083_HINT_1: 'Está escuro demais.',
    LEVEL_083_HINT_2: 'Você tem uma lanterna.',
    LEVEL_083_HINT_3: 'Arraste a lanterna pela tela e toque na chave.',

    LEVEL_084_TITLE: 'QUANTAS ESTRELAS? TOQUE NO NÚMERO',
    LEVEL_084_HINT_1: 'Conte com calma.',
    LEVEL_084_HINT_2: 'Uma delas está escondida.',
    LEVEL_084_HINT_3: 'Tire a nuvem do lugar: são 5.',

    LEVEL_085_TITLE: 'COLOQUE O RULI NA SOMBRA DELE',
    LEVEL_085_HINT_1: 'As sombras não são iguais.',
    LEVEL_085_HINT_2: 'Olhe o broto e os braços.',
    LEVEL_085_HINT_3: 'A sombra certa é a da direita.',

    LEVEL_086_TITLE: 'TOQUE QUANDO FICAR VERDE',
    LEVEL_086_HINT_1: 'O verde dura pouco.',
    LEVEL_086_HINT_2: 'Observe o ritmo antes de tocar.',
    LEVEL_086_HINT_3: 'Toque no semáforo enquanto a luz verde estiver acesa.',

    LEVEL_087_TITLE: 'FAÇA O REFLEXO PEGAR A ESTRELA',
    LEVEL_087_HINT_1: 'O Ruli não atravessa o espelho.',
    LEVEL_087_HINT_2: 'O reflexo copia tudo... ao contrário.',
    LEVEL_087_HINT_3: 'Leve o Ruli para o alto à esquerda: o reflexo vai para o alto à direita.',

    LEVEL_088_TITLE: 'REPITA A SEQUÊNCIA',
    LEVEL_088_HINT_1: 'Preste atenção nas luzes.',
    LEVEL_088_HINT_2: 'São quatro piscadas.',
    LEVEL_088_HINT_3: 'Toque: meio, esquerda, direita, meio.',

    LEVEL_089_TITLE: 'TOQUE NA CAIXA MAIS PESADA',
    LEVEL_089_HINT_1: 'Por fora são todas iguais.',
    LEVEL_089_HINT_2: 'A balança sabe.',
    LEVEL_089_HINT_3: 'Coloque as caixas nos pratos e compare.',

    LEVEL_090_TITLE: 'ENCONTRE O AMIGO DO RULI',
    LEVEL_090_HINT_1: 'Ele não está atrás das coisas.',
    LEVEL_090_HINT_2: 'Olhe as beiradas da tela.',
    LEVEL_090_HINT_3: 'Toque no amigo rosa espiando na direita.',

    LEVEL_091_TITLE: 'DESENHE UMA PONTE',
    LEVEL_091_HINT_1: 'Não tem ponte pronta.',
    LEVEL_091_HINT_2: 'Você pode desenhar com o dedo.',
    LEVEL_091_HINT_3: 'Trace uma linha de uma beirada do buraco até a outra.',

    LEVEL_092_TITLE: 'LIGUE OS PONTOS',
    LEVEL_092_HINT_1: 'Os números mostram a ordem.',
    LEVEL_092_HINT_2: 'Uma linha só, sem tirar o dedo.',
    LEVEL_092_HINT_3: 'Trace passando pelo 1, 2, 3, 4 e 5.',

    LEVEL_093_TITLE: 'LEVE A ÁGUA ATÉ A PLANTA',
    LEVEL_093_HINT_1: 'Os canos estão virados.',
    LEVEL_093_HINT_2: 'Canos giram.',
    LEVEL_093_HINT_3: 'Gire os canos até formarem um caminho da torneira até a planta.',

    LEVEL_094_TITLE: 'ABRA O COFRE',
    LEVEL_094_HINT_1: 'A senha está sempre à vista.',
    LEVEL_094_HINT_2: 'Que número está escrito lá em cima?',
    LEVEL_094_HINT_3: 'Gire os discos até 9 e 4 ficarem embaixo das setas.',

    LEVEL_095_TITLE: 'FAÇA O RULI DORMIR',
    LEVEL_095_HINT_1: 'Luz e barulho atrapalham.',
    LEVEL_095_HINT_2: 'E depois... silêncio.',
    LEVEL_095_HINT_3: 'Apague a luz, guarde o rádio na caixa e não toque em nada por 3 segundos.',

    LEVEL_096_TITLE: 'NÃO TOQUE EM NADA',
    LEVEL_096_HINT_1: 'O vaso vai cair.',
    LEVEL_096_HINT_2: 'Será que precisa de você?',
    LEVEL_096_HINT_3: 'Não toque em nada. A almofada já está lá.',

    LEVEL_097_TITLE: 'DEIXE TODOS IGUAIS',
    LEVEL_097_HINT_1: 'Iguais em tudo.',
    LEVEL_097_HINT_2: 'Cor e tamanho.',
    LEVEL_097_HINT_3: 'Pinte os três da mesma cor e deixe todos do mesmo tamanho.',

    LEVEL_098_TITLE: 'PINTE A FOLHA DE VERDE',
    LEVEL_098_HINT_1: 'Não existe tinta verde.',
    LEVEL_098_HINT_2: 'Duas cores juntas fazem uma terceira.',
    LEVEL_098_HINT_3: 'Junte a gota azul com a amarela e leve a verde até a folha.',

    LEVEL_099_TITLE: 'QUEBRE TODAS AS REGRAS',
    LEVEL_099_HINT_1: 'Leia as placas.',
    LEVEL_099_HINT_2: 'Faça o contrário de cada uma.',
    LEVEL_099_HINT_3: 'Toque na estrela, mova a caixa e depois espere.',

    LEVEL_100_TITLE: 'ESTA É A [[w_last|ÚLTIMA]] FASE',
    LEVEL_100_HINT_1: 'Quem disse que é a última?',
    LEVEL_100_HINT_2: 'A frase pode mudar.',
    LEVEL_100_HINT_3: 'Tire a palavra ÚLTIMA da frase.',
    UI_DEMO_END_TITLE: 'VOCÊ COMPLETOU AS 100 FASES!',
    UI_DEMO_END_TEXT: 'MAIS FASES EM BREVE'
  }
};
